#ifndef __qp_ana_csr_REGS_H__
#define __qp_ana_csr_REGS_H__

//#include "common.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef REG_BASE_C_MODULE
// ----------------- qp_ana_csr Bit Field Definitions -------------------

#define PACKING
typedef unsigned int UINT32;
typedef unsigned int FIELD;

typedef struct
{
    

        FIELD RG_QP_RX_DAC_EN           : 1;
        FIELD RG_QP_RX_DAC_PWD          : 1;
        FIELD rsv_2                     : 2;
        FIELD RG_QP_RX_DAC_MUX          : 4;
        FIELD RG_QP_RX_T2R_EN           : 1;
        FIELD RG_QP_RX_50_LOWER         : 3;
        FIELD RG_QP_SIGDET_VTH          : 2;
        FIELD RG_QP_SIGDET_LPF          : 2;
        FIELD RG_QP_SIGDET_HF           : 2;
        FIELD RG_QP_LFPS_LPF_AUX        : 1;
        FIELD RG_QP_LFPS_CMPOUT_SEL     : 1;
        FIELD RG_QP_LFPS_SLCOUT_SEL     : 1;
        FIELD RG_QP_LFPS_LPF            : 2;
        FIELD RG_QP_LFPS_LPF_I          : 2;
        FIELD RG_QP_LFPS_LPF_I_SEL      : 1;
        FIELD RG_QP_LFPS_MON_EN         : 1;
        FIELD RG_QP_RXAFE_DCMON_SEL     : 3;
        FIELD rsv_30                    : 2;
    
    
} REG_RG_QP_RX_DAC_EN, *PREG_RG_QP_RX_DAC_EN;

typedef struct
{
    

        FIELD RG_QP_RXAFE_RESERVE       : 8;
        FIELD RG_QP_RX_DAC_MEAS_EN      : 1;
        FIELD RG_QP_RX_VCMHPFSEL        : 1;
        FIELD RG_QP_CDR_PD_EDGE_DIS     : 1;
        FIELD RG_QP_CDR_PD_10B_EN       : 1;
        FIELD rsv_12                    : 20;
    
    
} REG_RG_QP_RXAFE_RESERVE, *PREG_RG_QP_RXAFE_RESERVE;

typedef struct
{
    

        FIELD RG_QP_CDR_LPF_BOT_LIM     : 19;
        FIELD rsv_19                    : 1;
        FIELD RG_QP_CDR_LPF_KI_GAIN     : 3;
        FIELD rsv_23                    : 1;
        FIELD RG_QP_CDR_LPF_KP_GAIN     : 3;
        FIELD RG_QP_CDR_LPF_LIN_LIM     : 4;
        FIELD RG_QP_CDR_LPF_MJV_EN      : 1;
    
    
} REG_RG_QP_CDR_LPF_BOT_LIM, *PREG_RG_QP_CDR_LPF_BOT_LIM;

typedef struct
{
    

        FIELD RG_QP_CDR_LPF_MJV_LIM     : 4;
        FIELD RG_QP_CDR_LPF_RATIO       : 2;
        FIELD rsv_6                     : 26;
    
    
} REG_RG_QP_CDR_LPF_MJV_LIM, *PREG_RG_QP_CDR_LPF_MJV_LIM;

typedef struct
{
    

        FIELD RG_QP_CDR_LPF_TOP_LIM     : 19;
        FIELD RG_QP_CDR_LPF_SNAPSHOT    : 1;
        FIELD RG_QP_CDR_LPF_SET         : 1;
        FIELD rsv_21                    : 9;
        FIELD RG_QP_CDR_LPF_ONESHOT_OUT_SEL : 2;
    
    
} REG_RG_QP_CDR_LPF_TOP_LIM, *PREG_RG_QP_CDR_LPF_TOP_LIM;

typedef struct
{
    

        FIELD RG_QP_CDR_LPF_SETVALUE    : 19;
        FIELD RG_QP_CDR_LPF_ONESHOT_STEP : 3;
        FIELD RG_QP_CDR_LPF_PISTEP_ONESHOT : 1;
        FIELD RG_QP_CDR_LPF_PISTEP_SEL  : 1;
        FIELD RG_QP_CDR_LPF_UD_GATING   : 1;
        FIELD RG_QP_CDR_PR_BETA_SEL     : 4;
        FIELD RG_QP_CDR_PR_BUF_IN_SR    : 3;
    
    
} REG_RG_QP_CDR_LPF_SETVALUE, *PREG_RG_QP_CDR_LPF_SETVALUE;

typedef struct
{
    

        FIELD RG_QP_CDR_PR_CKREF_DIV1   : 2;
        FIELD RG_QP_CDR_PR_CKREF_DIV    : 2;
        FIELD RG_QP_CDR_PR_CORSIG_OPT   : 2;
        FIELD RG_QP_CDR_PR_COR_HBW_EN   : 1;
        FIELD rsv_7                     : 1;
        FIELD RG_QP_CDR_PR_DAC_BAND     : 5;
        FIELD RG_QP_CDR_PR_DCMON_EN     : 1;
        FIELD rsv_14                    : 2;
        FIELD RG_QP_CDR_PR_DCMON_SEL    : 3;
        FIELD RG_QP_CDR_PR_INJ_FORCE_OFF : 1;
        FIELD RG_QP_CDR_PR_INJ_FORCE_ON : 1;
        FIELD rsv_21                    : 3;
        FIELD RG_QP_CDR_PR_KBAND_DIV    : 3;
        FIELD rsv_27                    : 5;
    
    
} REG_RG_QP_CDR_PR_CKREF_DIV1, *PREG_RG_QP_CDR_PR_CKREF_DIV1;

typedef struct
{
    

        FIELD RG_QP_CDR_PR_KBAND_DIV_PCIE : 6;
        FIELD RG_QP_CDR_PR_KBAND_PCIE_MODE : 1;
        FIELD RG_QP_CDR_PR_LDO_FORCE_ON : 1;
        FIELD RG_QP_CDR_PR_MONCK_EN     : 1;
        FIELD rsv_9                     : 3;
        FIELD RG_QP_CDR_PR_MONCK_MUX    : 3;
        FIELD RG_QP_CDR_PR_MONPI_EN     : 1;
        FIELD RG_QP_CDR_PR_MONPR_EN     : 1;
        FIELD RG_QP_CDR_PR_RSTB_BYPASS  : 1;
        FIELD RG_QP_CDR_PR_RST_DLY      : 2;
        FIELD RG_QP_CDR_PR_TDC_REF_SEL  : 2;
        FIELD rsv_22                    : 2;
        FIELD RG_QP_CDR_PR_VCOADC_OS    : 4;
        FIELD RG_QP_CDR_PR_VREG_CKBUF_VAL : 2;
        FIELD RG_QP_CDR_PR_XFICK_EN     : 1;
        FIELD RG_QP_CDR_FORCE_IBANDLPF_C_OFF : 1;
    
    
} REG_RG_QP_CDR_PR_KBAND_DIV_PCIE, *PREG_RG_QP_CDR_PR_KBAND_DIV_PCIE;

typedef struct
{
    

        FIELD RG_QP_CDR_FORCE_IBANDLPF_R_OFF : 1;
        FIELD RG_QP_CDR_PICAL_INV       : 1;
        FIELD RG_QP_CDR_PICAL_SEL       : 1;
        FIELD RG_QP_CDR_PIEYEBD4_SEL    : 1;
        FIELD RG_QP_CDR_PIEYE_XOR_EN    : 1;
        FIELD RG_QP_CDR_PI_CK_INV       : 1;
        FIELD RG_QP_CDR_PHYCK_DIV       : 7;
        FIELD RG_QP_CDR_PHYCK_RSTB      : 1;
        FIELD rsv_14                    : 2;
        FIELD RG_QP_CDR_PHYCK_SEL       : 2;
        FIELD rsv_18                    : 2;
        FIELD RG_QP_RX_MPX_SEL          : 3;
        FIELD rsv_23                    : 1;
        FIELD RG_QP_CDR_REFCK_DIV2_EN   : 1;
        FIELD RG_QP_RX_D0_LL_RESERVED   : 6;
        FIELD rsv_31                    : 1;
    
    
} REG_RG_QP_CDR_FORCE_IBANDLPF_R_OFF, *PREG_RG_QP_CDR_FORCE_IBANDLPF_R_OFF;

typedef struct
{
    

        FIELD RG_QP_RX_D0_HS_RESERVED   : 14;
        FIELD rsv_14                    : 2;
        FIELD RG_QP_RX_D1_HS_RESERVED   : 15;
        FIELD rsv_31                    : 1;
    
    
} REG_RG_QP_RX_D0_HS_RESERVED, *PREG_RG_QP_RX_D0_HS_RESERVED;

typedef struct
{
    

        FIELD RG_QP_TX_MODE_16B_EN      : 1;
        FIELD RG_QP_TXLBRX_EN           : 1;
        FIELD RG_QP_TX_VLMON_EN         : 1;
        FIELD RG_QP_TX_VLMON_SEL        : 3;
        FIELD RG_QP_TX_CKMON_EN         : 1;
        FIELD rsv_7                     : 2;
        FIELD RG_QP_TX_CKMON_SEL        : 4;
        FIELD rsv_13                    : 3;
        FIELD RG_QP_TX_RESERVE          : 16;
    
    
} REG_RG_QP_TX_MODE_16B_EN, *PREG_RG_QP_TX_MODE_16B_EN;

typedef struct
{
    

        FIELD RG_QP_RXLBTX_EN           : 1;
        FIELD RG_QP_TX250MCK_INVB       : 1;
        FIELD RG_QP_TX_CHGPLR_CN1       : 1;
        FIELD RG_QP_TX_CHGPLR_C1        : 1;
        FIELD RG_QP_TX_CHGPLR_C2        : 1;
        FIELD RG_QP_TX_SR_REDUCTION     : 3;
        FIELD RG_QP_TX_INT_EN           : 1;
        FIELD rsv_9                     : 7;
        FIELD RG_QP_TX_TERMCAL_VREF_H   : 3;
        FIELD rsv_19                    : 2;
        FIELD RG_QP_TX_TERMCAL_VREF_L   : 3;
        FIELD RG_QP_TX_TERMCAL_SELPN    : 1;
        FIELD RG_QP_TX_RXDET_METHOD     : 1;
        FIELD RG_QP_TX_AUTOZERO_EN      : 1;
        FIELD RG_QP_TX_DMEDGEGEN_EN     : 1;
        FIELD rsv_28                    : 4;
    
    
} REG_RG_QP_RXLBTX_EN, *PREG_RG_QP_RXLBTX_EN;

typedef struct
{
    

        FIELD RG_QP_BGR_EN              : 1;
        FIELD RG_QP_CHPEN               : 1;
        FIELD RG_QP_BG_DIV              : 2;
        FIELD RG_QP_MPX_EN              : 1;
        FIELD rsv_5                     : 4;
        FIELD RG_QP_MPX_SEL             : 5;
        FIELD rsv_14                    : 3;
        FIELD RG_QP_VRT_VREF_SEL        : 4;
        FIELD RG_QP_BIAS_V2V_CAL        : 6;
        FIELD RG_QP_BG_MONEN            : 1;
        FIELD rsv_28                    : 4;
    
    
} REG_RG_QP_BGR_EN, *PREG_RG_QP_BGR_EN;

typedef struct
{
    

        FIELD RG_PCIE_CLKDRV_IMPSEL     : 5;
        FIELD rsv_5                     : 4;
        FIELD RG_PCIE_CLKDRV_RP         : 5;
        FIELD RG_PCIE_CLKDRV_HZ         : 1;
        FIELD rsv_15                    : 1;
        FIELD RG_PCIE_CLKDRV_OFFSET     : 3;
        FIELD RG_PCIE_CLKDRV_SLEW       : 2;
        FIELD RG_PCIE_CLKDRV_DUTY       : 2;
        FIELD RG_PCIE_CLKDRV_FORCEIN    : 2;
        FIELD RG_PCIE_CLKDRV_AMP        : 3;
        FIELD rsv_28                    : 1;
        FIELD RG_PCIE_CLKDET_VTH        : 2;
        FIELD RG_QP_TDC_AUTOEN          : 1;
    
    
} REG_RG_PCIE_CLKDRV_IMPSEL, *PREG_RG_PCIE_CLKDRV_IMPSEL;

typedef struct
{
    

        FIELD RG_QP_TDC_FT_CK_EN        : 1;
        FIELD RG_QP_TDC_MON_CK_EN       : 1;
        FIELD rsv_2                     : 3;
        FIELD RG_QP_PLL_MONCK_SEL       : 3;
        FIELD RG_VUSB10_ON              : 1;
        FIELD RG_QP_XTAL_TOP_RESERVE0   : 8;
        FIELD RG_QP_PLL_RST_DLY         : 2;
        FIELD RG_QP_PLL_DEBUG_SEL       : 1;
        FIELD rsv_20                    : 1;
        FIELD RG_QP_PLL_IBAND           : 11;
    
    
} REG_RG_QP_TDC_FT_CK_EN, *PREG_RG_QP_TDC_FT_CK_EN;

typedef struct
{
    

        FIELD RG_QP_PLL_IPLL_DIG_PWR_SEL : 1;
        FIELD RG_QP_PLL_KBAND_KFC       : 2;
        FIELD RG_QP_PLL_KBAND_MEAS_EN   : 1;
        FIELD RG_QP_PLL_LOAD_EN         : 1;
        FIELD RG_QP_PLL_LDOLPF_VSEL     : 2;
        FIELD RG_QP_PLL_LDOPFD_VSEL     : 2;
        FIELD RG_QP_PLL_LDOVCO_VSEL     : 2;
        FIELD RG_QP_PLL_MONCK_DIV4_EN   : 1;
        FIELD RG_QP_PLL_MONCK_EN        : 1;
        FIELD RG_QP_PLL_MONREF_EN       : 1;
        FIELD RG_QP_PLL_MONVC_EN        : 1;
        FIELD rsv_15                    : 1;
        FIELD RG_QP_PLL_MON_LDO_SEL     : 3;
        FIELD RG_QP_PLL_OSCAL_ENB       : 1;
        FIELD rsv_20                    : 1;
        FIELD RG_QP_PLL_POSTDIV         : 2;
        FIELD rsv_23                    : 2;
        FIELD RG_QP_PLL_PREDIV          : 2;
        FIELD RG_QP_PLL_RLP_SEL         : 1;
        FIELD RG_QP_PLL_TCL_EN          : 1;
        FIELD RG_QP_PLL_SDM_DI_LS       : 2;
        FIELD rsv_31                    : 1;
    
    
} REG_RG_QP_PLL_IPLL_DIG_PWR_SEL, *PREG_RG_QP_PLL_IPLL_DIG_PWR_SEL;

typedef struct
{
    

        FIELD RG_QP_PLL_SDM_ORD         : 2;
        FIELD RG_QP_PLL_SDM_OUT         : 1;
        FIELD RG_QP_PLL_SSC_PHASE_INI   : 1;
        FIELD RG_QP_PLL_SSC_TRI_EN      : 1;
        FIELD RG_QP_PLL_POST_MONCK_EN   : 1;
        FIELD rsv_6                     : 3;
        FIELD RG_QP_PLL_POST_MONCK_SEL  : 2;
        FIELD RG_QP_PLL_FREQ_MEAS_EN    : 1;
        FIELD rsv_12                    : 20;
    
    
} REG_RG_QP_PLL_SDM_ORD, *PREG_RG_QP_PLL_SDM_ORD;

// ----------------- qp_ana_csr  Grouping Definitions -------------------
// ----------------- qp_ana_csr Register Definition -------------------
#if 0
typedef volatile 
{
    REG_RG_QP_RX_DAC_EN             RG_QP_RX_DAC_EN;  // F000
    REG_RG_QP_RXAFE_RESERVE         RG_QP_RXAFE_RESERVE; // F004
    REG_RG_QP_CDR_LPF_BOT_LIM       RG_QP_CDR_LPF_BOT_LIM; // F008
    REG_RG_QP_CDR_LPF_MJV_LIM       RG_QP_CDR_LPF_MJV_LIM; // F00C
    REG_RG_QP_CDR_LPF_TOP_LIM       RG_QP_CDR_LPF_TOP_LIM; // F010
    REG_RG_QP_CDR_LPF_SETVALUE      RG_QP_CDR_LPF_SETVALUE; // F014
    REG_RG_QP_CDR_PR_CKREF_DIV1     RG_QP_CDR_PR_CKREF_DIV1; // F018
    REG_RG_QP_CDR_PR_KBAND_DIV_PCIE RG_QP_CDR_PR_KBAND_DIV_PCIE; // F01C
    REG_RG_QP_CDR_FORCE_IBANDLPF_R_OFF RG_QP_CDR_FORCE_IBANDLPF_R_OFF; // F020
    REG_RG_QP_RX_D0_HS_RESERVED     RG_QP_RX_D0_HS_RESERVED; // F024
    REG_RG_QP_TX_MODE_16B_EN        RG_QP_TX_MODE_16B_EN; // F028
    REG_RG_QP_RXLBTX_EN             RG_QP_RXLBTX_EN;  // F02C
    REG_RG_QP_BGR_EN                RG_QP_BGR_EN;     // F030
    REG_RG_PCIE_CLKDRV_IMPSEL       RG_PCIE_CLKDRV_IMPSEL; // F034
    REG_RG_QP_TDC_FT_CK_EN          RG_QP_TDC_FT_CK_EN; // F038
    REG_RG_QP_PLL_IPLL_DIG_PWR_SEL  RG_QP_PLL_IPLL_DIG_PWR_SEL; // F03C
    REG_RG_QP_PLL_SDM_ORD           RG_QP_PLL_SDM_ORD; // F040
}qp_ana_csr_REGS, *Pqp_ana_csr_REGS;

// ---------- qp_ana_csr Enum Definitions      ----------
// ---------- qp_ana_csr C Macro Definitions   ----------
extern Pqp_ana_csr_REGS g_qp_ana_csr_BASE;

#define qp_ana_csr_BASE                                        (g_qp_ana_csr_BASE)
#endif

#define _RG_QP_RX_DAC_EN		0xF000
#define _RG_QP_RXAFE_RESERVE		0xF004
#define _RG_QP_CDR_LPF_BOT_LIM		0xF008
#define _RG_QP_CDR_LPF_MJV_LIM		0xF00C
#define _RG_QP_CDR_LPF_TOP_LIM		0xF010
#define _RG_QP_CDR_LPF_SETVALUE		0xF014
#define _RG_QP_CDR_PR_CKREF_DIV1		0xF018
#define _RG_QP_CDR_PR_KBAND_DIV_PCIE		0xF01C
#define _RG_QP_CDR_FORCE_IBANDLPF_R_OFF		0xF020
#define _RG_QP_RX_D0_HS_RESERVED		0xF024
#define _RG_QP_TX_MODE_16B_EN		0xF028
#define _RG_QP_RXLBTX_EN		0xF02C
#define _RG_QP_BGR_EN		0xF030
#define _RG_PCIE_CLKDRV_IMPSEL		0xF034
#define _RG_QP_TDC_FT_CK_EN		0xF038
#define _RG_QP_PLL_IPLL_DIG_PWR_SEL		0xF03C
#define _RG_QP_PLL_SDM_ORD		0xF040

#endif


#define RG_QP_RX_DAC_EN_FLD_RG_QP_RXAFE_DCMON_SEL              REG_FLD(3, 27)
#define RG_QP_RX_DAC_EN_FLD_RG_QP_LFPS_MON_EN                  REG_FLD(1, 26)
#define RG_QP_RX_DAC_EN_FLD_RG_QP_LFPS_LPF_I_SEL               REG_FLD(1, 25)
#define RG_QP_RX_DAC_EN_FLD_RG_QP_LFPS_LPF_I                   REG_FLD(2, 23)
#define RG_QP_RX_DAC_EN_FLD_RG_QP_LFPS_LPF                     REG_FLD(2, 21)
#define RG_QP_RX_DAC_EN_FLD_RG_QP_LFPS_SLCOUT_SEL              REG_FLD(1, 20)
#define RG_QP_RX_DAC_EN_FLD_RG_QP_LFPS_CMPOUT_SEL              REG_FLD(1, 19)
#define RG_QP_RX_DAC_EN_FLD_RG_QP_LFPS_LPF_AUX                 REG_FLD(1, 18)
#define RG_QP_RX_DAC_EN_FLD_RG_QP_SIGDET_HF                    REG_FLD(2, 16)
#define RG_QP_RX_DAC_EN_FLD_RG_QP_SIGDET_LPF                   REG_FLD(2, 14)
#define RG_QP_RX_DAC_EN_FLD_RG_QP_SIGDET_VTH                   REG_FLD(2, 12)
#define RG_QP_RX_DAC_EN_FLD_RG_QP_RX_50_LOWER                  REG_FLD(3, 9)
#define RG_QP_RX_DAC_EN_FLD_RG_QP_RX_T2R_EN                    REG_FLD(1, 8)
#define RG_QP_RX_DAC_EN_FLD_RG_QP_RX_DAC_MUX                   REG_FLD(4, 4)
#define RG_QP_RX_DAC_EN_FLD_RG_QP_RX_DAC_PWD                   REG_FLD(1, 1)
#define RG_QP_RX_DAC_EN_FLD_RG_QP_RX_DAC_EN                    REG_FLD(1, 0)

#define RG_QP_RXAFE_RESERVE_FLD_RG_QP_CDR_PD_10B_EN            REG_FLD(1, 11)
#define RG_QP_RXAFE_RESERVE_FLD_RG_QP_CDR_PD_EDGE_DIS          REG_FLD(1, 10)
#define RG_QP_RXAFE_RESERVE_FLD_RG_QP_RX_VCMHPFSEL             REG_FLD(1, 9)
#define RG_QP_RXAFE_RESERVE_FLD_RG_QP_RX_DAC_MEAS_EN           REG_FLD(1, 8)
#define RG_QP_RXAFE_RESERVE_FLD_RG_QP_RXAFE_RESERVE            REG_FLD(8, 0)

#define RG_QP_CDR_LPF_BOT_LIM_FLD_RG_QP_CDR_LPF_MJV_EN         REG_FLD(1, 31)
#define RG_QP_CDR_LPF_BOT_LIM_FLD_RG_QP_CDR_LPF_LIN_LIM        REG_FLD(4, 27)
#define RG_QP_CDR_LPF_BOT_LIM_FLD_RG_QP_CDR_LPF_KP_GAIN        REG_FLD(3, 24)
#define RG_QP_CDR_LPF_BOT_LIM_FLD_RG_QP_CDR_LPF_KI_GAIN        REG_FLD(3, 20)
#define RG_QP_CDR_LPF_BOT_LIM_FLD_RG_QP_CDR_LPF_BOT_LIM        REG_FLD(19, 0)

#define RG_QP_CDR_LPF_MJV_LIM_FLD_RG_QP_CDR_LPF_RATIO          REG_FLD(2, 4)
#define RG_QP_CDR_LPF_MJV_LIM_FLD_RG_QP_CDR_LPF_MJV_LIM        REG_FLD(4, 0)

#define RG_QP_CDR_LPF_TOP_LIM_FLD_RG_QP_CDR_LPF_ONESHOT_OUT_SEL REG_FLD(2, 30)
#define RG_QP_CDR_LPF_TOP_LIM_FLD_RG_QP_CDR_LPF_SET            REG_FLD(1, 20)
#define RG_QP_CDR_LPF_TOP_LIM_FLD_RG_QP_CDR_LPF_SNAPSHOT       REG_FLD(1, 19)
#define RG_QP_CDR_LPF_TOP_LIM_FLD_RG_QP_CDR_LPF_TOP_LIM        REG_FLD(19, 0)

#define RG_QP_CDR_LPF_SETVALUE_FLD_RG_QP_CDR_PR_BUF_IN_SR      REG_FLD(3, 29)
#define RG_QP_CDR_LPF_SETVALUE_FLD_RG_QP_CDR_PR_BETA_SEL       REG_FLD(4, 25)
#define RG_QP_CDR_LPF_SETVALUE_FLD_RG_QP_CDR_LPF_UD_GATING     REG_FLD(1, 24)
#define RG_QP_CDR_LPF_SETVALUE_FLD_RG_QP_CDR_LPF_PISTEP_SEL    REG_FLD(1, 23)
#define RG_QP_CDR_LPF_SETVALUE_FLD_RG_QP_CDR_LPF_PISTEP_ONESHOT REG_FLD(1, 22)
#define RG_QP_CDR_LPF_SETVALUE_FLD_RG_QP_CDR_LPF_ONESHOT_STEP  REG_FLD(3, 19)
#define RG_QP_CDR_LPF_SETVALUE_FLD_RG_QP_CDR_LPF_SETVALUE      REG_FLD(19, 0)

#define RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_KBAND_DIV     REG_FLD(3, 24)
#define RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_INJ_FORCE_ON  REG_FLD(1, 20)
#define RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_INJ_FORCE_OFF REG_FLD(1, 19)
#define RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_DCMON_SEL     REG_FLD(3, 16)
#define RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_DCMON_EN      REG_FLD(1, 13)
#define RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_DAC_BAND      REG_FLD(5, 8)
#define RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_COR_HBW_EN    REG_FLD(1, 6)
#define RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_CORSIG_OPT    REG_FLD(2, 4)
#define RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_CKREF_DIV     REG_FLD(2, 2)
#define RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_CKREF_DIV1    REG_FLD(2, 0)

#define RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_FORCE_IBANDLPF_C_OFF REG_FLD(1, 31)
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_XFICK_EN  REG_FLD(1, 30)
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_VREG_CKBUF_VAL REG_FLD(2, 28)
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_VCOADC_OS REG_FLD(4, 24)
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_TDC_REF_SEL REG_FLD(2, 20)
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_RST_DLY   REG_FLD(2, 18)
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_RSTB_BYPASS REG_FLD(1, 17)
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_MONPR_EN  REG_FLD(1, 16)
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_MONPI_EN  REG_FLD(1, 15)
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_MONCK_MUX REG_FLD(3, 12)
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_MONCK_EN  REG_FLD(1, 8)
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_LDO_FORCE_ON REG_FLD(1, 7)
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_KBAND_PCIE_MODE REG_FLD(1, 6)
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_KBAND_DIV_PCIE REG_FLD(6, 0)

#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_RX_D0_LL_RESERVED REG_FLD(6, 25)
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_REFCK_DIV2_EN REG_FLD(1, 24)
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_RX_MPX_SEL    REG_FLD(3, 20)
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PHYCK_SEL REG_FLD(2, 16)
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PHYCK_RSTB REG_FLD(1, 13)
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PHYCK_DIV REG_FLD(7, 6)
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PI_CK_INV REG_FLD(1, 5)
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PIEYE_XOR_EN REG_FLD(1, 4)
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PIEYEBD4_SEL REG_FLD(1, 3)
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PICAL_SEL REG_FLD(1, 2)
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PICAL_INV REG_FLD(1, 1)
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_FORCE_IBANDLPF_R_OFF REG_FLD(1, 0)

#define RG_QP_RX_D0_HS_RESERVED_FLD_RG_QP_RX_D1_HS_RESERVED    REG_FLD(15, 16)
#define RG_QP_RX_D0_HS_RESERVED_FLD_RG_QP_RX_D0_HS_RESERVED    REG_FLD(14, 0)

#define RG_QP_TX_MODE_16B_EN_FLD_RG_QP_TX_RESERVE              REG_FLD(16, 16)
#define RG_QP_TX_MODE_16B_EN_FLD_RG_QP_TX_CKMON_SEL            REG_FLD(4, 9)
#define RG_QP_TX_MODE_16B_EN_FLD_RG_QP_TX_CKMON_EN             REG_FLD(1, 6)
#define RG_QP_TX_MODE_16B_EN_FLD_RG_QP_TX_VLMON_SEL            REG_FLD(3, 3)
#define RG_QP_TX_MODE_16B_EN_FLD_RG_QP_TX_VLMON_EN             REG_FLD(1, 2)
#define RG_QP_TX_MODE_16B_EN_FLD_RG_QP_TXLBRX_EN               REG_FLD(1, 1)
#define RG_QP_TX_MODE_16B_EN_FLD_RG_QP_TX_MODE_16B_EN          REG_FLD(1, 0)

#define RG_QP_RXLBTX_EN_FLD_RG_QP_TX_DMEDGEGEN_EN              REG_FLD(1, 27)
#define RG_QP_RXLBTX_EN_FLD_RG_QP_TX_AUTOZERO_EN               REG_FLD(1, 26)
#define RG_QP_RXLBTX_EN_FLD_RG_QP_TX_RXDET_METHOD              REG_FLD(1, 25)
#define RG_QP_RXLBTX_EN_FLD_RG_QP_TX_TERMCAL_SELPN             REG_FLD(1, 24)
#define RG_QP_RXLBTX_EN_FLD_RG_QP_TX_TERMCAL_VREF_L            REG_FLD(3, 21)
#define RG_QP_RXLBTX_EN_FLD_RG_QP_TX_TERMCAL_VREF_H            REG_FLD(3, 16)
#define RG_QP_RXLBTX_EN_FLD_RG_QP_TX_INT_EN                    REG_FLD(1, 8)
#define RG_QP_RXLBTX_EN_FLD_RG_QP_TX_SR_REDUCTION              REG_FLD(3, 5)
#define RG_QP_RXLBTX_EN_FLD_RG_QP_TX_CHGPLR_C2                 REG_FLD(1, 4)
#define RG_QP_RXLBTX_EN_FLD_RG_QP_TX_CHGPLR_C1                 REG_FLD(1, 3)
#define RG_QP_RXLBTX_EN_FLD_RG_QP_TX_CHGPLR_CN1                REG_FLD(1, 2)
#define RG_QP_RXLBTX_EN_FLD_RG_QP_TX250MCK_INVB                REG_FLD(1, 1)
#define RG_QP_RXLBTX_EN_FLD_RG_QP_RXLBTX_EN                    REG_FLD(1, 0)

#define RG_QP_BGR_EN_FLD_RG_QP_BG_MONEN                        REG_FLD(1, 27)
#define RG_QP_BGR_EN_FLD_RG_QP_BIAS_V2V_CAL                    REG_FLD(6, 21)
#define RG_QP_BGR_EN_FLD_RG_QP_VRT_VREF_SEL                    REG_FLD(4, 17)
#define RG_QP_BGR_EN_FLD_RG_QP_MPX_SEL                         REG_FLD(5, 9)
#define RG_QP_BGR_EN_FLD_RG_QP_MPX_EN                          REG_FLD(1, 4)
#define RG_QP_BGR_EN_FLD_RG_QP_BG_DIV                          REG_FLD(2, 2)
#define RG_QP_BGR_EN_FLD_RG_QP_CHPEN                           REG_FLD(1, 1)
#define RG_QP_BGR_EN_FLD_RG_QP_BGR_EN                          REG_FLD(1, 0)

#define RG_PCIE_CLKDRV_IMPSEL_FLD_RG_QP_TDC_AUTOEN             REG_FLD(1, 31)
#define RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDET_VTH           REG_FLD(2, 29)
#define RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_AMP           REG_FLD(3, 25)
#define RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_FORCEIN       REG_FLD(2, 23)
#define RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_DUTY          REG_FLD(2, 21)
#define RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_SLEW          REG_FLD(2, 19)
#define RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_OFFSET        REG_FLD(3, 16)
#define RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_HZ            REG_FLD(1, 14)
#define RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_RP            REG_FLD(5, 9)
#define RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_IMPSEL        REG_FLD(5, 0)

#define RG_QP_TDC_FT_CK_EN_FLD_RG_QP_PLL_IBAND                 REG_FLD(11, 21)
#define RG_QP_TDC_FT_CK_EN_FLD_RG_QP_PLL_DEBUG_SEL             REG_FLD(1, 19)
#define RG_QP_TDC_FT_CK_EN_FLD_RG_QP_PLL_RST_DLY               REG_FLD(2, 17)
#define RG_QP_TDC_FT_CK_EN_FLD_RG_QP_XTAL_TOP_RESERVE0         REG_FLD(8, 9)
#define RG_QP_TDC_FT_CK_EN_FLD_RG_VUSB10_ON                    REG_FLD(1, 8)
#define RG_QP_TDC_FT_CK_EN_FLD_RG_QP_PLL_MONCK_SEL             REG_FLD(3, 5)
#define RG_QP_TDC_FT_CK_EN_FLD_RG_QP_TDC_MON_CK_EN             REG_FLD(1, 1)
#define RG_QP_TDC_FT_CK_EN_FLD_RG_QP_TDC_FT_CK_EN              REG_FLD(1, 0)

#define RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_SDM_DI_LS     REG_FLD(2, 29)
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_TCL_EN        REG_FLD(1, 28)
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_RLP_SEL       REG_FLD(1, 27)
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_PREDIV        REG_FLD(2, 25)
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_POSTDIV       REG_FLD(2, 21)
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_OSCAL_ENB     REG_FLD(1, 19)
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_MON_LDO_SEL   REG_FLD(3, 16)
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_MONVC_EN      REG_FLD(1, 14)
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_MONREF_EN     REG_FLD(1, 13)
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_MONCK_EN      REG_FLD(1, 12)
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_MONCK_DIV4_EN REG_FLD(1, 11)
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_LDOVCO_VSEL   REG_FLD(2, 9)
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_LDOPFD_VSEL   REG_FLD(2, 7)
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_LDOLPF_VSEL   REG_FLD(2, 5)
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_LOAD_EN       REG_FLD(1, 4)
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_KBAND_MEAS_EN REG_FLD(1, 3)
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_KBAND_KFC     REG_FLD(2, 1)
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_IPLL_DIG_PWR_SEL REG_FLD(1, 0)

#define RG_QP_PLL_SDM_ORD_FLD_RG_QP_PLL_FREQ_MEAS_EN           REG_FLD(1, 11)
#define RG_QP_PLL_SDM_ORD_FLD_RG_QP_PLL_POST_MONCK_SEL         REG_FLD(2, 9)
#define RG_QP_PLL_SDM_ORD_FLD_RG_QP_PLL_POST_MONCK_EN          REG_FLD(1, 5)
#define RG_QP_PLL_SDM_ORD_FLD_RG_QP_PLL_SSC_TRI_EN             REG_FLD(1, 4)
#define RG_QP_PLL_SDM_ORD_FLD_RG_QP_PLL_SSC_PHASE_INI          REG_FLD(1, 3)
#define RG_QP_PLL_SDM_ORD_FLD_RG_QP_PLL_SDM_OUT                REG_FLD(1, 2)
#define RG_QP_PLL_SDM_ORD_FLD_RG_QP_PLL_SDM_ORD                REG_FLD(2, 0)

#define RG_QP_RX_DAC_EN_GET_RG_QP_RXAFE_DCMON_SEL(reg32)       REG_FLD_GET(RG_QP_RX_DAC_EN_FLD_RG_QP_RXAFE_DCMON_SEL, (reg32))
#define RG_QP_RX_DAC_EN_GET_RG_QP_LFPS_MON_EN(reg32)           REG_FLD_GET(RG_QP_RX_DAC_EN_FLD_RG_QP_LFPS_MON_EN, (reg32))
#define RG_QP_RX_DAC_EN_GET_RG_QP_LFPS_LPF_I_SEL(reg32)        REG_FLD_GET(RG_QP_RX_DAC_EN_FLD_RG_QP_LFPS_LPF_I_SEL, (reg32))
#define RG_QP_RX_DAC_EN_GET_RG_QP_LFPS_LPF_I(reg32)            REG_FLD_GET(RG_QP_RX_DAC_EN_FLD_RG_QP_LFPS_LPF_I, (reg32))
#define RG_QP_RX_DAC_EN_GET_RG_QP_LFPS_LPF(reg32)              REG_FLD_GET(RG_QP_RX_DAC_EN_FLD_RG_QP_LFPS_LPF, (reg32))
#define RG_QP_RX_DAC_EN_GET_RG_QP_LFPS_SLCOUT_SEL(reg32)       REG_FLD_GET(RG_QP_RX_DAC_EN_FLD_RG_QP_LFPS_SLCOUT_SEL, (reg32))
#define RG_QP_RX_DAC_EN_GET_RG_QP_LFPS_CMPOUT_SEL(reg32)       REG_FLD_GET(RG_QP_RX_DAC_EN_FLD_RG_QP_LFPS_CMPOUT_SEL, (reg32))
#define RG_QP_RX_DAC_EN_GET_RG_QP_LFPS_LPF_AUX(reg32)          REG_FLD_GET(RG_QP_RX_DAC_EN_FLD_RG_QP_LFPS_LPF_AUX, (reg32))
#define RG_QP_RX_DAC_EN_GET_RG_QP_SIGDET_HF(reg32)             REG_FLD_GET(RG_QP_RX_DAC_EN_FLD_RG_QP_SIGDET_HF, (reg32))
#define RG_QP_RX_DAC_EN_GET_RG_QP_SIGDET_LPF(reg32)            REG_FLD_GET(RG_QP_RX_DAC_EN_FLD_RG_QP_SIGDET_LPF, (reg32))
#define RG_QP_RX_DAC_EN_GET_RG_QP_SIGDET_VTH(reg32)            REG_FLD_GET(RG_QP_RX_DAC_EN_FLD_RG_QP_SIGDET_VTH, (reg32))
#define RG_QP_RX_DAC_EN_GET_RG_QP_RX_50_LOWER(reg32)           REG_FLD_GET(RG_QP_RX_DAC_EN_FLD_RG_QP_RX_50_LOWER, (reg32))
#define RG_QP_RX_DAC_EN_GET_RG_QP_RX_T2R_EN(reg32)             REG_FLD_GET(RG_QP_RX_DAC_EN_FLD_RG_QP_RX_T2R_EN, (reg32))
#define RG_QP_RX_DAC_EN_GET_RG_QP_RX_DAC_MUX(reg32)            REG_FLD_GET(RG_QP_RX_DAC_EN_FLD_RG_QP_RX_DAC_MUX, (reg32))
#define RG_QP_RX_DAC_EN_GET_RG_QP_RX_DAC_PWD(reg32)            REG_FLD_GET(RG_QP_RX_DAC_EN_FLD_RG_QP_RX_DAC_PWD, (reg32))
#define RG_QP_RX_DAC_EN_GET_RG_QP_RX_DAC_EN(reg32)             REG_FLD_GET(RG_QP_RX_DAC_EN_FLD_RG_QP_RX_DAC_EN, (reg32))

#define RG_QP_RXAFE_RESERVE_GET_RG_QP_CDR_PD_10B_EN(reg32)     REG_FLD_GET(RG_QP_RXAFE_RESERVE_FLD_RG_QP_CDR_PD_10B_EN, (reg32))
#define RG_QP_RXAFE_RESERVE_GET_RG_QP_CDR_PD_EDGE_DIS(reg32)   REG_FLD_GET(RG_QP_RXAFE_RESERVE_FLD_RG_QP_CDR_PD_EDGE_DIS, (reg32))
#define RG_QP_RXAFE_RESERVE_GET_RG_QP_RX_VCMHPFSEL(reg32)      REG_FLD_GET(RG_QP_RXAFE_RESERVE_FLD_RG_QP_RX_VCMHPFSEL, (reg32))
#define RG_QP_RXAFE_RESERVE_GET_RG_QP_RX_DAC_MEAS_EN(reg32)    REG_FLD_GET(RG_QP_RXAFE_RESERVE_FLD_RG_QP_RX_DAC_MEAS_EN, (reg32))
#define RG_QP_RXAFE_RESERVE_GET_RG_QP_RXAFE_RESERVE(reg32)     REG_FLD_GET(RG_QP_RXAFE_RESERVE_FLD_RG_QP_RXAFE_RESERVE, (reg32))

#define RG_QP_CDR_LPF_BOT_LIM_GET_RG_QP_CDR_LPF_MJV_EN(reg32)  REG_FLD_GET(RG_QP_CDR_LPF_BOT_LIM_FLD_RG_QP_CDR_LPF_MJV_EN, (reg32))
#define RG_QP_CDR_LPF_BOT_LIM_GET_RG_QP_CDR_LPF_LIN_LIM(reg32) REG_FLD_GET(RG_QP_CDR_LPF_BOT_LIM_FLD_RG_QP_CDR_LPF_LIN_LIM, (reg32))
#define RG_QP_CDR_LPF_BOT_LIM_GET_RG_QP_CDR_LPF_KP_GAIN(reg32) REG_FLD_GET(RG_QP_CDR_LPF_BOT_LIM_FLD_RG_QP_CDR_LPF_KP_GAIN, (reg32))
#define RG_QP_CDR_LPF_BOT_LIM_GET_RG_QP_CDR_LPF_KI_GAIN(reg32) REG_FLD_GET(RG_QP_CDR_LPF_BOT_LIM_FLD_RG_QP_CDR_LPF_KI_GAIN, (reg32))
#define RG_QP_CDR_LPF_BOT_LIM_GET_RG_QP_CDR_LPF_BOT_LIM(reg32) REG_FLD_GET(RG_QP_CDR_LPF_BOT_LIM_FLD_RG_QP_CDR_LPF_BOT_LIM, (reg32))

#define RG_QP_CDR_LPF_MJV_LIM_GET_RG_QP_CDR_LPF_RATIO(reg32)   REG_FLD_GET(RG_QP_CDR_LPF_MJV_LIM_FLD_RG_QP_CDR_LPF_RATIO, (reg32))
#define RG_QP_CDR_LPF_MJV_LIM_GET_RG_QP_CDR_LPF_MJV_LIM(reg32) REG_FLD_GET(RG_QP_CDR_LPF_MJV_LIM_FLD_RG_QP_CDR_LPF_MJV_LIM, (reg32))

#define RG_QP_CDR_LPF_TOP_LIM_GET_RG_QP_CDR_LPF_ONESHOT_OUT_SEL(reg32) REG_FLD_GET(RG_QP_CDR_LPF_TOP_LIM_FLD_RG_QP_CDR_LPF_ONESHOT_OUT_SEL, (reg32))
#define RG_QP_CDR_LPF_TOP_LIM_GET_RG_QP_CDR_LPF_SET(reg32)     REG_FLD_GET(RG_QP_CDR_LPF_TOP_LIM_FLD_RG_QP_CDR_LPF_SET, (reg32))
#define RG_QP_CDR_LPF_TOP_LIM_GET_RG_QP_CDR_LPF_SNAPSHOT(reg32) REG_FLD_GET(RG_QP_CDR_LPF_TOP_LIM_FLD_RG_QP_CDR_LPF_SNAPSHOT, (reg32))
#define RG_QP_CDR_LPF_TOP_LIM_GET_RG_QP_CDR_LPF_TOP_LIM(reg32) REG_FLD_GET(RG_QP_CDR_LPF_TOP_LIM_FLD_RG_QP_CDR_LPF_TOP_LIM, (reg32))

#define RG_QP_CDR_LPF_SETVALUE_GET_RG_QP_CDR_PR_BUF_IN_SR(reg32) REG_FLD_GET(RG_QP_CDR_LPF_SETVALUE_FLD_RG_QP_CDR_PR_BUF_IN_SR, (reg32))
#define RG_QP_CDR_LPF_SETVALUE_GET_RG_QP_CDR_PR_BETA_SEL(reg32) REG_FLD_GET(RG_QP_CDR_LPF_SETVALUE_FLD_RG_QP_CDR_PR_BETA_SEL, (reg32))
#define RG_QP_CDR_LPF_SETVALUE_GET_RG_QP_CDR_LPF_UD_GATING(reg32) REG_FLD_GET(RG_QP_CDR_LPF_SETVALUE_FLD_RG_QP_CDR_LPF_UD_GATING, (reg32))
#define RG_QP_CDR_LPF_SETVALUE_GET_RG_QP_CDR_LPF_PISTEP_SEL(reg32) REG_FLD_GET(RG_QP_CDR_LPF_SETVALUE_FLD_RG_QP_CDR_LPF_PISTEP_SEL, (reg32))
#define RG_QP_CDR_LPF_SETVALUE_GET_RG_QP_CDR_LPF_PISTEP_ONESHOT(reg32) REG_FLD_GET(RG_QP_CDR_LPF_SETVALUE_FLD_RG_QP_CDR_LPF_PISTEP_ONESHOT, (reg32))
#define RG_QP_CDR_LPF_SETVALUE_GET_RG_QP_CDR_LPF_ONESHOT_STEP(reg32) REG_FLD_GET(RG_QP_CDR_LPF_SETVALUE_FLD_RG_QP_CDR_LPF_ONESHOT_STEP, (reg32))
#define RG_QP_CDR_LPF_SETVALUE_GET_RG_QP_CDR_LPF_SETVALUE(reg32) REG_FLD_GET(RG_QP_CDR_LPF_SETVALUE_FLD_RG_QP_CDR_LPF_SETVALUE, (reg32))

#define RG_QP_CDR_PR_CKREF_DIV1_GET_RG_QP_CDR_PR_KBAND_DIV(reg32) REG_FLD_GET(RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_KBAND_DIV, (reg32))
#define RG_QP_CDR_PR_CKREF_DIV1_GET_RG_QP_CDR_PR_INJ_FORCE_ON(reg32) REG_FLD_GET(RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_INJ_FORCE_ON, (reg32))
#define RG_QP_CDR_PR_CKREF_DIV1_GET_RG_QP_CDR_PR_INJ_FORCE_OFF(reg32) REG_FLD_GET(RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_INJ_FORCE_OFF, (reg32))
#define RG_QP_CDR_PR_CKREF_DIV1_GET_RG_QP_CDR_PR_DCMON_SEL(reg32) REG_FLD_GET(RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_DCMON_SEL, (reg32))
#define RG_QP_CDR_PR_CKREF_DIV1_GET_RG_QP_CDR_PR_DCMON_EN(reg32) REG_FLD_GET(RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_DCMON_EN, (reg32))
#define RG_QP_CDR_PR_CKREF_DIV1_GET_RG_QP_CDR_PR_DAC_BAND(reg32) REG_FLD_GET(RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_DAC_BAND, (reg32))
#define RG_QP_CDR_PR_CKREF_DIV1_GET_RG_QP_CDR_PR_COR_HBW_EN(reg32) REG_FLD_GET(RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_COR_HBW_EN, (reg32))
#define RG_QP_CDR_PR_CKREF_DIV1_GET_RG_QP_CDR_PR_CORSIG_OPT(reg32) REG_FLD_GET(RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_CORSIG_OPT, (reg32))
#define RG_QP_CDR_PR_CKREF_DIV1_GET_RG_QP_CDR_PR_CKREF_DIV(reg32) REG_FLD_GET(RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_CKREF_DIV, (reg32))
#define RG_QP_CDR_PR_CKREF_DIV1_GET_RG_QP_CDR_PR_CKREF_DIV1(reg32) REG_FLD_GET(RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_CKREF_DIV1, (reg32))

#define RG_QP_CDR_PR_KBAND_DIV_PCIE_GET_RG_QP_CDR_FORCE_IBANDLPF_C_OFF(reg32) REG_FLD_GET(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_FORCE_IBANDLPF_C_OFF, (reg32))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_GET_RG_QP_CDR_PR_XFICK_EN(reg32) REG_FLD_GET(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_XFICK_EN, (reg32))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_GET_RG_QP_CDR_PR_VREG_CKBUF_VAL(reg32) REG_FLD_GET(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_VREG_CKBUF_VAL, (reg32))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_GET_RG_QP_CDR_PR_VCOADC_OS(reg32) REG_FLD_GET(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_VCOADC_OS, (reg32))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_GET_RG_QP_CDR_PR_TDC_REF_SEL(reg32) REG_FLD_GET(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_TDC_REF_SEL, (reg32))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_GET_RG_QP_CDR_PR_RST_DLY(reg32) REG_FLD_GET(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_RST_DLY, (reg32))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_GET_RG_QP_CDR_PR_RSTB_BYPASS(reg32) REG_FLD_GET(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_RSTB_BYPASS, (reg32))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_GET_RG_QP_CDR_PR_MONPR_EN(reg32) REG_FLD_GET(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_MONPR_EN, (reg32))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_GET_RG_QP_CDR_PR_MONPI_EN(reg32) REG_FLD_GET(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_MONPI_EN, (reg32))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_GET_RG_QP_CDR_PR_MONCK_MUX(reg32) REG_FLD_GET(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_MONCK_MUX, (reg32))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_GET_RG_QP_CDR_PR_MONCK_EN(reg32) REG_FLD_GET(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_MONCK_EN, (reg32))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_GET_RG_QP_CDR_PR_LDO_FORCE_ON(reg32) REG_FLD_GET(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_LDO_FORCE_ON, (reg32))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_GET_RG_QP_CDR_PR_KBAND_PCIE_MODE(reg32) REG_FLD_GET(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_KBAND_PCIE_MODE, (reg32))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_GET_RG_QP_CDR_PR_KBAND_DIV_PCIE(reg32) REG_FLD_GET(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_KBAND_DIV_PCIE, (reg32))

#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_GET_RG_QP_RX_D0_LL_RESERVED(reg32) REG_FLD_GET(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_RX_D0_LL_RESERVED, (reg32))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_GET_RG_QP_CDR_REFCK_DIV2_EN(reg32) REG_FLD_GET(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_REFCK_DIV2_EN, (reg32))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_GET_RG_QP_RX_MPX_SEL(reg32) REG_FLD_GET(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_RX_MPX_SEL, (reg32))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_GET_RG_QP_CDR_PHYCK_SEL(reg32) REG_FLD_GET(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PHYCK_SEL, (reg32))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_GET_RG_QP_CDR_PHYCK_RSTB(reg32) REG_FLD_GET(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PHYCK_RSTB, (reg32))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_GET_RG_QP_CDR_PHYCK_DIV(reg32) REG_FLD_GET(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PHYCK_DIV, (reg32))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_GET_RG_QP_CDR_PI_CK_INV(reg32) REG_FLD_GET(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PI_CK_INV, (reg32))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_GET_RG_QP_CDR_PIEYE_XOR_EN(reg32) REG_FLD_GET(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PIEYE_XOR_EN, (reg32))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_GET_RG_QP_CDR_PIEYEBD4_SEL(reg32) REG_FLD_GET(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PIEYEBD4_SEL, (reg32))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_GET_RG_QP_CDR_PICAL_SEL(reg32) REG_FLD_GET(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PICAL_SEL, (reg32))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_GET_RG_QP_CDR_PICAL_INV(reg32) REG_FLD_GET(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PICAL_INV, (reg32))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_GET_RG_QP_CDR_FORCE_IBANDLPF_R_OFF(reg32) REG_FLD_GET(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_FORCE_IBANDLPF_R_OFF, (reg32))

#define RG_QP_RX_D0_HS_RESERVED_GET_RG_QP_RX_D1_HS_RESERVED(reg32) REG_FLD_GET(RG_QP_RX_D0_HS_RESERVED_FLD_RG_QP_RX_D1_HS_RESERVED, (reg32))
#define RG_QP_RX_D0_HS_RESERVED_GET_RG_QP_RX_D0_HS_RESERVED(reg32) REG_FLD_GET(RG_QP_RX_D0_HS_RESERVED_FLD_RG_QP_RX_D0_HS_RESERVED, (reg32))

#define RG_QP_TX_MODE_16B_EN_GET_RG_QP_TX_RESERVE(reg32)       REG_FLD_GET(RG_QP_TX_MODE_16B_EN_FLD_RG_QP_TX_RESERVE, (reg32))
#define RG_QP_TX_MODE_16B_EN_GET_RG_QP_TX_CKMON_SEL(reg32)     REG_FLD_GET(RG_QP_TX_MODE_16B_EN_FLD_RG_QP_TX_CKMON_SEL, (reg32))
#define RG_QP_TX_MODE_16B_EN_GET_RG_QP_TX_CKMON_EN(reg32)      REG_FLD_GET(RG_QP_TX_MODE_16B_EN_FLD_RG_QP_TX_CKMON_EN, (reg32))
#define RG_QP_TX_MODE_16B_EN_GET_RG_QP_TX_VLMON_SEL(reg32)     REG_FLD_GET(RG_QP_TX_MODE_16B_EN_FLD_RG_QP_TX_VLMON_SEL, (reg32))
#define RG_QP_TX_MODE_16B_EN_GET_RG_QP_TX_VLMON_EN(reg32)      REG_FLD_GET(RG_QP_TX_MODE_16B_EN_FLD_RG_QP_TX_VLMON_EN, (reg32))
#define RG_QP_TX_MODE_16B_EN_GET_RG_QP_TXLBRX_EN(reg32)        REG_FLD_GET(RG_QP_TX_MODE_16B_EN_FLD_RG_QP_TXLBRX_EN, (reg32))
#define RG_QP_TX_MODE_16B_EN_GET_RG_QP_TX_MODE_16B_EN(reg32)   REG_FLD_GET(RG_QP_TX_MODE_16B_EN_FLD_RG_QP_TX_MODE_16B_EN, (reg32))

#define RG_QP_RXLBTX_EN_GET_RG_QP_TX_DMEDGEGEN_EN(reg32)       REG_FLD_GET(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_DMEDGEGEN_EN, (reg32))
#define RG_QP_RXLBTX_EN_GET_RG_QP_TX_AUTOZERO_EN(reg32)        REG_FLD_GET(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_AUTOZERO_EN, (reg32))
#define RG_QP_RXLBTX_EN_GET_RG_QP_TX_RXDET_METHOD(reg32)       REG_FLD_GET(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_RXDET_METHOD, (reg32))
#define RG_QP_RXLBTX_EN_GET_RG_QP_TX_TERMCAL_SELPN(reg32)      REG_FLD_GET(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_TERMCAL_SELPN, (reg32))
#define RG_QP_RXLBTX_EN_GET_RG_QP_TX_TERMCAL_VREF_L(reg32)     REG_FLD_GET(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_TERMCAL_VREF_L, (reg32))
#define RG_QP_RXLBTX_EN_GET_RG_QP_TX_TERMCAL_VREF_H(reg32)     REG_FLD_GET(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_TERMCAL_VREF_H, (reg32))
#define RG_QP_RXLBTX_EN_GET_RG_QP_TX_INT_EN(reg32)             REG_FLD_GET(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_INT_EN, (reg32))
#define RG_QP_RXLBTX_EN_GET_RG_QP_TX_SR_REDUCTION(reg32)       REG_FLD_GET(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_SR_REDUCTION, (reg32))
#define RG_QP_RXLBTX_EN_GET_RG_QP_TX_CHGPLR_C2(reg32)          REG_FLD_GET(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_CHGPLR_C2, (reg32))
#define RG_QP_RXLBTX_EN_GET_RG_QP_TX_CHGPLR_C1(reg32)          REG_FLD_GET(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_CHGPLR_C1, (reg32))
#define RG_QP_RXLBTX_EN_GET_RG_QP_TX_CHGPLR_CN1(reg32)         REG_FLD_GET(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_CHGPLR_CN1, (reg32))
#define RG_QP_RXLBTX_EN_GET_RG_QP_TX250MCK_INVB(reg32)         REG_FLD_GET(RG_QP_RXLBTX_EN_FLD_RG_QP_TX250MCK_INVB, (reg32))
#define RG_QP_RXLBTX_EN_GET_RG_QP_RXLBTX_EN(reg32)             REG_FLD_GET(RG_QP_RXLBTX_EN_FLD_RG_QP_RXLBTX_EN, (reg32))

#define RG_QP_BGR_EN_GET_RG_QP_BG_MONEN(reg32)                 REG_FLD_GET(RG_QP_BGR_EN_FLD_RG_QP_BG_MONEN, (reg32))
#define RG_QP_BGR_EN_GET_RG_QP_BIAS_V2V_CAL(reg32)             REG_FLD_GET(RG_QP_BGR_EN_FLD_RG_QP_BIAS_V2V_CAL, (reg32))
#define RG_QP_BGR_EN_GET_RG_QP_VRT_VREF_SEL(reg32)             REG_FLD_GET(RG_QP_BGR_EN_FLD_RG_QP_VRT_VREF_SEL, (reg32))
#define RG_QP_BGR_EN_GET_RG_QP_MPX_SEL(reg32)                  REG_FLD_GET(RG_QP_BGR_EN_FLD_RG_QP_MPX_SEL, (reg32))
#define RG_QP_BGR_EN_GET_RG_QP_MPX_EN(reg32)                   REG_FLD_GET(RG_QP_BGR_EN_FLD_RG_QP_MPX_EN, (reg32))
#define RG_QP_BGR_EN_GET_RG_QP_BG_DIV(reg32)                   REG_FLD_GET(RG_QP_BGR_EN_FLD_RG_QP_BG_DIV, (reg32))
#define RG_QP_BGR_EN_GET_RG_QP_CHPEN(reg32)                    REG_FLD_GET(RG_QP_BGR_EN_FLD_RG_QP_CHPEN, (reg32))
#define RG_QP_BGR_EN_GET_RG_QP_BGR_EN(reg32)                   REG_FLD_GET(RG_QP_BGR_EN_FLD_RG_QP_BGR_EN, (reg32))

#define RG_PCIE_CLKDRV_IMPSEL_GET_RG_QP_TDC_AUTOEN(reg32)      REG_FLD_GET(RG_PCIE_CLKDRV_IMPSEL_FLD_RG_QP_TDC_AUTOEN, (reg32))
#define RG_PCIE_CLKDRV_IMPSEL_GET_RG_PCIE_CLKDET_VTH(reg32)    REG_FLD_GET(RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDET_VTH, (reg32))
#define RG_PCIE_CLKDRV_IMPSEL_GET_RG_PCIE_CLKDRV_AMP(reg32)    REG_FLD_GET(RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_AMP, (reg32))
#define RG_PCIE_CLKDRV_IMPSEL_GET_RG_PCIE_CLKDRV_FORCEIN(reg32) REG_FLD_GET(RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_FORCEIN, (reg32))
#define RG_PCIE_CLKDRV_IMPSEL_GET_RG_PCIE_CLKDRV_DUTY(reg32)   REG_FLD_GET(RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_DUTY, (reg32))
#define RG_PCIE_CLKDRV_IMPSEL_GET_RG_PCIE_CLKDRV_SLEW(reg32)   REG_FLD_GET(RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_SLEW, (reg32))
#define RG_PCIE_CLKDRV_IMPSEL_GET_RG_PCIE_CLKDRV_OFFSET(reg32) REG_FLD_GET(RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_OFFSET, (reg32))
#define RG_PCIE_CLKDRV_IMPSEL_GET_RG_PCIE_CLKDRV_HZ(reg32)     REG_FLD_GET(RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_HZ, (reg32))
#define RG_PCIE_CLKDRV_IMPSEL_GET_RG_PCIE_CLKDRV_RP(reg32)     REG_FLD_GET(RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_RP, (reg32))
#define RG_PCIE_CLKDRV_IMPSEL_GET_RG_PCIE_CLKDRV_IMPSEL(reg32) REG_FLD_GET(RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_IMPSEL, (reg32))

#define RG_QP_TDC_FT_CK_EN_GET_RG_QP_PLL_IBAND(reg32)          REG_FLD_GET(RG_QP_TDC_FT_CK_EN_FLD_RG_QP_PLL_IBAND, (reg32))
#define RG_QP_TDC_FT_CK_EN_GET_RG_QP_PLL_DEBUG_SEL(reg32)      REG_FLD_GET(RG_QP_TDC_FT_CK_EN_FLD_RG_QP_PLL_DEBUG_SEL, (reg32))
#define RG_QP_TDC_FT_CK_EN_GET_RG_QP_PLL_RST_DLY(reg32)        REG_FLD_GET(RG_QP_TDC_FT_CK_EN_FLD_RG_QP_PLL_RST_DLY, (reg32))
#define RG_QP_TDC_FT_CK_EN_GET_RG_QP_XTAL_TOP_RESERVE0(reg32)  REG_FLD_GET(RG_QP_TDC_FT_CK_EN_FLD_RG_QP_XTAL_TOP_RESERVE0, (reg32))
#define RG_QP_TDC_FT_CK_EN_GET_RG_VUSB10_ON(reg32)             REG_FLD_GET(RG_QP_TDC_FT_CK_EN_FLD_RG_VUSB10_ON, (reg32))
#define RG_QP_TDC_FT_CK_EN_GET_RG_QP_PLL_MONCK_SEL(reg32)      REG_FLD_GET(RG_QP_TDC_FT_CK_EN_FLD_RG_QP_PLL_MONCK_SEL, (reg32))
#define RG_QP_TDC_FT_CK_EN_GET_RG_QP_TDC_MON_CK_EN(reg32)      REG_FLD_GET(RG_QP_TDC_FT_CK_EN_FLD_RG_QP_TDC_MON_CK_EN, (reg32))
#define RG_QP_TDC_FT_CK_EN_GET_RG_QP_TDC_FT_CK_EN(reg32)       REG_FLD_GET(RG_QP_TDC_FT_CK_EN_FLD_RG_QP_TDC_FT_CK_EN, (reg32))

#define RG_QP_PLL_IPLL_DIG_PWR_SEL_GET_RG_QP_PLL_SDM_DI_LS(reg32) REG_FLD_GET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_SDM_DI_LS, (reg32))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_GET_RG_QP_PLL_TCL_EN(reg32) REG_FLD_GET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_TCL_EN, (reg32))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_GET_RG_QP_PLL_RLP_SEL(reg32) REG_FLD_GET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_RLP_SEL, (reg32))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_GET_RG_QP_PLL_PREDIV(reg32) REG_FLD_GET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_PREDIV, (reg32))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_GET_RG_QP_PLL_POSTDIV(reg32) REG_FLD_GET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_POSTDIV, (reg32))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_GET_RG_QP_PLL_OSCAL_ENB(reg32) REG_FLD_GET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_OSCAL_ENB, (reg32))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_GET_RG_QP_PLL_MON_LDO_SEL(reg32) REG_FLD_GET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_MON_LDO_SEL, (reg32))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_GET_RG_QP_PLL_MONVC_EN(reg32) REG_FLD_GET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_MONVC_EN, (reg32))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_GET_RG_QP_PLL_MONREF_EN(reg32) REG_FLD_GET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_MONREF_EN, (reg32))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_GET_RG_QP_PLL_MONCK_EN(reg32) REG_FLD_GET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_MONCK_EN, (reg32))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_GET_RG_QP_PLL_MONCK_DIV4_EN(reg32) REG_FLD_GET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_MONCK_DIV4_EN, (reg32))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_GET_RG_QP_PLL_LDOVCO_VSEL(reg32) REG_FLD_GET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_LDOVCO_VSEL, (reg32))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_GET_RG_QP_PLL_LDOPFD_VSEL(reg32) REG_FLD_GET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_LDOPFD_VSEL, (reg32))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_GET_RG_QP_PLL_LDOLPF_VSEL(reg32) REG_FLD_GET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_LDOLPF_VSEL, (reg32))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_GET_RG_QP_PLL_LOAD_EN(reg32) REG_FLD_GET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_LOAD_EN, (reg32))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_GET_RG_QP_PLL_KBAND_MEAS_EN(reg32) REG_FLD_GET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_KBAND_MEAS_EN, (reg32))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_GET_RG_QP_PLL_KBAND_KFC(reg32) REG_FLD_GET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_KBAND_KFC, (reg32))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_GET_RG_QP_PLL_IPLL_DIG_PWR_SEL(reg32) REG_FLD_GET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_IPLL_DIG_PWR_SEL, (reg32))

#define RG_QP_PLL_SDM_ORD_GET_RG_QP_PLL_FREQ_MEAS_EN(reg32)    REG_FLD_GET(RG_QP_PLL_SDM_ORD_FLD_RG_QP_PLL_FREQ_MEAS_EN, (reg32))
#define RG_QP_PLL_SDM_ORD_GET_RG_QP_PLL_POST_MONCK_SEL(reg32)  REG_FLD_GET(RG_QP_PLL_SDM_ORD_FLD_RG_QP_PLL_POST_MONCK_SEL, (reg32))
#define RG_QP_PLL_SDM_ORD_GET_RG_QP_PLL_POST_MONCK_EN(reg32)   REG_FLD_GET(RG_QP_PLL_SDM_ORD_FLD_RG_QP_PLL_POST_MONCK_EN, (reg32))
#define RG_QP_PLL_SDM_ORD_GET_RG_QP_PLL_SSC_TRI_EN(reg32)      REG_FLD_GET(RG_QP_PLL_SDM_ORD_FLD_RG_QP_PLL_SSC_TRI_EN, (reg32))
#define RG_QP_PLL_SDM_ORD_GET_RG_QP_PLL_SSC_PHASE_INI(reg32)   REG_FLD_GET(RG_QP_PLL_SDM_ORD_FLD_RG_QP_PLL_SSC_PHASE_INI, (reg32))
#define RG_QP_PLL_SDM_ORD_GET_RG_QP_PLL_SDM_OUT(reg32)         REG_FLD_GET(RG_QP_PLL_SDM_ORD_FLD_RG_QP_PLL_SDM_OUT, (reg32))
#define RG_QP_PLL_SDM_ORD_GET_RG_QP_PLL_SDM_ORD(reg32)         REG_FLD_GET(RG_QP_PLL_SDM_ORD_FLD_RG_QP_PLL_SDM_ORD, (reg32))

#define RG_QP_RX_DAC_EN_SET_RG_QP_RXAFE_DCMON_SEL(reg32, val)  REG_FLD_SET(RG_QP_RX_DAC_EN_FLD_RG_QP_RXAFE_DCMON_SEL, (reg32), (val))
#define RG_QP_RX_DAC_EN_SET_RG_QP_LFPS_MON_EN(reg32, val)      REG_FLD_SET(RG_QP_RX_DAC_EN_FLD_RG_QP_LFPS_MON_EN, (reg32), (val))
#define RG_QP_RX_DAC_EN_SET_RG_QP_LFPS_LPF_I_SEL(reg32, val)   REG_FLD_SET(RG_QP_RX_DAC_EN_FLD_RG_QP_LFPS_LPF_I_SEL, (reg32), (val))
#define RG_QP_RX_DAC_EN_SET_RG_QP_LFPS_LPF_I(reg32, val)       REG_FLD_SET(RG_QP_RX_DAC_EN_FLD_RG_QP_LFPS_LPF_I, (reg32), (val))
#define RG_QP_RX_DAC_EN_SET_RG_QP_LFPS_LPF(reg32, val)         REG_FLD_SET(RG_QP_RX_DAC_EN_FLD_RG_QP_LFPS_LPF, (reg32), (val))
#define RG_QP_RX_DAC_EN_SET_RG_QP_LFPS_SLCOUT_SEL(reg32, val)  REG_FLD_SET(RG_QP_RX_DAC_EN_FLD_RG_QP_LFPS_SLCOUT_SEL, (reg32), (val))
#define RG_QP_RX_DAC_EN_SET_RG_QP_LFPS_CMPOUT_SEL(reg32, val)  REG_FLD_SET(RG_QP_RX_DAC_EN_FLD_RG_QP_LFPS_CMPOUT_SEL, (reg32), (val))
#define RG_QP_RX_DAC_EN_SET_RG_QP_LFPS_LPF_AUX(reg32, val)     REG_FLD_SET(RG_QP_RX_DAC_EN_FLD_RG_QP_LFPS_LPF_AUX, (reg32), (val))
#define RG_QP_RX_DAC_EN_SET_RG_QP_SIGDET_HF(reg32, val)        REG_FLD_SET(RG_QP_RX_DAC_EN_FLD_RG_QP_SIGDET_HF, (reg32), (val))
#define RG_QP_RX_DAC_EN_SET_RG_QP_SIGDET_LPF(reg32, val)       REG_FLD_SET(RG_QP_RX_DAC_EN_FLD_RG_QP_SIGDET_LPF, (reg32), (val))
#define RG_QP_RX_DAC_EN_SET_RG_QP_SIGDET_VTH(reg32, val)       REG_FLD_SET(RG_QP_RX_DAC_EN_FLD_RG_QP_SIGDET_VTH, (reg32), (val))
#define RG_QP_RX_DAC_EN_SET_RG_QP_RX_50_LOWER(reg32, val)      REG_FLD_SET(RG_QP_RX_DAC_EN_FLD_RG_QP_RX_50_LOWER, (reg32), (val))
#define RG_QP_RX_DAC_EN_SET_RG_QP_RX_T2R_EN(reg32, val)        REG_FLD_SET(RG_QP_RX_DAC_EN_FLD_RG_QP_RX_T2R_EN, (reg32), (val))
#define RG_QP_RX_DAC_EN_SET_RG_QP_RX_DAC_MUX(reg32, val)       REG_FLD_SET(RG_QP_RX_DAC_EN_FLD_RG_QP_RX_DAC_MUX, (reg32), (val))
#define RG_QP_RX_DAC_EN_SET_RG_QP_RX_DAC_PWD(reg32, val)       REG_FLD_SET(RG_QP_RX_DAC_EN_FLD_RG_QP_RX_DAC_PWD, (reg32), (val))
#define RG_QP_RX_DAC_EN_SET_RG_QP_RX_DAC_EN(reg32, val)        REG_FLD_SET(RG_QP_RX_DAC_EN_FLD_RG_QP_RX_DAC_EN, (reg32), (val))

#define RG_QP_RXAFE_RESERVE_SET_RG_QP_CDR_PD_10B_EN(reg32, val) REG_FLD_SET(RG_QP_RXAFE_RESERVE_FLD_RG_QP_CDR_PD_10B_EN, (reg32), (val))
#define RG_QP_RXAFE_RESERVE_SET_RG_QP_CDR_PD_EDGE_DIS(reg32, val) REG_FLD_SET(RG_QP_RXAFE_RESERVE_FLD_RG_QP_CDR_PD_EDGE_DIS, (reg32), (val))
#define RG_QP_RXAFE_RESERVE_SET_RG_QP_RX_VCMHPFSEL(reg32, val) REG_FLD_SET(RG_QP_RXAFE_RESERVE_FLD_RG_QP_RX_VCMHPFSEL, (reg32), (val))
#define RG_QP_RXAFE_RESERVE_SET_RG_QP_RX_DAC_MEAS_EN(reg32, val) REG_FLD_SET(RG_QP_RXAFE_RESERVE_FLD_RG_QP_RX_DAC_MEAS_EN, (reg32), (val))
#define RG_QP_RXAFE_RESERVE_SET_RG_QP_RXAFE_RESERVE(reg32, val) REG_FLD_SET(RG_QP_RXAFE_RESERVE_FLD_RG_QP_RXAFE_RESERVE, (reg32), (val))

#define RG_QP_CDR_LPF_BOT_LIM_SET_RG_QP_CDR_LPF_MJV_EN(reg32, val) REG_FLD_SET(RG_QP_CDR_LPF_BOT_LIM_FLD_RG_QP_CDR_LPF_MJV_EN, (reg32), (val))
#define RG_QP_CDR_LPF_BOT_LIM_SET_RG_QP_CDR_LPF_LIN_LIM(reg32, val) REG_FLD_SET(RG_QP_CDR_LPF_BOT_LIM_FLD_RG_QP_CDR_LPF_LIN_LIM, (reg32), (val))
#define RG_QP_CDR_LPF_BOT_LIM_SET_RG_QP_CDR_LPF_KP_GAIN(reg32, val) REG_FLD_SET(RG_QP_CDR_LPF_BOT_LIM_FLD_RG_QP_CDR_LPF_KP_GAIN, (reg32), (val))
#define RG_QP_CDR_LPF_BOT_LIM_SET_RG_QP_CDR_LPF_KI_GAIN(reg32, val) REG_FLD_SET(RG_QP_CDR_LPF_BOT_LIM_FLD_RG_QP_CDR_LPF_KI_GAIN, (reg32), (val))
#define RG_QP_CDR_LPF_BOT_LIM_SET_RG_QP_CDR_LPF_BOT_LIM(reg32, val) REG_FLD_SET(RG_QP_CDR_LPF_BOT_LIM_FLD_RG_QP_CDR_LPF_BOT_LIM, (reg32), (val))

#define RG_QP_CDR_LPF_MJV_LIM_SET_RG_QP_CDR_LPF_RATIO(reg32, val) REG_FLD_SET(RG_QP_CDR_LPF_MJV_LIM_FLD_RG_QP_CDR_LPF_RATIO, (reg32), (val))
#define RG_QP_CDR_LPF_MJV_LIM_SET_RG_QP_CDR_LPF_MJV_LIM(reg32, val) REG_FLD_SET(RG_QP_CDR_LPF_MJV_LIM_FLD_RG_QP_CDR_LPF_MJV_LIM, (reg32), (val))

#define RG_QP_CDR_LPF_TOP_LIM_SET_RG_QP_CDR_LPF_ONESHOT_OUT_SEL(reg32, val) REG_FLD_SET(RG_QP_CDR_LPF_TOP_LIM_FLD_RG_QP_CDR_LPF_ONESHOT_OUT_SEL, (reg32), (val))
#define RG_QP_CDR_LPF_TOP_LIM_SET_RG_QP_CDR_LPF_SET(reg32, val) REG_FLD_SET(RG_QP_CDR_LPF_TOP_LIM_FLD_RG_QP_CDR_LPF_SET, (reg32), (val))
#define RG_QP_CDR_LPF_TOP_LIM_SET_RG_QP_CDR_LPF_SNAPSHOT(reg32, val) REG_FLD_SET(RG_QP_CDR_LPF_TOP_LIM_FLD_RG_QP_CDR_LPF_SNAPSHOT, (reg32), (val))
#define RG_QP_CDR_LPF_TOP_LIM_SET_RG_QP_CDR_LPF_TOP_LIM(reg32, val) REG_FLD_SET(RG_QP_CDR_LPF_TOP_LIM_FLD_RG_QP_CDR_LPF_TOP_LIM, (reg32), (val))

#define RG_QP_CDR_LPF_SETVALUE_SET_RG_QP_CDR_PR_BUF_IN_SR(reg32, val) REG_FLD_SET(RG_QP_CDR_LPF_SETVALUE_FLD_RG_QP_CDR_PR_BUF_IN_SR, (reg32), (val))
#define RG_QP_CDR_LPF_SETVALUE_SET_RG_QP_CDR_PR_BETA_SEL(reg32, val) REG_FLD_SET(RG_QP_CDR_LPF_SETVALUE_FLD_RG_QP_CDR_PR_BETA_SEL, (reg32), (val))
#define RG_QP_CDR_LPF_SETVALUE_SET_RG_QP_CDR_LPF_UD_GATING(reg32, val) REG_FLD_SET(RG_QP_CDR_LPF_SETVALUE_FLD_RG_QP_CDR_LPF_UD_GATING, (reg32), (val))
#define RG_QP_CDR_LPF_SETVALUE_SET_RG_QP_CDR_LPF_PISTEP_SEL(reg32, val) REG_FLD_SET(RG_QP_CDR_LPF_SETVALUE_FLD_RG_QP_CDR_LPF_PISTEP_SEL, (reg32), (val))
#define RG_QP_CDR_LPF_SETVALUE_SET_RG_QP_CDR_LPF_PISTEP_ONESHOT(reg32, val) REG_FLD_SET(RG_QP_CDR_LPF_SETVALUE_FLD_RG_QP_CDR_LPF_PISTEP_ONESHOT, (reg32), (val))
#define RG_QP_CDR_LPF_SETVALUE_SET_RG_QP_CDR_LPF_ONESHOT_STEP(reg32, val) REG_FLD_SET(RG_QP_CDR_LPF_SETVALUE_FLD_RG_QP_CDR_LPF_ONESHOT_STEP, (reg32), (val))
#define RG_QP_CDR_LPF_SETVALUE_SET_RG_QP_CDR_LPF_SETVALUE(reg32, val) REG_FLD_SET(RG_QP_CDR_LPF_SETVALUE_FLD_RG_QP_CDR_LPF_SETVALUE, (reg32), (val))

#define RG_QP_CDR_PR_CKREF_DIV1_SET_RG_QP_CDR_PR_KBAND_DIV(reg32, val) REG_FLD_SET(RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_KBAND_DIV, (reg32), (val))
#define RG_QP_CDR_PR_CKREF_DIV1_SET_RG_QP_CDR_PR_INJ_FORCE_ON(reg32, val) REG_FLD_SET(RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_INJ_FORCE_ON, (reg32), (val))
#define RG_QP_CDR_PR_CKREF_DIV1_SET_RG_QP_CDR_PR_INJ_FORCE_OFF(reg32, val) REG_FLD_SET(RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_INJ_FORCE_OFF, (reg32), (val))
#define RG_QP_CDR_PR_CKREF_DIV1_SET_RG_QP_CDR_PR_DCMON_SEL(reg32, val) REG_FLD_SET(RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_DCMON_SEL, (reg32), (val))
#define RG_QP_CDR_PR_CKREF_DIV1_SET_RG_QP_CDR_PR_DCMON_EN(reg32, val) REG_FLD_SET(RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_DCMON_EN, (reg32), (val))
#define RG_QP_CDR_PR_CKREF_DIV1_SET_RG_QP_CDR_PR_DAC_BAND(reg32, val) REG_FLD_SET(RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_DAC_BAND, (reg32), (val))
#define RG_QP_CDR_PR_CKREF_DIV1_SET_RG_QP_CDR_PR_COR_HBW_EN(reg32, val) REG_FLD_SET(RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_COR_HBW_EN, (reg32), (val))
#define RG_QP_CDR_PR_CKREF_DIV1_SET_RG_QP_CDR_PR_CORSIG_OPT(reg32, val) REG_FLD_SET(RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_CORSIG_OPT, (reg32), (val))
#define RG_QP_CDR_PR_CKREF_DIV1_SET_RG_QP_CDR_PR_CKREF_DIV(reg32, val) REG_FLD_SET(RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_CKREF_DIV, (reg32), (val))
#define RG_QP_CDR_PR_CKREF_DIV1_SET_RG_QP_CDR_PR_CKREF_DIV1(reg32, val) REG_FLD_SET(RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_CKREF_DIV1, (reg32), (val))

#define RG_QP_CDR_PR_KBAND_DIV_PCIE_SET_RG_QP_CDR_FORCE_IBANDLPF_C_OFF(reg32, val) REG_FLD_SET(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_FORCE_IBANDLPF_C_OFF, (reg32), (val))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_SET_RG_QP_CDR_PR_XFICK_EN(reg32, val) REG_FLD_SET(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_XFICK_EN, (reg32), (val))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_SET_RG_QP_CDR_PR_VREG_CKBUF_VAL(reg32, val) REG_FLD_SET(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_VREG_CKBUF_VAL, (reg32), (val))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_SET_RG_QP_CDR_PR_VCOADC_OS(reg32, val) REG_FLD_SET(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_VCOADC_OS, (reg32), (val))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_SET_RG_QP_CDR_PR_TDC_REF_SEL(reg32, val) REG_FLD_SET(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_TDC_REF_SEL, (reg32), (val))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_SET_RG_QP_CDR_PR_RST_DLY(reg32, val) REG_FLD_SET(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_RST_DLY, (reg32), (val))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_SET_RG_QP_CDR_PR_RSTB_BYPASS(reg32, val) REG_FLD_SET(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_RSTB_BYPASS, (reg32), (val))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_SET_RG_QP_CDR_PR_MONPR_EN(reg32, val) REG_FLD_SET(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_MONPR_EN, (reg32), (val))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_SET_RG_QP_CDR_PR_MONPI_EN(reg32, val) REG_FLD_SET(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_MONPI_EN, (reg32), (val))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_SET_RG_QP_CDR_PR_MONCK_MUX(reg32, val) REG_FLD_SET(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_MONCK_MUX, (reg32), (val))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_SET_RG_QP_CDR_PR_MONCK_EN(reg32, val) REG_FLD_SET(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_MONCK_EN, (reg32), (val))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_SET_RG_QP_CDR_PR_LDO_FORCE_ON(reg32, val) REG_FLD_SET(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_LDO_FORCE_ON, (reg32), (val))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_SET_RG_QP_CDR_PR_KBAND_PCIE_MODE(reg32, val) REG_FLD_SET(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_KBAND_PCIE_MODE, (reg32), (val))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_SET_RG_QP_CDR_PR_KBAND_DIV_PCIE(reg32, val) REG_FLD_SET(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_KBAND_DIV_PCIE, (reg32), (val))

#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_SET_RG_QP_RX_D0_LL_RESERVED(reg32, val) REG_FLD_SET(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_RX_D0_LL_RESERVED, (reg32), (val))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_SET_RG_QP_CDR_REFCK_DIV2_EN(reg32, val) REG_FLD_SET(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_REFCK_DIV2_EN, (reg32), (val))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_SET_RG_QP_RX_MPX_SEL(reg32, val) REG_FLD_SET(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_RX_MPX_SEL, (reg32), (val))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_SET_RG_QP_CDR_PHYCK_SEL(reg32, val) REG_FLD_SET(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PHYCK_SEL, (reg32), (val))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_SET_RG_QP_CDR_PHYCK_RSTB(reg32, val) REG_FLD_SET(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PHYCK_RSTB, (reg32), (val))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_SET_RG_QP_CDR_PHYCK_DIV(reg32, val) REG_FLD_SET(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PHYCK_DIV, (reg32), (val))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_SET_RG_QP_CDR_PI_CK_INV(reg32, val) REG_FLD_SET(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PI_CK_INV, (reg32), (val))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_SET_RG_QP_CDR_PIEYE_XOR_EN(reg32, val) REG_FLD_SET(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PIEYE_XOR_EN, (reg32), (val))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_SET_RG_QP_CDR_PIEYEBD4_SEL(reg32, val) REG_FLD_SET(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PIEYEBD4_SEL, (reg32), (val))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_SET_RG_QP_CDR_PICAL_SEL(reg32, val) REG_FLD_SET(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PICAL_SEL, (reg32), (val))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_SET_RG_QP_CDR_PICAL_INV(reg32, val) REG_FLD_SET(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PICAL_INV, (reg32), (val))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_SET_RG_QP_CDR_FORCE_IBANDLPF_R_OFF(reg32, val) REG_FLD_SET(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_FORCE_IBANDLPF_R_OFF, (reg32), (val))

#define RG_QP_RX_D0_HS_RESERVED_SET_RG_QP_RX_D1_HS_RESERVED(reg32, val) REG_FLD_SET(RG_QP_RX_D0_HS_RESERVED_FLD_RG_QP_RX_D1_HS_RESERVED, (reg32), (val))
#define RG_QP_RX_D0_HS_RESERVED_SET_RG_QP_RX_D0_HS_RESERVED(reg32, val) REG_FLD_SET(RG_QP_RX_D0_HS_RESERVED_FLD_RG_QP_RX_D0_HS_RESERVED, (reg32), (val))

#define RG_QP_TX_MODE_16B_EN_SET_RG_QP_TX_RESERVE(reg32, val)  REG_FLD_SET(RG_QP_TX_MODE_16B_EN_FLD_RG_QP_TX_RESERVE, (reg32), (val))
#define RG_QP_TX_MODE_16B_EN_SET_RG_QP_TX_CKMON_SEL(reg32, val) REG_FLD_SET(RG_QP_TX_MODE_16B_EN_FLD_RG_QP_TX_CKMON_SEL, (reg32), (val))
#define RG_QP_TX_MODE_16B_EN_SET_RG_QP_TX_CKMON_EN(reg32, val) REG_FLD_SET(RG_QP_TX_MODE_16B_EN_FLD_RG_QP_TX_CKMON_EN, (reg32), (val))
#define RG_QP_TX_MODE_16B_EN_SET_RG_QP_TX_VLMON_SEL(reg32, val) REG_FLD_SET(RG_QP_TX_MODE_16B_EN_FLD_RG_QP_TX_VLMON_SEL, (reg32), (val))
#define RG_QP_TX_MODE_16B_EN_SET_RG_QP_TX_VLMON_EN(reg32, val) REG_FLD_SET(RG_QP_TX_MODE_16B_EN_FLD_RG_QP_TX_VLMON_EN, (reg32), (val))
#define RG_QP_TX_MODE_16B_EN_SET_RG_QP_TXLBRX_EN(reg32, val)   REG_FLD_SET(RG_QP_TX_MODE_16B_EN_FLD_RG_QP_TXLBRX_EN, (reg32), (val))
#define RG_QP_TX_MODE_16B_EN_SET_RG_QP_TX_MODE_16B_EN(reg32, val) REG_FLD_SET(RG_QP_TX_MODE_16B_EN_FLD_RG_QP_TX_MODE_16B_EN, (reg32), (val))

#define RG_QP_RXLBTX_EN_SET_RG_QP_TX_DMEDGEGEN_EN(reg32, val)  REG_FLD_SET(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_DMEDGEGEN_EN, (reg32), (val))
#define RG_QP_RXLBTX_EN_SET_RG_QP_TX_AUTOZERO_EN(reg32, val)   REG_FLD_SET(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_AUTOZERO_EN, (reg32), (val))
#define RG_QP_RXLBTX_EN_SET_RG_QP_TX_RXDET_METHOD(reg32, val)  REG_FLD_SET(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_RXDET_METHOD, (reg32), (val))
#define RG_QP_RXLBTX_EN_SET_RG_QP_TX_TERMCAL_SELPN(reg32, val) REG_FLD_SET(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_TERMCAL_SELPN, (reg32), (val))
#define RG_QP_RXLBTX_EN_SET_RG_QP_TX_TERMCAL_VREF_L(reg32, val) REG_FLD_SET(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_TERMCAL_VREF_L, (reg32), (val))
#define RG_QP_RXLBTX_EN_SET_RG_QP_TX_TERMCAL_VREF_H(reg32, val) REG_FLD_SET(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_TERMCAL_VREF_H, (reg32), (val))
#define RG_QP_RXLBTX_EN_SET_RG_QP_TX_INT_EN(reg32, val)        REG_FLD_SET(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_INT_EN, (reg32), (val))
#define RG_QP_RXLBTX_EN_SET_RG_QP_TX_SR_REDUCTION(reg32, val)  REG_FLD_SET(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_SR_REDUCTION, (reg32), (val))
#define RG_QP_RXLBTX_EN_SET_RG_QP_TX_CHGPLR_C2(reg32, val)     REG_FLD_SET(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_CHGPLR_C2, (reg32), (val))
#define RG_QP_RXLBTX_EN_SET_RG_QP_TX_CHGPLR_C1(reg32, val)     REG_FLD_SET(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_CHGPLR_C1, (reg32), (val))
#define RG_QP_RXLBTX_EN_SET_RG_QP_TX_CHGPLR_CN1(reg32, val)    REG_FLD_SET(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_CHGPLR_CN1, (reg32), (val))
#define RG_QP_RXLBTX_EN_SET_RG_QP_TX250MCK_INVB(reg32, val)    REG_FLD_SET(RG_QP_RXLBTX_EN_FLD_RG_QP_TX250MCK_INVB, (reg32), (val))
#define RG_QP_RXLBTX_EN_SET_RG_QP_RXLBTX_EN(reg32, val)        REG_FLD_SET(RG_QP_RXLBTX_EN_FLD_RG_QP_RXLBTX_EN, (reg32), (val))

#define RG_QP_BGR_EN_SET_RG_QP_BG_MONEN(reg32, val)            REG_FLD_SET(RG_QP_BGR_EN_FLD_RG_QP_BG_MONEN, (reg32), (val))
#define RG_QP_BGR_EN_SET_RG_QP_BIAS_V2V_CAL(reg32, val)        REG_FLD_SET(RG_QP_BGR_EN_FLD_RG_QP_BIAS_V2V_CAL, (reg32), (val))
#define RG_QP_BGR_EN_SET_RG_QP_VRT_VREF_SEL(reg32, val)        REG_FLD_SET(RG_QP_BGR_EN_FLD_RG_QP_VRT_VREF_SEL, (reg32), (val))
#define RG_QP_BGR_EN_SET_RG_QP_MPX_SEL(reg32, val)             REG_FLD_SET(RG_QP_BGR_EN_FLD_RG_QP_MPX_SEL, (reg32), (val))
#define RG_QP_BGR_EN_SET_RG_QP_MPX_EN(reg32, val)              REG_FLD_SET(RG_QP_BGR_EN_FLD_RG_QP_MPX_EN, (reg32), (val))
#define RG_QP_BGR_EN_SET_RG_QP_BG_DIV(reg32, val)              REG_FLD_SET(RG_QP_BGR_EN_FLD_RG_QP_BG_DIV, (reg32), (val))
#define RG_QP_BGR_EN_SET_RG_QP_CHPEN(reg32, val)               REG_FLD_SET(RG_QP_BGR_EN_FLD_RG_QP_CHPEN, (reg32), (val))
#define RG_QP_BGR_EN_SET_RG_QP_BGR_EN(reg32, val)              REG_FLD_SET(RG_QP_BGR_EN_FLD_RG_QP_BGR_EN, (reg32), (val))

#define RG_PCIE_CLKDRV_IMPSEL_SET_RG_QP_TDC_AUTOEN(reg32, val) REG_FLD_SET(RG_PCIE_CLKDRV_IMPSEL_FLD_RG_QP_TDC_AUTOEN, (reg32), (val))
#define RG_PCIE_CLKDRV_IMPSEL_SET_RG_PCIE_CLKDET_VTH(reg32, val) REG_FLD_SET(RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDET_VTH, (reg32), (val))
#define RG_PCIE_CLKDRV_IMPSEL_SET_RG_PCIE_CLKDRV_AMP(reg32, val) REG_FLD_SET(RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_AMP, (reg32), (val))
#define RG_PCIE_CLKDRV_IMPSEL_SET_RG_PCIE_CLKDRV_FORCEIN(reg32, val) REG_FLD_SET(RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_FORCEIN, (reg32), (val))
#define RG_PCIE_CLKDRV_IMPSEL_SET_RG_PCIE_CLKDRV_DUTY(reg32, val) REG_FLD_SET(RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_DUTY, (reg32), (val))
#define RG_PCIE_CLKDRV_IMPSEL_SET_RG_PCIE_CLKDRV_SLEW(reg32, val) REG_FLD_SET(RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_SLEW, (reg32), (val))
#define RG_PCIE_CLKDRV_IMPSEL_SET_RG_PCIE_CLKDRV_OFFSET(reg32, val) REG_FLD_SET(RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_OFFSET, (reg32), (val))
#define RG_PCIE_CLKDRV_IMPSEL_SET_RG_PCIE_CLKDRV_HZ(reg32, val) REG_FLD_SET(RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_HZ, (reg32), (val))
#define RG_PCIE_CLKDRV_IMPSEL_SET_RG_PCIE_CLKDRV_RP(reg32, val) REG_FLD_SET(RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_RP, (reg32), (val))
#define RG_PCIE_CLKDRV_IMPSEL_SET_RG_PCIE_CLKDRV_IMPSEL(reg32, val) REG_FLD_SET(RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_IMPSEL, (reg32), (val))

#define RG_QP_TDC_FT_CK_EN_SET_RG_QP_PLL_IBAND(reg32, val)     REG_FLD_SET(RG_QP_TDC_FT_CK_EN_FLD_RG_QP_PLL_IBAND, (reg32), (val))
#define RG_QP_TDC_FT_CK_EN_SET_RG_QP_PLL_DEBUG_SEL(reg32, val) REG_FLD_SET(RG_QP_TDC_FT_CK_EN_FLD_RG_QP_PLL_DEBUG_SEL, (reg32), (val))
#define RG_QP_TDC_FT_CK_EN_SET_RG_QP_PLL_RST_DLY(reg32, val)   REG_FLD_SET(RG_QP_TDC_FT_CK_EN_FLD_RG_QP_PLL_RST_DLY, (reg32), (val))
#define RG_QP_TDC_FT_CK_EN_SET_RG_QP_XTAL_TOP_RESERVE0(reg32, val) REG_FLD_SET(RG_QP_TDC_FT_CK_EN_FLD_RG_QP_XTAL_TOP_RESERVE0, (reg32), (val))
#define RG_QP_TDC_FT_CK_EN_SET_RG_VUSB10_ON(reg32, val)        REG_FLD_SET(RG_QP_TDC_FT_CK_EN_FLD_RG_VUSB10_ON, (reg32), (val))
#define RG_QP_TDC_FT_CK_EN_SET_RG_QP_PLL_MONCK_SEL(reg32, val) REG_FLD_SET(RG_QP_TDC_FT_CK_EN_FLD_RG_QP_PLL_MONCK_SEL, (reg32), (val))
#define RG_QP_TDC_FT_CK_EN_SET_RG_QP_TDC_MON_CK_EN(reg32, val) REG_FLD_SET(RG_QP_TDC_FT_CK_EN_FLD_RG_QP_TDC_MON_CK_EN, (reg32), (val))
#define RG_QP_TDC_FT_CK_EN_SET_RG_QP_TDC_FT_CK_EN(reg32, val)  REG_FLD_SET(RG_QP_TDC_FT_CK_EN_FLD_RG_QP_TDC_FT_CK_EN, (reg32), (val))

#define RG_QP_PLL_IPLL_DIG_PWR_SEL_SET_RG_QP_PLL_SDM_DI_LS(reg32, val) REG_FLD_SET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_SDM_DI_LS, (reg32), (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_SET_RG_QP_PLL_TCL_EN(reg32, val) REG_FLD_SET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_TCL_EN, (reg32), (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_SET_RG_QP_PLL_RLP_SEL(reg32, val) REG_FLD_SET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_RLP_SEL, (reg32), (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_SET_RG_QP_PLL_PREDIV(reg32, val) REG_FLD_SET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_PREDIV, (reg32), (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_SET_RG_QP_PLL_POSTDIV(reg32, val) REG_FLD_SET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_POSTDIV, (reg32), (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_SET_RG_QP_PLL_OSCAL_ENB(reg32, val) REG_FLD_SET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_OSCAL_ENB, (reg32), (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_SET_RG_QP_PLL_MON_LDO_SEL(reg32, val) REG_FLD_SET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_MON_LDO_SEL, (reg32), (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_SET_RG_QP_PLL_MONVC_EN(reg32, val) REG_FLD_SET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_MONVC_EN, (reg32), (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_SET_RG_QP_PLL_MONREF_EN(reg32, val) REG_FLD_SET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_MONREF_EN, (reg32), (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_SET_RG_QP_PLL_MONCK_EN(reg32, val) REG_FLD_SET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_MONCK_EN, (reg32), (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_SET_RG_QP_PLL_MONCK_DIV4_EN(reg32, val) REG_FLD_SET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_MONCK_DIV4_EN, (reg32), (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_SET_RG_QP_PLL_LDOVCO_VSEL(reg32, val) REG_FLD_SET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_LDOVCO_VSEL, (reg32), (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_SET_RG_QP_PLL_LDOPFD_VSEL(reg32, val) REG_FLD_SET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_LDOPFD_VSEL, (reg32), (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_SET_RG_QP_PLL_LDOLPF_VSEL(reg32, val) REG_FLD_SET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_LDOLPF_VSEL, (reg32), (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_SET_RG_QP_PLL_LOAD_EN(reg32, val) REG_FLD_SET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_LOAD_EN, (reg32), (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_SET_RG_QP_PLL_KBAND_MEAS_EN(reg32, val) REG_FLD_SET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_KBAND_MEAS_EN, (reg32), (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_SET_RG_QP_PLL_KBAND_KFC(reg32, val) REG_FLD_SET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_KBAND_KFC, (reg32), (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_SET_RG_QP_PLL_IPLL_DIG_PWR_SEL(reg32, val) REG_FLD_SET(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_IPLL_DIG_PWR_SEL, (reg32), (val))

#define RG_QP_PLL_SDM_ORD_SET_RG_QP_PLL_FREQ_MEAS_EN(reg32, val) REG_FLD_SET(RG_QP_PLL_SDM_ORD_FLD_RG_QP_PLL_FREQ_MEAS_EN, (reg32), (val))
#define RG_QP_PLL_SDM_ORD_SET_RG_QP_PLL_POST_MONCK_SEL(reg32, val) REG_FLD_SET(RG_QP_PLL_SDM_ORD_FLD_RG_QP_PLL_POST_MONCK_SEL, (reg32), (val))
#define RG_QP_PLL_SDM_ORD_SET_RG_QP_PLL_POST_MONCK_EN(reg32, val) REG_FLD_SET(RG_QP_PLL_SDM_ORD_FLD_RG_QP_PLL_POST_MONCK_EN, (reg32), (val))
#define RG_QP_PLL_SDM_ORD_SET_RG_QP_PLL_SSC_TRI_EN(reg32, val) REG_FLD_SET(RG_QP_PLL_SDM_ORD_FLD_RG_QP_PLL_SSC_TRI_EN, (reg32), (val))
#define RG_QP_PLL_SDM_ORD_SET_RG_QP_PLL_SSC_PHASE_INI(reg32, val) REG_FLD_SET(RG_QP_PLL_SDM_ORD_FLD_RG_QP_PLL_SSC_PHASE_INI, (reg32), (val))
#define RG_QP_PLL_SDM_ORD_SET_RG_QP_PLL_SDM_OUT(reg32, val)    REG_FLD_SET(RG_QP_PLL_SDM_ORD_FLD_RG_QP_PLL_SDM_OUT, (reg32), (val))
#define RG_QP_PLL_SDM_ORD_SET_RG_QP_PLL_SDM_ORD(reg32, val)    REG_FLD_SET(RG_QP_PLL_SDM_ORD_FLD_RG_QP_PLL_SDM_ORD, (reg32), (val))

#define RG_QP_RX_DAC_EN_VAL_RG_QP_RXAFE_DCMON_SEL(val)         REG_FLD_VAL(RG_QP_RX_DAC_EN_FLD_RG_QP_RXAFE_DCMON_SEL, (val))
#define RG_QP_RX_DAC_EN_VAL_RG_QP_LFPS_MON_EN(val)             REG_FLD_VAL(RG_QP_RX_DAC_EN_FLD_RG_QP_LFPS_MON_EN, (val))
#define RG_QP_RX_DAC_EN_VAL_RG_QP_LFPS_LPF_I_SEL(val)          REG_FLD_VAL(RG_QP_RX_DAC_EN_FLD_RG_QP_LFPS_LPF_I_SEL, (val))
#define RG_QP_RX_DAC_EN_VAL_RG_QP_LFPS_LPF_I(val)              REG_FLD_VAL(RG_QP_RX_DAC_EN_FLD_RG_QP_LFPS_LPF_I, (val))
#define RG_QP_RX_DAC_EN_VAL_RG_QP_LFPS_LPF(val)                REG_FLD_VAL(RG_QP_RX_DAC_EN_FLD_RG_QP_LFPS_LPF, (val))
#define RG_QP_RX_DAC_EN_VAL_RG_QP_LFPS_SLCOUT_SEL(val)         REG_FLD_VAL(RG_QP_RX_DAC_EN_FLD_RG_QP_LFPS_SLCOUT_SEL, (val))
#define RG_QP_RX_DAC_EN_VAL_RG_QP_LFPS_CMPOUT_SEL(val)         REG_FLD_VAL(RG_QP_RX_DAC_EN_FLD_RG_QP_LFPS_CMPOUT_SEL, (val))
#define RG_QP_RX_DAC_EN_VAL_RG_QP_LFPS_LPF_AUX(val)            REG_FLD_VAL(RG_QP_RX_DAC_EN_FLD_RG_QP_LFPS_LPF_AUX, (val))
#define RG_QP_RX_DAC_EN_VAL_RG_QP_SIGDET_HF(val)               REG_FLD_VAL(RG_QP_RX_DAC_EN_FLD_RG_QP_SIGDET_HF, (val))
#define RG_QP_RX_DAC_EN_VAL_RG_QP_SIGDET_LPF(val)              REG_FLD_VAL(RG_QP_RX_DAC_EN_FLD_RG_QP_SIGDET_LPF, (val))
#define RG_QP_RX_DAC_EN_VAL_RG_QP_SIGDET_VTH(val)              REG_FLD_VAL(RG_QP_RX_DAC_EN_FLD_RG_QP_SIGDET_VTH, (val))
#define RG_QP_RX_DAC_EN_VAL_RG_QP_RX_50_LOWER(val)             REG_FLD_VAL(RG_QP_RX_DAC_EN_FLD_RG_QP_RX_50_LOWER, (val))
#define RG_QP_RX_DAC_EN_VAL_RG_QP_RX_T2R_EN(val)               REG_FLD_VAL(RG_QP_RX_DAC_EN_FLD_RG_QP_RX_T2R_EN, (val))
#define RG_QP_RX_DAC_EN_VAL_RG_QP_RX_DAC_MUX(val)              REG_FLD_VAL(RG_QP_RX_DAC_EN_FLD_RG_QP_RX_DAC_MUX, (val))
#define RG_QP_RX_DAC_EN_VAL_RG_QP_RX_DAC_PWD(val)              REG_FLD_VAL(RG_QP_RX_DAC_EN_FLD_RG_QP_RX_DAC_PWD, (val))
#define RG_QP_RX_DAC_EN_VAL_RG_QP_RX_DAC_EN(val)               REG_FLD_VAL(RG_QP_RX_DAC_EN_FLD_RG_QP_RX_DAC_EN, (val))

#define RG_QP_RXAFE_RESERVE_VAL_RG_QP_CDR_PD_10B_EN(val)       REG_FLD_VAL(RG_QP_RXAFE_RESERVE_FLD_RG_QP_CDR_PD_10B_EN, (val))
#define RG_QP_RXAFE_RESERVE_VAL_RG_QP_CDR_PD_EDGE_DIS(val)     REG_FLD_VAL(RG_QP_RXAFE_RESERVE_FLD_RG_QP_CDR_PD_EDGE_DIS, (val))
#define RG_QP_RXAFE_RESERVE_VAL_RG_QP_RX_VCMHPFSEL(val)        REG_FLD_VAL(RG_QP_RXAFE_RESERVE_FLD_RG_QP_RX_VCMHPFSEL, (val))
#define RG_QP_RXAFE_RESERVE_VAL_RG_QP_RX_DAC_MEAS_EN(val)      REG_FLD_VAL(RG_QP_RXAFE_RESERVE_FLD_RG_QP_RX_DAC_MEAS_EN, (val))
#define RG_QP_RXAFE_RESERVE_VAL_RG_QP_RXAFE_RESERVE(val)       REG_FLD_VAL(RG_QP_RXAFE_RESERVE_FLD_RG_QP_RXAFE_RESERVE, (val))

#define RG_QP_CDR_LPF_BOT_LIM_VAL_RG_QP_CDR_LPF_MJV_EN(val)    REG_FLD_VAL(RG_QP_CDR_LPF_BOT_LIM_FLD_RG_QP_CDR_LPF_MJV_EN, (val))
#define RG_QP_CDR_LPF_BOT_LIM_VAL_RG_QP_CDR_LPF_LIN_LIM(val)   REG_FLD_VAL(RG_QP_CDR_LPF_BOT_LIM_FLD_RG_QP_CDR_LPF_LIN_LIM, (val))
#define RG_QP_CDR_LPF_BOT_LIM_VAL_RG_QP_CDR_LPF_KP_GAIN(val)   REG_FLD_VAL(RG_QP_CDR_LPF_BOT_LIM_FLD_RG_QP_CDR_LPF_KP_GAIN, (val))
#define RG_QP_CDR_LPF_BOT_LIM_VAL_RG_QP_CDR_LPF_KI_GAIN(val)   REG_FLD_VAL(RG_QP_CDR_LPF_BOT_LIM_FLD_RG_QP_CDR_LPF_KI_GAIN, (val))
#define RG_QP_CDR_LPF_BOT_LIM_VAL_RG_QP_CDR_LPF_BOT_LIM(val)   REG_FLD_VAL(RG_QP_CDR_LPF_BOT_LIM_FLD_RG_QP_CDR_LPF_BOT_LIM, (val))

#define RG_QP_CDR_LPF_MJV_LIM_VAL_RG_QP_CDR_LPF_RATIO(val)     REG_FLD_VAL(RG_QP_CDR_LPF_MJV_LIM_FLD_RG_QP_CDR_LPF_RATIO, (val))
#define RG_QP_CDR_LPF_MJV_LIM_VAL_RG_QP_CDR_LPF_MJV_LIM(val)   REG_FLD_VAL(RG_QP_CDR_LPF_MJV_LIM_FLD_RG_QP_CDR_LPF_MJV_LIM, (val))

#define RG_QP_CDR_LPF_TOP_LIM_VAL_RG_QP_CDR_LPF_ONESHOT_OUT_SEL(val) REG_FLD_VAL(RG_QP_CDR_LPF_TOP_LIM_FLD_RG_QP_CDR_LPF_ONESHOT_OUT_SEL, (val))
#define RG_QP_CDR_LPF_TOP_LIM_VAL_RG_QP_CDR_LPF_SET(val)       REG_FLD_VAL(RG_QP_CDR_LPF_TOP_LIM_FLD_RG_QP_CDR_LPF_SET, (val))
#define RG_QP_CDR_LPF_TOP_LIM_VAL_RG_QP_CDR_LPF_SNAPSHOT(val)  REG_FLD_VAL(RG_QP_CDR_LPF_TOP_LIM_FLD_RG_QP_CDR_LPF_SNAPSHOT, (val))
#define RG_QP_CDR_LPF_TOP_LIM_VAL_RG_QP_CDR_LPF_TOP_LIM(val)   REG_FLD_VAL(RG_QP_CDR_LPF_TOP_LIM_FLD_RG_QP_CDR_LPF_TOP_LIM, (val))

#define RG_QP_CDR_LPF_SETVALUE_VAL_RG_QP_CDR_PR_BUF_IN_SR(val) REG_FLD_VAL(RG_QP_CDR_LPF_SETVALUE_FLD_RG_QP_CDR_PR_BUF_IN_SR, (val))
#define RG_QP_CDR_LPF_SETVALUE_VAL_RG_QP_CDR_PR_BETA_SEL(val)  REG_FLD_VAL(RG_QP_CDR_LPF_SETVALUE_FLD_RG_QP_CDR_PR_BETA_SEL, (val))
#define RG_QP_CDR_LPF_SETVALUE_VAL_RG_QP_CDR_LPF_UD_GATING(val) REG_FLD_VAL(RG_QP_CDR_LPF_SETVALUE_FLD_RG_QP_CDR_LPF_UD_GATING, (val))
#define RG_QP_CDR_LPF_SETVALUE_VAL_RG_QP_CDR_LPF_PISTEP_SEL(val) REG_FLD_VAL(RG_QP_CDR_LPF_SETVALUE_FLD_RG_QP_CDR_LPF_PISTEP_SEL, (val))
#define RG_QP_CDR_LPF_SETVALUE_VAL_RG_QP_CDR_LPF_PISTEP_ONESHOT(val) REG_FLD_VAL(RG_QP_CDR_LPF_SETVALUE_FLD_RG_QP_CDR_LPF_PISTEP_ONESHOT, (val))
#define RG_QP_CDR_LPF_SETVALUE_VAL_RG_QP_CDR_LPF_ONESHOT_STEP(val) REG_FLD_VAL(RG_QP_CDR_LPF_SETVALUE_FLD_RG_QP_CDR_LPF_ONESHOT_STEP, (val))
#define RG_QP_CDR_LPF_SETVALUE_VAL_RG_QP_CDR_LPF_SETVALUE(val) REG_FLD_VAL(RG_QP_CDR_LPF_SETVALUE_FLD_RG_QP_CDR_LPF_SETVALUE, (val))

#define RG_QP_CDR_PR_CKREF_DIV1_VAL_RG_QP_CDR_PR_KBAND_DIV(val) REG_FLD_VAL(RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_KBAND_DIV, (val))
#define RG_QP_CDR_PR_CKREF_DIV1_VAL_RG_QP_CDR_PR_INJ_FORCE_ON(val) REG_FLD_VAL(RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_INJ_FORCE_ON, (val))
#define RG_QP_CDR_PR_CKREF_DIV1_VAL_RG_QP_CDR_PR_INJ_FORCE_OFF(val) REG_FLD_VAL(RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_INJ_FORCE_OFF, (val))
#define RG_QP_CDR_PR_CKREF_DIV1_VAL_RG_QP_CDR_PR_DCMON_SEL(val) REG_FLD_VAL(RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_DCMON_SEL, (val))
#define RG_QP_CDR_PR_CKREF_DIV1_VAL_RG_QP_CDR_PR_DCMON_EN(val) REG_FLD_VAL(RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_DCMON_EN, (val))
#define RG_QP_CDR_PR_CKREF_DIV1_VAL_RG_QP_CDR_PR_DAC_BAND(val) REG_FLD_VAL(RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_DAC_BAND, (val))
#define RG_QP_CDR_PR_CKREF_DIV1_VAL_RG_QP_CDR_PR_COR_HBW_EN(val) REG_FLD_VAL(RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_COR_HBW_EN, (val))
#define RG_QP_CDR_PR_CKREF_DIV1_VAL_RG_QP_CDR_PR_CORSIG_OPT(val) REG_FLD_VAL(RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_CORSIG_OPT, (val))
#define RG_QP_CDR_PR_CKREF_DIV1_VAL_RG_QP_CDR_PR_CKREF_DIV(val) REG_FLD_VAL(RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_CKREF_DIV, (val))
#define RG_QP_CDR_PR_CKREF_DIV1_VAL_RG_QP_CDR_PR_CKREF_DIV1(val) REG_FLD_VAL(RG_QP_CDR_PR_CKREF_DIV1_FLD_RG_QP_CDR_PR_CKREF_DIV1, (val))

#define RG_QP_CDR_PR_KBAND_DIV_PCIE_VAL_RG_QP_CDR_FORCE_IBANDLPF_C_OFF(val) REG_FLD_VAL(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_FORCE_IBANDLPF_C_OFF, (val))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_VAL_RG_QP_CDR_PR_XFICK_EN(val) REG_FLD_VAL(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_XFICK_EN, (val))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_VAL_RG_QP_CDR_PR_VREG_CKBUF_VAL(val) REG_FLD_VAL(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_VREG_CKBUF_VAL, (val))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_VAL_RG_QP_CDR_PR_VCOADC_OS(val) REG_FLD_VAL(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_VCOADC_OS, (val))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_VAL_RG_QP_CDR_PR_TDC_REF_SEL(val) REG_FLD_VAL(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_TDC_REF_SEL, (val))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_VAL_RG_QP_CDR_PR_RST_DLY(val) REG_FLD_VAL(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_RST_DLY, (val))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_VAL_RG_QP_CDR_PR_RSTB_BYPASS(val) REG_FLD_VAL(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_RSTB_BYPASS, (val))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_VAL_RG_QP_CDR_PR_MONPR_EN(val) REG_FLD_VAL(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_MONPR_EN, (val))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_VAL_RG_QP_CDR_PR_MONPI_EN(val) REG_FLD_VAL(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_MONPI_EN, (val))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_VAL_RG_QP_CDR_PR_MONCK_MUX(val) REG_FLD_VAL(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_MONCK_MUX, (val))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_VAL_RG_QP_CDR_PR_MONCK_EN(val) REG_FLD_VAL(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_MONCK_EN, (val))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_VAL_RG_QP_CDR_PR_LDO_FORCE_ON(val) REG_FLD_VAL(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_LDO_FORCE_ON, (val))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_VAL_RG_QP_CDR_PR_KBAND_PCIE_MODE(val) REG_FLD_VAL(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_KBAND_PCIE_MODE, (val))
#define RG_QP_CDR_PR_KBAND_DIV_PCIE_VAL_RG_QP_CDR_PR_KBAND_DIV_PCIE(val) REG_FLD_VAL(RG_QP_CDR_PR_KBAND_DIV_PCIE_FLD_RG_QP_CDR_PR_KBAND_DIV_PCIE, (val))

#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_VAL_RG_QP_RX_D0_LL_RESERVED(val) REG_FLD_VAL(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_RX_D0_LL_RESERVED, (val))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_VAL_RG_QP_CDR_REFCK_DIV2_EN(val) REG_FLD_VAL(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_REFCK_DIV2_EN, (val))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_VAL_RG_QP_RX_MPX_SEL(val) REG_FLD_VAL(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_RX_MPX_SEL, (val))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_VAL_RG_QP_CDR_PHYCK_SEL(val) REG_FLD_VAL(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PHYCK_SEL, (val))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_VAL_RG_QP_CDR_PHYCK_RSTB(val) REG_FLD_VAL(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PHYCK_RSTB, (val))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_VAL_RG_QP_CDR_PHYCK_DIV(val) REG_FLD_VAL(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PHYCK_DIV, (val))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_VAL_RG_QP_CDR_PI_CK_INV(val) REG_FLD_VAL(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PI_CK_INV, (val))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_VAL_RG_QP_CDR_PIEYE_XOR_EN(val) REG_FLD_VAL(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PIEYE_XOR_EN, (val))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_VAL_RG_QP_CDR_PIEYEBD4_SEL(val) REG_FLD_VAL(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PIEYEBD4_SEL, (val))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_VAL_RG_QP_CDR_PICAL_SEL(val) REG_FLD_VAL(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PICAL_SEL, (val))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_VAL_RG_QP_CDR_PICAL_INV(val) REG_FLD_VAL(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_PICAL_INV, (val))
#define RG_QP_CDR_FORCE_IBANDLPF_R_OFF_VAL_RG_QP_CDR_FORCE_IBANDLPF_R_OFF(val) REG_FLD_VAL(RG_QP_CDR_FORCE_IBANDLPF_R_OFF_FLD_RG_QP_CDR_FORCE_IBANDLPF_R_OFF, (val))

#define RG_QP_RX_D0_HS_RESERVED_VAL_RG_QP_RX_D1_HS_RESERVED(val) REG_FLD_VAL(RG_QP_RX_D0_HS_RESERVED_FLD_RG_QP_RX_D1_HS_RESERVED, (val))
#define RG_QP_RX_D0_HS_RESERVED_VAL_RG_QP_RX_D0_HS_RESERVED(val) REG_FLD_VAL(RG_QP_RX_D0_HS_RESERVED_FLD_RG_QP_RX_D0_HS_RESERVED, (val))

#define RG_QP_TX_MODE_16B_EN_VAL_RG_QP_TX_RESERVE(val)         REG_FLD_VAL(RG_QP_TX_MODE_16B_EN_FLD_RG_QP_TX_RESERVE, (val))
#define RG_QP_TX_MODE_16B_EN_VAL_RG_QP_TX_CKMON_SEL(val)       REG_FLD_VAL(RG_QP_TX_MODE_16B_EN_FLD_RG_QP_TX_CKMON_SEL, (val))
#define RG_QP_TX_MODE_16B_EN_VAL_RG_QP_TX_CKMON_EN(val)        REG_FLD_VAL(RG_QP_TX_MODE_16B_EN_FLD_RG_QP_TX_CKMON_EN, (val))
#define RG_QP_TX_MODE_16B_EN_VAL_RG_QP_TX_VLMON_SEL(val)       REG_FLD_VAL(RG_QP_TX_MODE_16B_EN_FLD_RG_QP_TX_VLMON_SEL, (val))
#define RG_QP_TX_MODE_16B_EN_VAL_RG_QP_TX_VLMON_EN(val)        REG_FLD_VAL(RG_QP_TX_MODE_16B_EN_FLD_RG_QP_TX_VLMON_EN, (val))
#define RG_QP_TX_MODE_16B_EN_VAL_RG_QP_TXLBRX_EN(val)          REG_FLD_VAL(RG_QP_TX_MODE_16B_EN_FLD_RG_QP_TXLBRX_EN, (val))
#define RG_QP_TX_MODE_16B_EN_VAL_RG_QP_TX_MODE_16B_EN(val)     REG_FLD_VAL(RG_QP_TX_MODE_16B_EN_FLD_RG_QP_TX_MODE_16B_EN, (val))

#define RG_QP_RXLBTX_EN_VAL_RG_QP_TX_DMEDGEGEN_EN(val)         REG_FLD_VAL(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_DMEDGEGEN_EN, (val))
#define RG_QP_RXLBTX_EN_VAL_RG_QP_TX_AUTOZERO_EN(val)          REG_FLD_VAL(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_AUTOZERO_EN, (val))
#define RG_QP_RXLBTX_EN_VAL_RG_QP_TX_RXDET_METHOD(val)         REG_FLD_VAL(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_RXDET_METHOD, (val))
#define RG_QP_RXLBTX_EN_VAL_RG_QP_TX_TERMCAL_SELPN(val)        REG_FLD_VAL(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_TERMCAL_SELPN, (val))
#define RG_QP_RXLBTX_EN_VAL_RG_QP_TX_TERMCAL_VREF_L(val)       REG_FLD_VAL(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_TERMCAL_VREF_L, (val))
#define RG_QP_RXLBTX_EN_VAL_RG_QP_TX_TERMCAL_VREF_H(val)       REG_FLD_VAL(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_TERMCAL_VREF_H, (val))
#define RG_QP_RXLBTX_EN_VAL_RG_QP_TX_INT_EN(val)               REG_FLD_VAL(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_INT_EN, (val))
#define RG_QP_RXLBTX_EN_VAL_RG_QP_TX_SR_REDUCTION(val)         REG_FLD_VAL(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_SR_REDUCTION, (val))
#define RG_QP_RXLBTX_EN_VAL_RG_QP_TX_CHGPLR_C2(val)            REG_FLD_VAL(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_CHGPLR_C2, (val))
#define RG_QP_RXLBTX_EN_VAL_RG_QP_TX_CHGPLR_C1(val)            REG_FLD_VAL(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_CHGPLR_C1, (val))
#define RG_QP_RXLBTX_EN_VAL_RG_QP_TX_CHGPLR_CN1(val)           REG_FLD_VAL(RG_QP_RXLBTX_EN_FLD_RG_QP_TX_CHGPLR_CN1, (val))
#define RG_QP_RXLBTX_EN_VAL_RG_QP_TX250MCK_INVB(val)           REG_FLD_VAL(RG_QP_RXLBTX_EN_FLD_RG_QP_TX250MCK_INVB, (val))
#define RG_QP_RXLBTX_EN_VAL_RG_QP_RXLBTX_EN(val)               REG_FLD_VAL(RG_QP_RXLBTX_EN_FLD_RG_QP_RXLBTX_EN, (val))

#define RG_QP_BGR_EN_VAL_RG_QP_BG_MONEN(val)                   REG_FLD_VAL(RG_QP_BGR_EN_FLD_RG_QP_BG_MONEN, (val))
#define RG_QP_BGR_EN_VAL_RG_QP_BIAS_V2V_CAL(val)               REG_FLD_VAL(RG_QP_BGR_EN_FLD_RG_QP_BIAS_V2V_CAL, (val))
#define RG_QP_BGR_EN_VAL_RG_QP_VRT_VREF_SEL(val)               REG_FLD_VAL(RG_QP_BGR_EN_FLD_RG_QP_VRT_VREF_SEL, (val))
#define RG_QP_BGR_EN_VAL_RG_QP_MPX_SEL(val)                    REG_FLD_VAL(RG_QP_BGR_EN_FLD_RG_QP_MPX_SEL, (val))
#define RG_QP_BGR_EN_VAL_RG_QP_MPX_EN(val)                     REG_FLD_VAL(RG_QP_BGR_EN_FLD_RG_QP_MPX_EN, (val))
#define RG_QP_BGR_EN_VAL_RG_QP_BG_DIV(val)                     REG_FLD_VAL(RG_QP_BGR_EN_FLD_RG_QP_BG_DIV, (val))
#define RG_QP_BGR_EN_VAL_RG_QP_CHPEN(val)                      REG_FLD_VAL(RG_QP_BGR_EN_FLD_RG_QP_CHPEN, (val))
#define RG_QP_BGR_EN_VAL_RG_QP_BGR_EN(val)                     REG_FLD_VAL(RG_QP_BGR_EN_FLD_RG_QP_BGR_EN, (val))

#define RG_PCIE_CLKDRV_IMPSEL_VAL_RG_QP_TDC_AUTOEN(val)        REG_FLD_VAL(RG_PCIE_CLKDRV_IMPSEL_FLD_RG_QP_TDC_AUTOEN, (val))
#define RG_PCIE_CLKDRV_IMPSEL_VAL_RG_PCIE_CLKDET_VTH(val)      REG_FLD_VAL(RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDET_VTH, (val))
#define RG_PCIE_CLKDRV_IMPSEL_VAL_RG_PCIE_CLKDRV_AMP(val)      REG_FLD_VAL(RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_AMP, (val))
#define RG_PCIE_CLKDRV_IMPSEL_VAL_RG_PCIE_CLKDRV_FORCEIN(val)  REG_FLD_VAL(RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_FORCEIN, (val))
#define RG_PCIE_CLKDRV_IMPSEL_VAL_RG_PCIE_CLKDRV_DUTY(val)     REG_FLD_VAL(RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_DUTY, (val))
#define RG_PCIE_CLKDRV_IMPSEL_VAL_RG_PCIE_CLKDRV_SLEW(val)     REG_FLD_VAL(RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_SLEW, (val))
#define RG_PCIE_CLKDRV_IMPSEL_VAL_RG_PCIE_CLKDRV_OFFSET(val)   REG_FLD_VAL(RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_OFFSET, (val))
#define RG_PCIE_CLKDRV_IMPSEL_VAL_RG_PCIE_CLKDRV_HZ(val)       REG_FLD_VAL(RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_HZ, (val))
#define RG_PCIE_CLKDRV_IMPSEL_VAL_RG_PCIE_CLKDRV_RP(val)       REG_FLD_VAL(RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_RP, (val))
#define RG_PCIE_CLKDRV_IMPSEL_VAL_RG_PCIE_CLKDRV_IMPSEL(val)   REG_FLD_VAL(RG_PCIE_CLKDRV_IMPSEL_FLD_RG_PCIE_CLKDRV_IMPSEL, (val))

#define RG_QP_TDC_FT_CK_EN_VAL_RG_QP_PLL_IBAND(val)            REG_FLD_VAL(RG_QP_TDC_FT_CK_EN_FLD_RG_QP_PLL_IBAND, (val))
#define RG_QP_TDC_FT_CK_EN_VAL_RG_QP_PLL_DEBUG_SEL(val)        REG_FLD_VAL(RG_QP_TDC_FT_CK_EN_FLD_RG_QP_PLL_DEBUG_SEL, (val))
#define RG_QP_TDC_FT_CK_EN_VAL_RG_QP_PLL_RST_DLY(val)          REG_FLD_VAL(RG_QP_TDC_FT_CK_EN_FLD_RG_QP_PLL_RST_DLY, (val))
#define RG_QP_TDC_FT_CK_EN_VAL_RG_QP_XTAL_TOP_RESERVE0(val)    REG_FLD_VAL(RG_QP_TDC_FT_CK_EN_FLD_RG_QP_XTAL_TOP_RESERVE0, (val))
#define RG_QP_TDC_FT_CK_EN_VAL_RG_VUSB10_ON(val)               REG_FLD_VAL(RG_QP_TDC_FT_CK_EN_FLD_RG_VUSB10_ON, (val))
#define RG_QP_TDC_FT_CK_EN_VAL_RG_QP_PLL_MONCK_SEL(val)        REG_FLD_VAL(RG_QP_TDC_FT_CK_EN_FLD_RG_QP_PLL_MONCK_SEL, (val))
#define RG_QP_TDC_FT_CK_EN_VAL_RG_QP_TDC_MON_CK_EN(val)        REG_FLD_VAL(RG_QP_TDC_FT_CK_EN_FLD_RG_QP_TDC_MON_CK_EN, (val))
#define RG_QP_TDC_FT_CK_EN_VAL_RG_QP_TDC_FT_CK_EN(val)         REG_FLD_VAL(RG_QP_TDC_FT_CK_EN_FLD_RG_QP_TDC_FT_CK_EN, (val))

#define RG_QP_PLL_IPLL_DIG_PWR_SEL_VAL_RG_QP_PLL_SDM_DI_LS(val) REG_FLD_VAL(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_SDM_DI_LS, (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_VAL_RG_QP_PLL_TCL_EN(val)   REG_FLD_VAL(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_TCL_EN, (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_VAL_RG_QP_PLL_RLP_SEL(val)  REG_FLD_VAL(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_RLP_SEL, (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_VAL_RG_QP_PLL_PREDIV(val)   REG_FLD_VAL(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_PREDIV, (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_VAL_RG_QP_PLL_POSTDIV(val)  REG_FLD_VAL(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_POSTDIV, (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_VAL_RG_QP_PLL_OSCAL_ENB(val) REG_FLD_VAL(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_OSCAL_ENB, (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_VAL_RG_QP_PLL_MON_LDO_SEL(val) REG_FLD_VAL(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_MON_LDO_SEL, (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_VAL_RG_QP_PLL_MONVC_EN(val) REG_FLD_VAL(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_MONVC_EN, (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_VAL_RG_QP_PLL_MONREF_EN(val) REG_FLD_VAL(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_MONREF_EN, (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_VAL_RG_QP_PLL_MONCK_EN(val) REG_FLD_VAL(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_MONCK_EN, (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_VAL_RG_QP_PLL_MONCK_DIV4_EN(val) REG_FLD_VAL(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_MONCK_DIV4_EN, (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_VAL_RG_QP_PLL_LDOVCO_VSEL(val) REG_FLD_VAL(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_LDOVCO_VSEL, (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_VAL_RG_QP_PLL_LDOPFD_VSEL(val) REG_FLD_VAL(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_LDOPFD_VSEL, (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_VAL_RG_QP_PLL_LDOLPF_VSEL(val) REG_FLD_VAL(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_LDOLPF_VSEL, (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_VAL_RG_QP_PLL_LOAD_EN(val)  REG_FLD_VAL(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_LOAD_EN, (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_VAL_RG_QP_PLL_KBAND_MEAS_EN(val) REG_FLD_VAL(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_KBAND_MEAS_EN, (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_VAL_RG_QP_PLL_KBAND_KFC(val) REG_FLD_VAL(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_KBAND_KFC, (val))
#define RG_QP_PLL_IPLL_DIG_PWR_SEL_VAL_RG_QP_PLL_IPLL_DIG_PWR_SEL(val) REG_FLD_VAL(RG_QP_PLL_IPLL_DIG_PWR_SEL_FLD_RG_QP_PLL_IPLL_DIG_PWR_SEL, (val))

#define RG_QP_PLL_SDM_ORD_VAL_RG_QP_PLL_FREQ_MEAS_EN(val)      REG_FLD_VAL(RG_QP_PLL_SDM_ORD_FLD_RG_QP_PLL_FREQ_MEAS_EN, (val))
#define RG_QP_PLL_SDM_ORD_VAL_RG_QP_PLL_POST_MONCK_SEL(val)    REG_FLD_VAL(RG_QP_PLL_SDM_ORD_FLD_RG_QP_PLL_POST_MONCK_SEL, (val))
#define RG_QP_PLL_SDM_ORD_VAL_RG_QP_PLL_POST_MONCK_EN(val)     REG_FLD_VAL(RG_QP_PLL_SDM_ORD_FLD_RG_QP_PLL_POST_MONCK_EN, (val))
#define RG_QP_PLL_SDM_ORD_VAL_RG_QP_PLL_SSC_TRI_EN(val)        REG_FLD_VAL(RG_QP_PLL_SDM_ORD_FLD_RG_QP_PLL_SSC_TRI_EN, (val))
#define RG_QP_PLL_SDM_ORD_VAL_RG_QP_PLL_SSC_PHASE_INI(val)     REG_FLD_VAL(RG_QP_PLL_SDM_ORD_FLD_RG_QP_PLL_SSC_PHASE_INI, (val))
#define RG_QP_PLL_SDM_ORD_VAL_RG_QP_PLL_SDM_OUT(val)           REG_FLD_VAL(RG_QP_PLL_SDM_ORD_FLD_RG_QP_PLL_SDM_OUT, (val))
#define RG_QP_PLL_SDM_ORD_VAL_RG_QP_PLL_SDM_ORD(val)           REG_FLD_VAL(RG_QP_PLL_SDM_ORD_FLD_RG_QP_PLL_SDM_ORD, (val))

#ifdef __cplusplus
}
#endif

#endif // __qp_ana_csr_REGS_H__

