ifneq ($(strip $(TCSUPPORT_CPU_AN7583)),)
obj-y += an7583/air_eth_xsgmii.o
obj-y += an7583/air_xpon_xsgmii.o
obj-y += an7583/air_usb_xsgmii.o
obj-y += an7583/air_pcie1_xsgmii.o
obj-y += an7583/air_pcie0_xsgmii.o
obj-y += an7583/air_xsgmii_proc.o
obj-y += an7583/air_xsgmii_api.o
endif