#ifndef __pon_hsgmii_ana_csr_REGS_H__
#define __pon_hsgmii_ana_csr_REGS_H__

//#include "common.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef REG_BASE_C_MODULE
// ----------------- pon_hsgmii_ana_csr Bit Field Definitions -------------------

#define PACKING
typedef unsigned int FIELD;
typedef unsigned int UINT32; 

typedef PACKING union
{
    PACKING struct
    {
        FIELD RG_PON_TDC_RXCK_TEST_EN   : 1;
        FIELD RG_PON_TDC_TXCKDIV_SEL    : 2;
        FIELD RG_PON_TDC_RXCKDIV_SEL    : 2;
        FIELD RG_PON_TDC_AUTOEN         : 1;
        FIELD RG_PON_TXPLL_REFIN_LPBK_CKEN : 1;
        FIELD rsv_7                     : 1;
        FIELD RG_PON_TDC_RESERVED       : 8;
        FIELD rsv_16                    : 16;
    } Bits;
    UINT32 Raw;
} REG_RG_PON_TDC_RXCK_TEST_EN, *PREG_RG_PON_TDC_RXCK_TEST_EN;

typedef PACKING union
{
    PACKING struct
    {
        FIELD RG_SSUSB_BGR_EN           : 1;
        FIELD RG_SSUSB_CHPEN            : 1;
        FIELD RG_SSUSB_BG_DIV           : 2;
        FIELD RG_SSUSB_VRT_25M_EN       : 1;
        FIELD RG_SSUSB_INTR_EN          : 1;
        FIELD rsv_6                     : 1;
        FIELD RG_SSUSB_MPX_EN           : 1;
        FIELD RG_SSUSB_MPX_SEL          : 8;
        FIELD rsv_16                    : 2;
        FIELD RG_SSUSB_IEXT_INTR_CTRL   : 6;
        FIELD RG_SSUSB_VRT_VREF_SEL     : 4;
        FIELD RG_SSUSB_REF_EN           : 1;
        FIELD RG_SSUSB_BG_MONEN         : 1;
        FIELD RG_SSUSB_INT_BIAS_SEL     : 1;
        FIELD RG_SSUSB_EXT_BIAS_SEL     : 1;
    } Bits;
    UINT32 Raw;
} REG_RG_SSUSB_BGR_EN, *PREG_RG_SSUSB_BGR_EN;

typedef PACKING union
{
    PACKING struct
    {
        FIELD RG_PCIE_CLKDRV_OFFSET     : 2;
        FIELD RG_PCIE_CLKDRV_SLEW       : 2;
        FIELD RG_PCIE_CLKDRV_AMP        : 3;
        FIELD rsv_7                     : 1;
        FIELD RG_PCIE_CLKDET_VTH        : 2;
        FIELD RG_VUSB10_ON              : 1;
        FIELD RG_SSUSB_XTAL_TST_A2DCK_EN : 1;
        FIELD RG_SSUSB_XTAL_MON_EN      : 1;
        FIELD RG_SSUSB_XTAL_HYS         : 1;
        FIELD rsv_14                    : 2;
        FIELD RG_SSUSB_XTAL_TOP_RESERVE : 16;
    } Bits;
    UINT32 Raw;
} REG_RG_PCIE_CLKDRV_OFFSET, *PREG_RG_PCIE_CLKDRV_OFFSET;

typedef PACKING union
{
    PACKING struct
    {
        FIELD rsv_0                     : 19;
        FIELD RG_PON_PLL_RXREF_SEL      : 1;
        FIELD RG_PCIE_CLKDRV_IMPSEL     : 5;
        FIELD RG_PCIE_CLKDRV_HZ         : 1;
        FIELD RG_PCIE_CLKDRV_FORCE      : 2;
        FIELD RG_SSUSB_PLL_RST_DLY      : 2;
        FIELD RG_SSUSB_PLL_RICO_SEL     : 1;
        FIELD rsv_31                    : 1;
    } Bits;
    UINT32 Raw;
} REG_RG_PON_PLL_RXREF_SEL, *PREG_RG_PON_PLL_RXREF_SEL;

typedef PACKING union
{
    PACKING struct
    {
        FIELD RG_SSUSB_PLL_KBAND_KFC    : 2;
        FIELD RG_SSUSB_PLL_POSDIV       : 2;
        FIELD RG_SSUSB_PLL_KBAND_PREDIV : 2;
        FIELD RG_SSUSB_PLL_MONCK_EN     : 1;
        FIELD RG_SSUSB_PLL_MONVC_EN     : 1;
        FIELD RG_SSUSB_PLL_MONREF_EN    : 1;
        FIELD RG_SSUSB_PLL_MON_LDO_SEL  : 3;
        FIELD RG_SSUSB_PLL_LDOPFD_VSEL  : 2;
        FIELD RG_SSUSB_PLL_LDOCHP_VSEL  : 2;
        FIELD RG_SSUSB_PLL_LDOLPF_VSEL  : 2;
        FIELD RG_SSUSB_PLL_LDOVCO_VSEL  : 2;
        FIELD RG_SSUSB_PLL_TCL_EN       : 1;
        FIELD RG_SSUSB_PLL_RLP_SEL      : 1;
        FIELD RG_SSUSB_PLL_DEBUG_SEL    : 1;
        FIELD RG_SSUSB_PLL_IPLL_DIG_PWR_SEL : 1;
        FIELD RG_SSUSB_PLL_SDM_DI_EN    : 1;
        FIELD RG_SSUSB_PLL_SDM_DI_LS    : 2;
        FIELD RG_SSUSB_PLL_SDM_ORD      : 2;
        FIELD RG_SSUSB_PLL_SDM_MODE     : 2;
        FIELD rsv_31                    : 1;
    } Bits;
    UINT32 Raw;
} REG_RG_SSUSB_PLL_KBAND_KFC, *PREG_RG_SSUSB_PLL_KBAND_KFC;

typedef PACKING union
{
    PACKING struct
    {
        FIELD RG_SSUSB_PLL_SDM_HREN     : 2;
        FIELD RG_SSUSB_PLL_SDM_IFM      : 1;
        FIELD RG_SSUSB_PLL_SSC_PRD      : 16;
        FIELD RG_SSUSB_PLL_SSC_PH_INIT  : 1;
        FIELD RG_SSUSB_PLL_SSC_TRI_EN   : 1;
        FIELD RG_SSUSB_PLL_SSC_DIR_DLY  : 2;
        FIELD RG_SSUSB_PLL_RESERVE      : 8;
        FIELD rsv_31                    : 1;
    } Bits;
    UINT32 Raw;
} REG_RG_SSUSB_PLL_SDM_HREN, *PREG_RG_SSUSB_PLL_SDM_HREN;

typedef PACKING union
{
    PACKING struct
    {
        FIELD RG_SSUSB_LN0_CDR_RESERVE  : 8;
        FIELD RG_SSUSB_LN0_RXAFE_RESERVE : 8;
        FIELD RG_PCIE_LN0_RX_RESERVE    : 8;
        FIELD rsv_24                    : 4;
        FIELD RG_SSUSB_LN0_LNMPX_SEL    : 4;
    } Bits;
    UINT32 Raw;
} REG_RG_SSUSB_LN0_CDR_RESERVE, *PREG_RG_SSUSB_LN0_CDR_RESERVE;

typedef PACKING union
{
    PACKING struct
    {
        FIELD RG_SSUSB_LN0_TX250MCK_INVB : 1;
        FIELD RG_SSUSB_LN0_IDRV_ITAILOP_EN : 1;
        FIELD RG_SSUSB_LN0_IDRV_CALIB   : 6;
        FIELD RG_SSUSB_LN0_IDEM_BIAS    : 4;
        FIELD RG_SSUSB_LN0_TX_R50_FON   : 1;
        FIELD RG_SSUSB_LN0_TX_SR        : 3;
        FIELD RG_SSUSB_LN0_RXDET_RSEL   : 2;
        FIELD RG_SSUSB_LN0_RXDET_UPDN_FORCE : 1;
        FIELD RG_SSUSB_LN0_RXDET_UPDN_SEL : 1;
        FIELD RG_SSUSB_LN0_RXDET_VTHSEL_L : 2;
        FIELD RG_SSUSB_LN0_RXDET_VTHSEL_H : 2;
        FIELD RG_SSUSB_LN0_CKMON_EN     : 1;
        FIELD RG_SSUSB_LN0_TX_VLMON_EN  : 1;
        FIELD RG_SSUSB_LN0_TX_VLMON_SEL : 2;
        FIELD RG_SSUSB_LN0_CKMON_SEL    : 4;
    } Bits;
    UINT32 Raw;
} REG_RG_SSUSB_LN0_TX250MCK_INVB, *PREG_RG_SSUSB_LN0_TX250MCK_INVB;

typedef PACKING union
{
    PACKING struct
    {
        FIELD RG_SSUSB_LN0_TX_EIDLE_CM  : 4;
        FIELD RG_SSUSB_LN0_RXLBTX_EN    : 1;
        FIELD RG_SSUSB_LN0_TXLBRX_EN    : 1;
        FIELD rsv_6                     : 10;
        FIELD RG_SSUSB_LN0_RESERVE      : 16;
    } Bits;
    UINT32 Raw;
} REG_RG_SSUSB_LN0_TX_EIDLE_CM, *PREG_RG_SSUSB_LN0_TX_EIDLE_CM;

typedef PACKING union
{
    PACKING struct
    {
        FIELD RG_SSUSB_LN0_CDR_PD_DIV_BYPASS : 1;
        FIELD RG_SSUSB_LN0_CDR_PD_DIV_SEL : 1;
        FIELD RG_SSUSB_LN0_CDR_CPBIAS_SEL : 1;
        FIELD RG_SSUSB_LN0_CDR_OSCDET_EN : 1;
        FIELD RG_SSUSB_LN0_CDR_MONMUX   : 1;
        FIELD RG_SSUSB_LN0_CDR_RST_DLY  : 2;
        FIELD RG_SSUSB_LN0_CDR_RSTB_MANUAL : 1;
        FIELD RG_SSUSB_LN0_CDR_BYPASS   : 2;
        FIELD RG_SSUSB_LN0_CDR_PI_SLEW  : 2;
        FIELD RG_SSUSB_LN0_CDR_EPEN     : 1;
        FIELD RG_SSUSB_LN0_CDR_AUTOK_LOAD : 1;
        FIELD rsv_14                    : 1;
        FIELD RG_SSUSB_LN0_CDR_MONEN    : 1;
        FIELD RG_SSUSB_LN0_CDR_MONEN_DIG : 1;
        FIELD rsv_17                    : 3;
        FIELD RG_SSUSB_LN0_CDR_REGOD    : 2;
        FIELD RG_SSUSB_LN0_CDR_AUTOK_KS : 2;
        FIELD RG_SSUSB_LN0_CDR_AUTOK_KF : 2;
        FIELD RG_SSUSB_LN0_RX_DAC_EN    : 1;
        FIELD RG_SSUSB_LN0_RX_DAC_PWD   : 1;
        FIELD RG_SSUSB_LN0_EQ_CURSEL    : 1;
        FIELD rsv_29                    : 3;
    } Bits;
    UINT32 Raw;
} REG_RG_SSUSB_LN0_CDR_PD_DIV_BYPASS, *PREG_RG_SSUSB_LN0_CDR_PD_DIV_BYPASS;

typedef PACKING union
{
    PACKING struct
    {
        FIELD RG_SSUSB_LN0_RX_DAC_MUX   : 5;
        FIELD RG_SSUSB_LN0_RX_R2T_EN    : 1;
        FIELD RG_SSUSB_LN0_RX_T2R_EN    : 1;
        FIELD rsv_7                     : 1;
        FIELD RG_SSUSB_LN0_RX_50_LOWER  : 3;
        FIELD rsv_11                    : 1;
        FIELD RG_SSUSB_LN0_RX_50_TAR    : 2;
        FIELD rsv_14                    : 2;
        FIELD RG_SSUSB_LN0_RX_SW_CTRL   : 4;
        FIELD RG_PCIE_LN0_SIGDET_VTH    : 2;
        FIELD RG_PCIE_LN0_SIGDET_LPF    : 2;
        FIELD RG_PCIE_LN0_SIGDET_HF     : 2;
        FIELD RG_SSUSB_LN0_LFPS_CMPOUT_SEL : 1;
        FIELD RG_SSUSB_LN0_LFPS_SLCOUT_SEL : 1;
        FIELD RG_SSUSB_LN0_LFPS_LPF     : 2;
        FIELD RG_SSUSB_LN0_LFPS_MON_EN  : 1;
        FIELD rsv_31                    : 1;
    } Bits;
    UINT32 Raw;
} REG_RG_SSUSB_LN0_RX_DAC_MUX, *PREG_RG_SSUSB_LN0_RX_DAC_MUX;

typedef PACKING union
{
    PACKING struct
    {
        FIELD RG_SSUSB_LN0_RXAFE_DCMON_SEL : 4;
        FIELD RG_SSUSB_LN0_RX_P1_ENTRY_PASS : 1;
        FIELD RG_SSUSB_LN0_RX_PD_RST    : 1;
        FIELD RG_SSUSB_LN0_RX_PD_RST_PASS : 1;
        FIELD RG_SSUSB_LN0_RX_PD_PICAL_SWAP : 1;
        FIELD RG_SSUSB_LN0_RX_DAC_MEAS_EN : 1;
        FIELD rsv_9                     : 5;
        FIELD RG_PCIE_LN0_CRSDET_VTH    : 2;
        FIELD RG_PON_RX_CDR_DIVTDC      : 2;
        FIELD RG_PON_TX_DIVTDC          : 2;
        FIELD rsv_20                    : 12;
    } Bits;
    UINT32 Raw;
} REG_RG_SSUSB_LN0_RXAFE_DCMON_SEL, *PREG_RG_SSUSB_LN0_RXAFE_DCMON_SEL;

typedef PACKING union
{
    PACKING struct
    {
        FIELD RGS_SSUSB_LN0_RX_DEBUG_RESERVE : 8;
        FIELD rsv_8                     : 24;
    } Bits;
    UINT32 Raw;
} REG_RGS_SSUSB_LN0_RX_DEBUG_RESERVE, *PREG_RGS_SSUSB_LN0_RX_DEBUG_RESERVE;

// ----------------- pon_hsgmii_ana_csr  Grouping Definitions -------------------
// ----------------- pon_hsgmii_ana_csr Register Definition -------------------
#if 0
typedef volatile PACKING struct
{
    REG_RG_PON_TDC_RXCK_TEST_EN     RG_PON_TDC_RXCK_TEST_EN; // 3000
    REG_RG_SSUSB_BGR_EN             RG_SSUSB_BGR_EN;  // 3004
    REG_RG_PCIE_CLKDRV_OFFSET       RG_PCIE_CLKDRV_OFFSET; // 3008
    REG_RG_PON_PLL_RXREF_SEL        RG_PON_PLL_RXREF_SEL; // 300C
    REG_RG_SSUSB_PLL_KBAND_KFC      RG_SSUSB_PLL_KBAND_KFC; // 3010
    REG_RG_SSUSB_PLL_SDM_HREN       RG_SSUSB_PLL_SDM_HREN; // 3014
    REG_RG_SSUSB_LN0_CDR_RESERVE    RG_SSUSB_LN0_CDR_RESERVE; // 3018
    REG_RG_SSUSB_LN0_TX250MCK_INVB  RG_SSUSB_LN0_TX250MCK_INVB; // 301C
    REG_RG_SSUSB_LN0_TX_EIDLE_CM    RG_SSUSB_LN0_TX_EIDLE_CM; // 3020
    REG_RG_SSUSB_LN0_CDR_PD_DIV_BYPASS RG_SSUSB_LN0_CDR_PD_DIV_BYPASS; // 3024
    REG_RG_SSUSB_LN0_RX_DAC_MUX     RG_SSUSB_LN0_RX_DAC_MUX; // 3028
    REG_RG_SSUSB_LN0_RXAFE_DCMON_SEL RG_SSUSB_LN0_RXAFE_DCMON_SEL; // 302C
    REG_RGS_SSUSB_LN0_RX_DEBUG_RESERVE RGS_SSUSB_LN0_RX_DEBUG_RESERVE; // 3030
}pon_hsgmii_ana_csr_REGS, *Ppon_hsgmii_ana_csr_REGS;

#endif

// ---------- pon_hsgmii_ana_csr Enum Definitions      ----------
// ---------- pon_hsgmii_ana_csr C Macro Definitions   ----------
//extern Ppon_hsgmii_ana_csr_REGS g_pon_hsgmii_ana_csr_BASE;

//#define pon_hsgmii_ana_csr_BASE                                (g_pon_hsgmii_ana_csr_BASE)

#define _REG_RG_PON_TDC_RXCK_TEST_EN		0x3000
#define _REG_RG_SSUSB_BGR_EN		0x3004
#define _REG_RG_PCIE_CLKDRV_OFFSET		0x3008
#define _REG_RG_PON_PLL_RXREF_SEL		0x300C
#define _REG_RG_SSUSB_PLL_KBAND_KFC		0x3010
#define _REG_RG_SSUSB_PLL_SDM_HREN		0x3014
#define _REG_RG_SSUSB_LN0_CDR_RESERVE		0x3018
#define _REG_RG_SSUSB_LN0_TX250MCK_INVB		0x301C
#define _REG_RG_SSUSB_LN0_TX_EIDLE_CM		0x3020
#define _REG_RG_SSUSB_LN0_CDR_PD_DIV_BYPASS		0x3024
#define _REG_RG_SSUSB_LN0_RX_DAC_MUX		0x3028
#define _REG_RG_SSUSB_LN0_RXAFE_DCMON_SEL		0x302C
#define _REG_RGS_SSUSB_LN0_RX_DEBUG_RESERVE		0x3030

#endif


#define RG_PON_TDC_RXCK_TEST_EN_FLD_RG_PON_TDC_RESERVED        REG_FLD(8, 8)
#define RG_PON_TDC_RXCK_TEST_EN_FLD_RG_PON_TXPLL_REFIN_LPBK_CKEN REG_FLD(1, 6)
#define RG_PON_TDC_RXCK_TEST_EN_FLD_RG_PON_TDC_AUTOEN          REG_FLD(1, 5)
#define RG_PON_TDC_RXCK_TEST_EN_FLD_RG_PON_TDC_RXCKDIV_SEL     REG_FLD(2, 3)
#define RG_PON_TDC_RXCK_TEST_EN_FLD_RG_PON_TDC_TXCKDIV_SEL     REG_FLD(2, 1)
#define RG_PON_TDC_RXCK_TEST_EN_FLD_RG_PON_TDC_RXCK_TEST_EN    REG_FLD(1, 0)

#define RG_SSUSB_BGR_EN_FLD_RG_SSUSB_EXT_BIAS_SEL              REG_FLD(1, 31)
#define RG_SSUSB_BGR_EN_FLD_RG_SSUSB_INT_BIAS_SEL              REG_FLD(1, 30)
#define RG_SSUSB_BGR_EN_FLD_RG_SSUSB_BG_MONEN                  REG_FLD(1, 29)
#define RG_SSUSB_BGR_EN_FLD_RG_SSUSB_REF_EN                    REG_FLD(1, 28)
#define RG_SSUSB_BGR_EN_FLD_RG_SSUSB_VRT_VREF_SEL              REG_FLD(4, 24)
#define RG_SSUSB_BGR_EN_FLD_RG_SSUSB_IEXT_INTR_CTRL            REG_FLD(6, 18)
#define RG_SSUSB_BGR_EN_FLD_RG_SSUSB_MPX_SEL                   REG_FLD(8, 8)
#define RG_SSUSB_BGR_EN_FLD_RG_SSUSB_MPX_EN                    REG_FLD(1, 7)
#define RG_SSUSB_BGR_EN_FLD_RG_SSUSB_INTR_EN                   REG_FLD(1, 5)
#define RG_SSUSB_BGR_EN_FLD_RG_SSUSB_VRT_25M_EN                REG_FLD(1, 4)
#define RG_SSUSB_BGR_EN_FLD_RG_SSUSB_BG_DIV                    REG_FLD(2, 2)
#define RG_SSUSB_BGR_EN_FLD_RG_SSUSB_CHPEN                     REG_FLD(1, 1)
#define RG_SSUSB_BGR_EN_FLD_RG_SSUSB_BGR_EN                    REG_FLD(1, 0)

#define RG_PCIE_CLKDRV_OFFSET_FLD_RG_SSUSB_XTAL_TOP_RESERVE    REG_FLD(16, 16)
#define RG_PCIE_CLKDRV_OFFSET_FLD_RG_SSUSB_XTAL_HYS            REG_FLD(1, 13)
#define RG_PCIE_CLKDRV_OFFSET_FLD_RG_SSUSB_XTAL_MON_EN         REG_FLD(1, 12)
#define RG_PCIE_CLKDRV_OFFSET_FLD_RG_SSUSB_XTAL_TST_A2DCK_EN   REG_FLD(1, 11)
#define RG_PCIE_CLKDRV_OFFSET_FLD_RG_VUSB10_ON                 REG_FLD(1, 10)
#define RG_PCIE_CLKDRV_OFFSET_FLD_RG_PCIE_CLKDET_VTH           REG_FLD(2, 8)
#define RG_PCIE_CLKDRV_OFFSET_FLD_RG_PCIE_CLKDRV_AMP           REG_FLD(3, 4)
#define RG_PCIE_CLKDRV_OFFSET_FLD_RG_PCIE_CLKDRV_SLEW          REG_FLD(2, 2)
#define RG_PCIE_CLKDRV_OFFSET_FLD_RG_PCIE_CLKDRV_OFFSET        REG_FLD(2, 0)

#define RG_PON_PLL_RXREF_SEL_FLD_RG_SSUSB_PLL_RICO_SEL         REG_FLD(1, 30)
#define RG_PON_PLL_RXREF_SEL_FLD_RG_SSUSB_PLL_RST_DLY          REG_FLD(2, 28)
#define RG_PON_PLL_RXREF_SEL_FLD_RG_PCIE_CLKDRV_FORCE          REG_FLD(2, 26)
#define RG_PON_PLL_RXREF_SEL_FLD_RG_PCIE_CLKDRV_HZ             REG_FLD(1, 25)
#define RG_PON_PLL_RXREF_SEL_FLD_RG_PCIE_CLKDRV_IMPSEL         REG_FLD(5, 20)
#define RG_PON_PLL_RXREF_SEL_FLD_RG_PON_PLL_RXREF_SEL          REG_FLD(1, 19)

#define RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_SDM_MODE       REG_FLD(2, 29)
#define RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_SDM_ORD        REG_FLD(2, 27)
#define RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_SDM_DI_LS      REG_FLD(2, 25)
#define RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_SDM_DI_EN      REG_FLD(1, 24)
#define RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_IPLL_DIG_PWR_SEL REG_FLD(1, 23)
#define RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_DEBUG_SEL      REG_FLD(1, 22)
#define RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_RLP_SEL        REG_FLD(1, 21)
#define RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_TCL_EN         REG_FLD(1, 20)
#define RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_LDOVCO_VSEL    REG_FLD(2, 18)
#define RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_LDOLPF_VSEL    REG_FLD(2, 16)
#define RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_LDOCHP_VSEL    REG_FLD(2, 14)
#define RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_LDOPFD_VSEL    REG_FLD(2, 12)
#define RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_MON_LDO_SEL    REG_FLD(3, 9)
#define RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_MONREF_EN      REG_FLD(1, 8)
#define RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_MONVC_EN       REG_FLD(1, 7)
#define RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_MONCK_EN       REG_FLD(1, 6)
#define RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_KBAND_PREDIV   REG_FLD(2, 4)
#define RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_POSDIV         REG_FLD(2, 2)
#define RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_KBAND_KFC      REG_FLD(2, 0)

#define RG_SSUSB_PLL_SDM_HREN_FLD_RG_SSUSB_PLL_RESERVE         REG_FLD(8, 23)
#define RG_SSUSB_PLL_SDM_HREN_FLD_RG_SSUSB_PLL_SSC_DIR_DLY     REG_FLD(2, 21)
#define RG_SSUSB_PLL_SDM_HREN_FLD_RG_SSUSB_PLL_SSC_TRI_EN      REG_FLD(1, 20)
#define RG_SSUSB_PLL_SDM_HREN_FLD_RG_SSUSB_PLL_SSC_PH_INIT     REG_FLD(1, 19)
#define RG_SSUSB_PLL_SDM_HREN_FLD_RG_SSUSB_PLL_SSC_PRD         REG_FLD(16, 3)
#define RG_SSUSB_PLL_SDM_HREN_FLD_RG_SSUSB_PLL_SDM_IFM         REG_FLD(1, 2)
#define RG_SSUSB_PLL_SDM_HREN_FLD_RG_SSUSB_PLL_SDM_HREN        REG_FLD(2, 0)

#define RG_SSUSB_LN0_CDR_RESERVE_FLD_RG_SSUSB_LN0_LNMPX_SEL    REG_FLD(4, 28)
#define RG_SSUSB_LN0_CDR_RESERVE_FLD_RG_PCIE_LN0_RX_RESERVE    REG_FLD(8, 16)
#define RG_SSUSB_LN0_CDR_RESERVE_FLD_RG_SSUSB_LN0_RXAFE_RESERVE REG_FLD(8, 8)
#define RG_SSUSB_LN0_CDR_RESERVE_FLD_RG_SSUSB_LN0_CDR_RESERVE  REG_FLD(8, 0)

#define RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_CKMON_SEL  REG_FLD(4, 28)
#define RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_TX_VLMON_SEL REG_FLD(2, 26)
#define RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_TX_VLMON_EN REG_FLD(1, 25)
#define RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_CKMON_EN   REG_FLD(1, 24)
#define RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_RXDET_VTHSEL_H REG_FLD(2, 22)
#define RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_RXDET_VTHSEL_L REG_FLD(2, 20)
#define RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_RXDET_UPDN_SEL REG_FLD(1, 19)
#define RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_RXDET_UPDN_FORCE REG_FLD(1, 18)
#define RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_RXDET_RSEL REG_FLD(2, 16)
#define RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_TX_SR      REG_FLD(3, 13)
#define RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_TX_R50_FON REG_FLD(1, 12)
#define RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_IDEM_BIAS  REG_FLD(4, 8)
#define RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_IDRV_CALIB REG_FLD(6, 2)
#define RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_IDRV_ITAILOP_EN REG_FLD(1, 1)
#define RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_TX250MCK_INVB REG_FLD(1, 0)

#define RG_SSUSB_LN0_TX_EIDLE_CM_FLD_RG_SSUSB_LN0_RESERVE      REG_FLD(16, 16)
#define RG_SSUSB_LN0_TX_EIDLE_CM_FLD_RG_SSUSB_LN0_TXLBRX_EN    REG_FLD(1, 5)
#define RG_SSUSB_LN0_TX_EIDLE_CM_FLD_RG_SSUSB_LN0_RXLBTX_EN    REG_FLD(1, 4)
#define RG_SSUSB_LN0_TX_EIDLE_CM_FLD_RG_SSUSB_LN0_TX_EIDLE_CM  REG_FLD(4, 0)

#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_EQ_CURSEL REG_FLD(1, 28)
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_RX_DAC_PWD REG_FLD(1, 27)
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_RX_DAC_EN REG_FLD(1, 26)
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_AUTOK_KF REG_FLD(2, 24)
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_AUTOK_KS REG_FLD(2, 22)
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_REGOD REG_FLD(2, 20)
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_MONEN_DIG REG_FLD(1, 16)
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_MONEN REG_FLD(1, 15)
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_AUTOK_LOAD REG_FLD(1, 13)
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_EPEN REG_FLD(1, 12)
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_PI_SLEW REG_FLD(2, 10)
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_BYPASS REG_FLD(2, 8)
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_RSTB_MANUAL REG_FLD(1, 7)
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_RST_DLY REG_FLD(2, 5)
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_MONMUX REG_FLD(1, 4)
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_OSCDET_EN REG_FLD(1, 3)
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_CPBIAS_SEL REG_FLD(1, 2)
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_PD_DIV_SEL REG_FLD(1, 1)
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_PD_DIV_BYPASS REG_FLD(1, 0)

#define RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_LFPS_MON_EN   REG_FLD(1, 30)
#define RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_LFPS_LPF      REG_FLD(2, 28)
#define RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_LFPS_SLCOUT_SEL REG_FLD(1, 27)
#define RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_LFPS_CMPOUT_SEL REG_FLD(1, 26)
#define RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_PCIE_LN0_SIGDET_HF      REG_FLD(2, 24)
#define RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_PCIE_LN0_SIGDET_LPF     REG_FLD(2, 22)
#define RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_PCIE_LN0_SIGDET_VTH     REG_FLD(2, 20)
#define RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_RX_SW_CTRL    REG_FLD(4, 16)
#define RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_RX_50_TAR     REG_FLD(2, 12)
#define RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_RX_50_LOWER   REG_FLD(3, 8)
#define RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_RX_T2R_EN     REG_FLD(1, 6)
#define RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_RX_R2T_EN     REG_FLD(1, 5)
#define RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_RX_DAC_MUX    REG_FLD(5, 0)

#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_PON_TX_DIVTDC      REG_FLD(2, 18)
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_PON_RX_CDR_DIVTDC  REG_FLD(2, 16)
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_PCIE_LN0_CRSDET_VTH REG_FLD(2, 14)
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_SSUSB_LN0_RX_DAC_MEAS_EN REG_FLD(1, 8)
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_SSUSB_LN0_RX_PD_PICAL_SWAP REG_FLD(1, 7)
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_SSUSB_LN0_RX_PD_RST_PASS REG_FLD(1, 6)
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_SSUSB_LN0_RX_PD_RST REG_FLD(1, 5)
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_SSUSB_LN0_RX_P1_ENTRY_PASS REG_FLD(1, 4)
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_SSUSB_LN0_RXAFE_DCMON_SEL REG_FLD(4, 0)

#define RGS_SSUSB_LN0_RX_DEBUG_RESERVE_FLD_RGS_SSUSB_LN0_RX_DEBUG_RESERVE REG_FLD(8, 0)

#define RG_PON_TDC_RXCK_TEST_EN_GET_RG_PON_TDC_RESERVED(reg32) REG_FLD_GET(RG_PON_TDC_RXCK_TEST_EN_FLD_RG_PON_TDC_RESERVED, (reg32))
#define RG_PON_TDC_RXCK_TEST_EN_GET_RG_PON_TXPLL_REFIN_LPBK_CKEN(reg32) REG_FLD_GET(RG_PON_TDC_RXCK_TEST_EN_FLD_RG_PON_TXPLL_REFIN_LPBK_CKEN, (reg32))
#define RG_PON_TDC_RXCK_TEST_EN_GET_RG_PON_TDC_AUTOEN(reg32)   REG_FLD_GET(RG_PON_TDC_RXCK_TEST_EN_FLD_RG_PON_TDC_AUTOEN, (reg32))
#define RG_PON_TDC_RXCK_TEST_EN_GET_RG_PON_TDC_RXCKDIV_SEL(reg32) REG_FLD_GET(RG_PON_TDC_RXCK_TEST_EN_FLD_RG_PON_TDC_RXCKDIV_SEL, (reg32))
#define RG_PON_TDC_RXCK_TEST_EN_GET_RG_PON_TDC_TXCKDIV_SEL(reg32) REG_FLD_GET(RG_PON_TDC_RXCK_TEST_EN_FLD_RG_PON_TDC_TXCKDIV_SEL, (reg32))
#define RG_PON_TDC_RXCK_TEST_EN_GET_RG_PON_TDC_RXCK_TEST_EN(reg32) REG_FLD_GET(RG_PON_TDC_RXCK_TEST_EN_FLD_RG_PON_TDC_RXCK_TEST_EN, (reg32))

#define RG_SSUSB_BGR_EN_GET_RG_SSUSB_EXT_BIAS_SEL(reg32)       REG_FLD_GET(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_EXT_BIAS_SEL, (reg32))
#define RG_SSUSB_BGR_EN_GET_RG_SSUSB_INT_BIAS_SEL(reg32)       REG_FLD_GET(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_INT_BIAS_SEL, (reg32))
#define RG_SSUSB_BGR_EN_GET_RG_SSUSB_BG_MONEN(reg32)           REG_FLD_GET(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_BG_MONEN, (reg32))
#define RG_SSUSB_BGR_EN_GET_RG_SSUSB_REF_EN(reg32)             REG_FLD_GET(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_REF_EN, (reg32))
#define RG_SSUSB_BGR_EN_GET_RG_SSUSB_VRT_VREF_SEL(reg32)       REG_FLD_GET(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_VRT_VREF_SEL, (reg32))
#define RG_SSUSB_BGR_EN_GET_RG_SSUSB_IEXT_INTR_CTRL(reg32)     REG_FLD_GET(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_IEXT_INTR_CTRL, (reg32))
#define RG_SSUSB_BGR_EN_GET_RG_SSUSB_MPX_SEL(reg32)            REG_FLD_GET(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_MPX_SEL, (reg32))
#define RG_SSUSB_BGR_EN_GET_RG_SSUSB_MPX_EN(reg32)             REG_FLD_GET(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_MPX_EN, (reg32))
#define RG_SSUSB_BGR_EN_GET_RG_SSUSB_INTR_EN(reg32)            REG_FLD_GET(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_INTR_EN, (reg32))
#define RG_SSUSB_BGR_EN_GET_RG_SSUSB_VRT_25M_EN(reg32)         REG_FLD_GET(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_VRT_25M_EN, (reg32))
#define RG_SSUSB_BGR_EN_GET_RG_SSUSB_BG_DIV(reg32)             REG_FLD_GET(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_BG_DIV, (reg32))
#define RG_SSUSB_BGR_EN_GET_RG_SSUSB_CHPEN(reg32)              REG_FLD_GET(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_CHPEN, (reg32))
#define RG_SSUSB_BGR_EN_GET_RG_SSUSB_BGR_EN(reg32)             REG_FLD_GET(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_BGR_EN, (reg32))

#define RG_PCIE_CLKDRV_OFFSET_GET_RG_SSUSB_XTAL_TOP_RESERVE(reg32) REG_FLD_GET(RG_PCIE_CLKDRV_OFFSET_FLD_RG_SSUSB_XTAL_TOP_RESERVE, (reg32))
#define RG_PCIE_CLKDRV_OFFSET_GET_RG_SSUSB_XTAL_HYS(reg32)     REG_FLD_GET(RG_PCIE_CLKDRV_OFFSET_FLD_RG_SSUSB_XTAL_HYS, (reg32))
#define RG_PCIE_CLKDRV_OFFSET_GET_RG_SSUSB_XTAL_MON_EN(reg32)  REG_FLD_GET(RG_PCIE_CLKDRV_OFFSET_FLD_RG_SSUSB_XTAL_MON_EN, (reg32))
#define RG_PCIE_CLKDRV_OFFSET_GET_RG_SSUSB_XTAL_TST_A2DCK_EN(reg32) REG_FLD_GET(RG_PCIE_CLKDRV_OFFSET_FLD_RG_SSUSB_XTAL_TST_A2DCK_EN, (reg32))
#define RG_PCIE_CLKDRV_OFFSET_GET_RG_VUSB10_ON(reg32)          REG_FLD_GET(RG_PCIE_CLKDRV_OFFSET_FLD_RG_VUSB10_ON, (reg32))
#define RG_PCIE_CLKDRV_OFFSET_GET_RG_PCIE_CLKDET_VTH(reg32)    REG_FLD_GET(RG_PCIE_CLKDRV_OFFSET_FLD_RG_PCIE_CLKDET_VTH, (reg32))
#define RG_PCIE_CLKDRV_OFFSET_GET_RG_PCIE_CLKDRV_AMP(reg32)    REG_FLD_GET(RG_PCIE_CLKDRV_OFFSET_FLD_RG_PCIE_CLKDRV_AMP, (reg32))
#define RG_PCIE_CLKDRV_OFFSET_GET_RG_PCIE_CLKDRV_SLEW(reg32)   REG_FLD_GET(RG_PCIE_CLKDRV_OFFSET_FLD_RG_PCIE_CLKDRV_SLEW, (reg32))
#define RG_PCIE_CLKDRV_OFFSET_GET_RG_PCIE_CLKDRV_OFFSET(reg32) REG_FLD_GET(RG_PCIE_CLKDRV_OFFSET_FLD_RG_PCIE_CLKDRV_OFFSET, (reg32))

#define RG_PON_PLL_RXREF_SEL_GET_RG_SSUSB_PLL_RICO_SEL(reg32)  REG_FLD_GET(RG_PON_PLL_RXREF_SEL_FLD_RG_SSUSB_PLL_RICO_SEL, (reg32))
#define RG_PON_PLL_RXREF_SEL_GET_RG_SSUSB_PLL_RST_DLY(reg32)   REG_FLD_GET(RG_PON_PLL_RXREF_SEL_FLD_RG_SSUSB_PLL_RST_DLY, (reg32))
#define RG_PON_PLL_RXREF_SEL_GET_RG_PCIE_CLKDRV_FORCE(reg32)   REG_FLD_GET(RG_PON_PLL_RXREF_SEL_FLD_RG_PCIE_CLKDRV_FORCE, (reg32))
#define RG_PON_PLL_RXREF_SEL_GET_RG_PCIE_CLKDRV_HZ(reg32)      REG_FLD_GET(RG_PON_PLL_RXREF_SEL_FLD_RG_PCIE_CLKDRV_HZ, (reg32))
#define RG_PON_PLL_RXREF_SEL_GET_RG_PCIE_CLKDRV_IMPSEL(reg32)  REG_FLD_GET(RG_PON_PLL_RXREF_SEL_FLD_RG_PCIE_CLKDRV_IMPSEL, (reg32))
#define RG_PON_PLL_RXREF_SEL_GET_RG_PON_PLL_RXREF_SEL(reg32)   REG_FLD_GET(RG_PON_PLL_RXREF_SEL_FLD_RG_PON_PLL_RXREF_SEL, (reg32))

#define RG_SSUSB_PLL_KBAND_KFC_GET_RG_SSUSB_PLL_SDM_MODE(reg32) REG_FLD_GET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_SDM_MODE, (reg32))
#define RG_SSUSB_PLL_KBAND_KFC_GET_RG_SSUSB_PLL_SDM_ORD(reg32) REG_FLD_GET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_SDM_ORD, (reg32))
#define RG_SSUSB_PLL_KBAND_KFC_GET_RG_SSUSB_PLL_SDM_DI_LS(reg32) REG_FLD_GET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_SDM_DI_LS, (reg32))
#define RG_SSUSB_PLL_KBAND_KFC_GET_RG_SSUSB_PLL_SDM_DI_EN(reg32) REG_FLD_GET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_SDM_DI_EN, (reg32))
#define RG_SSUSB_PLL_KBAND_KFC_GET_RG_SSUSB_PLL_IPLL_DIG_PWR_SEL(reg32) REG_FLD_GET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_IPLL_DIG_PWR_SEL, (reg32))
#define RG_SSUSB_PLL_KBAND_KFC_GET_RG_SSUSB_PLL_DEBUG_SEL(reg32) REG_FLD_GET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_DEBUG_SEL, (reg32))
#define RG_SSUSB_PLL_KBAND_KFC_GET_RG_SSUSB_PLL_RLP_SEL(reg32) REG_FLD_GET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_RLP_SEL, (reg32))
#define RG_SSUSB_PLL_KBAND_KFC_GET_RG_SSUSB_PLL_TCL_EN(reg32)  REG_FLD_GET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_TCL_EN, (reg32))
#define RG_SSUSB_PLL_KBAND_KFC_GET_RG_SSUSB_PLL_LDOVCO_VSEL(reg32) REG_FLD_GET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_LDOVCO_VSEL, (reg32))
#define RG_SSUSB_PLL_KBAND_KFC_GET_RG_SSUSB_PLL_LDOLPF_VSEL(reg32) REG_FLD_GET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_LDOLPF_VSEL, (reg32))
#define RG_SSUSB_PLL_KBAND_KFC_GET_RG_SSUSB_PLL_LDOCHP_VSEL(reg32) REG_FLD_GET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_LDOCHP_VSEL, (reg32))
#define RG_SSUSB_PLL_KBAND_KFC_GET_RG_SSUSB_PLL_LDOPFD_VSEL(reg32) REG_FLD_GET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_LDOPFD_VSEL, (reg32))
#define RG_SSUSB_PLL_KBAND_KFC_GET_RG_SSUSB_PLL_MON_LDO_SEL(reg32) REG_FLD_GET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_MON_LDO_SEL, (reg32))
#define RG_SSUSB_PLL_KBAND_KFC_GET_RG_SSUSB_PLL_MONREF_EN(reg32) REG_FLD_GET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_MONREF_EN, (reg32))
#define RG_SSUSB_PLL_KBAND_KFC_GET_RG_SSUSB_PLL_MONVC_EN(reg32) REG_FLD_GET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_MONVC_EN, (reg32))
#define RG_SSUSB_PLL_KBAND_KFC_GET_RG_SSUSB_PLL_MONCK_EN(reg32) REG_FLD_GET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_MONCK_EN, (reg32))
#define RG_SSUSB_PLL_KBAND_KFC_GET_RG_SSUSB_PLL_KBAND_PREDIV(reg32) REG_FLD_GET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_KBAND_PREDIV, (reg32))
#define RG_SSUSB_PLL_KBAND_KFC_GET_RG_SSUSB_PLL_POSDIV(reg32)  REG_FLD_GET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_POSDIV, (reg32))
#define RG_SSUSB_PLL_KBAND_KFC_GET_RG_SSUSB_PLL_KBAND_KFC(reg32) REG_FLD_GET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_KBAND_KFC, (reg32))

#define RG_SSUSB_PLL_SDM_HREN_GET_RG_SSUSB_PLL_RESERVE(reg32)  REG_FLD_GET(RG_SSUSB_PLL_SDM_HREN_FLD_RG_SSUSB_PLL_RESERVE, (reg32))
#define RG_SSUSB_PLL_SDM_HREN_GET_RG_SSUSB_PLL_SSC_DIR_DLY(reg32) REG_FLD_GET(RG_SSUSB_PLL_SDM_HREN_FLD_RG_SSUSB_PLL_SSC_DIR_DLY, (reg32))
#define RG_SSUSB_PLL_SDM_HREN_GET_RG_SSUSB_PLL_SSC_TRI_EN(reg32) REG_FLD_GET(RG_SSUSB_PLL_SDM_HREN_FLD_RG_SSUSB_PLL_SSC_TRI_EN, (reg32))
#define RG_SSUSB_PLL_SDM_HREN_GET_RG_SSUSB_PLL_SSC_PH_INIT(reg32) REG_FLD_GET(RG_SSUSB_PLL_SDM_HREN_FLD_RG_SSUSB_PLL_SSC_PH_INIT, (reg32))
#define RG_SSUSB_PLL_SDM_HREN_GET_RG_SSUSB_PLL_SSC_PRD(reg32)  REG_FLD_GET(RG_SSUSB_PLL_SDM_HREN_FLD_RG_SSUSB_PLL_SSC_PRD, (reg32))
#define RG_SSUSB_PLL_SDM_HREN_GET_RG_SSUSB_PLL_SDM_IFM(reg32)  REG_FLD_GET(RG_SSUSB_PLL_SDM_HREN_FLD_RG_SSUSB_PLL_SDM_IFM, (reg32))
#define RG_SSUSB_PLL_SDM_HREN_GET_RG_SSUSB_PLL_SDM_HREN(reg32) REG_FLD_GET(RG_SSUSB_PLL_SDM_HREN_FLD_RG_SSUSB_PLL_SDM_HREN, (reg32))

#define RG_SSUSB_LN0_CDR_RESERVE_GET_RG_SSUSB_LN0_LNMPX_SEL(reg32) REG_FLD_GET(RG_SSUSB_LN0_CDR_RESERVE_FLD_RG_SSUSB_LN0_LNMPX_SEL, (reg32))
#define RG_SSUSB_LN0_CDR_RESERVE_GET_RG_PCIE_LN0_RX_RESERVE(reg32) REG_FLD_GET(RG_SSUSB_LN0_CDR_RESERVE_FLD_RG_PCIE_LN0_RX_RESERVE, (reg32))
#define RG_SSUSB_LN0_CDR_RESERVE_GET_RG_SSUSB_LN0_RXAFE_RESERVE(reg32) REG_FLD_GET(RG_SSUSB_LN0_CDR_RESERVE_FLD_RG_SSUSB_LN0_RXAFE_RESERVE, (reg32))
#define RG_SSUSB_LN0_CDR_RESERVE_GET_RG_SSUSB_LN0_CDR_RESERVE(reg32) REG_FLD_GET(RG_SSUSB_LN0_CDR_RESERVE_FLD_RG_SSUSB_LN0_CDR_RESERVE, (reg32))

#define RG_SSUSB_LN0_TX250MCK_INVB_GET_RG_SSUSB_LN0_CKMON_SEL(reg32) REG_FLD_GET(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_CKMON_SEL, (reg32))
#define RG_SSUSB_LN0_TX250MCK_INVB_GET_RG_SSUSB_LN0_TX_VLMON_SEL(reg32) REG_FLD_GET(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_TX_VLMON_SEL, (reg32))
#define RG_SSUSB_LN0_TX250MCK_INVB_GET_RG_SSUSB_LN0_TX_VLMON_EN(reg32) REG_FLD_GET(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_TX_VLMON_EN, (reg32))
#define RG_SSUSB_LN0_TX250MCK_INVB_GET_RG_SSUSB_LN0_CKMON_EN(reg32) REG_FLD_GET(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_CKMON_EN, (reg32))
#define RG_SSUSB_LN0_TX250MCK_INVB_GET_RG_SSUSB_LN0_RXDET_VTHSEL_H(reg32) REG_FLD_GET(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_RXDET_VTHSEL_H, (reg32))
#define RG_SSUSB_LN0_TX250MCK_INVB_GET_RG_SSUSB_LN0_RXDET_VTHSEL_L(reg32) REG_FLD_GET(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_RXDET_VTHSEL_L, (reg32))
#define RG_SSUSB_LN0_TX250MCK_INVB_GET_RG_SSUSB_LN0_RXDET_UPDN_SEL(reg32) REG_FLD_GET(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_RXDET_UPDN_SEL, (reg32))
#define RG_SSUSB_LN0_TX250MCK_INVB_GET_RG_SSUSB_LN0_RXDET_UPDN_FORCE(reg32) REG_FLD_GET(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_RXDET_UPDN_FORCE, (reg32))
#define RG_SSUSB_LN0_TX250MCK_INVB_GET_RG_SSUSB_LN0_RXDET_RSEL(reg32) REG_FLD_GET(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_RXDET_RSEL, (reg32))
#define RG_SSUSB_LN0_TX250MCK_INVB_GET_RG_SSUSB_LN0_TX_SR(reg32) REG_FLD_GET(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_TX_SR, (reg32))
#define RG_SSUSB_LN0_TX250MCK_INVB_GET_RG_SSUSB_LN0_TX_R50_FON(reg32) REG_FLD_GET(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_TX_R50_FON, (reg32))
#define RG_SSUSB_LN0_TX250MCK_INVB_GET_RG_SSUSB_LN0_IDEM_BIAS(reg32) REG_FLD_GET(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_IDEM_BIAS, (reg32))
#define RG_SSUSB_LN0_TX250MCK_INVB_GET_RG_SSUSB_LN0_IDRV_CALIB(reg32) REG_FLD_GET(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_IDRV_CALIB, (reg32))
#define RG_SSUSB_LN0_TX250MCK_INVB_GET_RG_SSUSB_LN0_IDRV_ITAILOP_EN(reg32) REG_FLD_GET(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_IDRV_ITAILOP_EN, (reg32))
#define RG_SSUSB_LN0_TX250MCK_INVB_GET_RG_SSUSB_LN0_TX250MCK_INVB(reg32) REG_FLD_GET(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_TX250MCK_INVB, (reg32))

#define RG_SSUSB_LN0_TX_EIDLE_CM_GET_RG_SSUSB_LN0_RESERVE(reg32) REG_FLD_GET(RG_SSUSB_LN0_TX_EIDLE_CM_FLD_RG_SSUSB_LN0_RESERVE, (reg32))
#define RG_SSUSB_LN0_TX_EIDLE_CM_GET_RG_SSUSB_LN0_TXLBRX_EN(reg32) REG_FLD_GET(RG_SSUSB_LN0_TX_EIDLE_CM_FLD_RG_SSUSB_LN0_TXLBRX_EN, (reg32))
#define RG_SSUSB_LN0_TX_EIDLE_CM_GET_RG_SSUSB_LN0_RXLBTX_EN(reg32) REG_FLD_GET(RG_SSUSB_LN0_TX_EIDLE_CM_FLD_RG_SSUSB_LN0_RXLBTX_EN, (reg32))
#define RG_SSUSB_LN0_TX_EIDLE_CM_GET_RG_SSUSB_LN0_TX_EIDLE_CM(reg32) REG_FLD_GET(RG_SSUSB_LN0_TX_EIDLE_CM_FLD_RG_SSUSB_LN0_TX_EIDLE_CM, (reg32))

#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_GET_RG_SSUSB_LN0_EQ_CURSEL(reg32) REG_FLD_GET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_EQ_CURSEL, (reg32))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_GET_RG_SSUSB_LN0_RX_DAC_PWD(reg32) REG_FLD_GET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_RX_DAC_PWD, (reg32))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_GET_RG_SSUSB_LN0_RX_DAC_EN(reg32) REG_FLD_GET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_RX_DAC_EN, (reg32))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_GET_RG_SSUSB_LN0_CDR_AUTOK_KF(reg32) REG_FLD_GET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_AUTOK_KF, (reg32))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_GET_RG_SSUSB_LN0_CDR_AUTOK_KS(reg32) REG_FLD_GET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_AUTOK_KS, (reg32))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_GET_RG_SSUSB_LN0_CDR_REGOD(reg32) REG_FLD_GET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_REGOD, (reg32))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_GET_RG_SSUSB_LN0_CDR_MONEN_DIG(reg32) REG_FLD_GET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_MONEN_DIG, (reg32))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_GET_RG_SSUSB_LN0_CDR_MONEN(reg32) REG_FLD_GET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_MONEN, (reg32))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_GET_RG_SSUSB_LN0_CDR_AUTOK_LOAD(reg32) REG_FLD_GET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_AUTOK_LOAD, (reg32))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_GET_RG_SSUSB_LN0_CDR_EPEN(reg32) REG_FLD_GET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_EPEN, (reg32))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_GET_RG_SSUSB_LN0_CDR_PI_SLEW(reg32) REG_FLD_GET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_PI_SLEW, (reg32))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_GET_RG_SSUSB_LN0_CDR_BYPASS(reg32) REG_FLD_GET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_BYPASS, (reg32))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_GET_RG_SSUSB_LN0_CDR_RSTB_MANUAL(reg32) REG_FLD_GET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_RSTB_MANUAL, (reg32))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_GET_RG_SSUSB_LN0_CDR_RST_DLY(reg32) REG_FLD_GET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_RST_DLY, (reg32))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_GET_RG_SSUSB_LN0_CDR_MONMUX(reg32) REG_FLD_GET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_MONMUX, (reg32))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_GET_RG_SSUSB_LN0_CDR_OSCDET_EN(reg32) REG_FLD_GET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_OSCDET_EN, (reg32))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_GET_RG_SSUSB_LN0_CDR_CPBIAS_SEL(reg32) REG_FLD_GET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_CPBIAS_SEL, (reg32))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_GET_RG_SSUSB_LN0_CDR_PD_DIV_SEL(reg32) REG_FLD_GET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_PD_DIV_SEL, (reg32))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_GET_RG_SSUSB_LN0_CDR_PD_DIV_BYPASS(reg32) REG_FLD_GET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_PD_DIV_BYPASS, (reg32))

#define RG_SSUSB_LN0_RX_DAC_MUX_GET_RG_SSUSB_LN0_LFPS_MON_EN(reg32) REG_FLD_GET(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_LFPS_MON_EN, (reg32))
#define RG_SSUSB_LN0_RX_DAC_MUX_GET_RG_SSUSB_LN0_LFPS_LPF(reg32) REG_FLD_GET(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_LFPS_LPF, (reg32))
#define RG_SSUSB_LN0_RX_DAC_MUX_GET_RG_SSUSB_LN0_LFPS_SLCOUT_SEL(reg32) REG_FLD_GET(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_LFPS_SLCOUT_SEL, (reg32))
#define RG_SSUSB_LN0_RX_DAC_MUX_GET_RG_SSUSB_LN0_LFPS_CMPOUT_SEL(reg32) REG_FLD_GET(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_LFPS_CMPOUT_SEL, (reg32))
#define RG_SSUSB_LN0_RX_DAC_MUX_GET_RG_PCIE_LN0_SIGDET_HF(reg32) REG_FLD_GET(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_PCIE_LN0_SIGDET_HF, (reg32))
#define RG_SSUSB_LN0_RX_DAC_MUX_GET_RG_PCIE_LN0_SIGDET_LPF(reg32) REG_FLD_GET(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_PCIE_LN0_SIGDET_LPF, (reg32))
#define RG_SSUSB_LN0_RX_DAC_MUX_GET_RG_PCIE_LN0_SIGDET_VTH(reg32) REG_FLD_GET(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_PCIE_LN0_SIGDET_VTH, (reg32))
#define RG_SSUSB_LN0_RX_DAC_MUX_GET_RG_SSUSB_LN0_RX_SW_CTRL(reg32) REG_FLD_GET(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_RX_SW_CTRL, (reg32))
#define RG_SSUSB_LN0_RX_DAC_MUX_GET_RG_SSUSB_LN0_RX_50_TAR(reg32) REG_FLD_GET(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_RX_50_TAR, (reg32))
#define RG_SSUSB_LN0_RX_DAC_MUX_GET_RG_SSUSB_LN0_RX_50_LOWER(reg32) REG_FLD_GET(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_RX_50_LOWER, (reg32))
#define RG_SSUSB_LN0_RX_DAC_MUX_GET_RG_SSUSB_LN0_RX_T2R_EN(reg32) REG_FLD_GET(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_RX_T2R_EN, (reg32))
#define RG_SSUSB_LN0_RX_DAC_MUX_GET_RG_SSUSB_LN0_RX_R2T_EN(reg32) REG_FLD_GET(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_RX_R2T_EN, (reg32))
#define RG_SSUSB_LN0_RX_DAC_MUX_GET_RG_SSUSB_LN0_RX_DAC_MUX(reg32) REG_FLD_GET(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_RX_DAC_MUX, (reg32))

#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_GET_RG_PON_TX_DIVTDC(reg32) REG_FLD_GET(RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_PON_TX_DIVTDC, (reg32))
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_GET_RG_PON_RX_CDR_DIVTDC(reg32) REG_FLD_GET(RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_PON_RX_CDR_DIVTDC, (reg32))
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_GET_RG_PCIE_LN0_CRSDET_VTH(reg32) REG_FLD_GET(RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_PCIE_LN0_CRSDET_VTH, (reg32))
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_GET_RG_SSUSB_LN0_RX_DAC_MEAS_EN(reg32) REG_FLD_GET(RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_SSUSB_LN0_RX_DAC_MEAS_EN, (reg32))
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_GET_RG_SSUSB_LN0_RX_PD_PICAL_SWAP(reg32) REG_FLD_GET(RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_SSUSB_LN0_RX_PD_PICAL_SWAP, (reg32))
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_GET_RG_SSUSB_LN0_RX_PD_RST_PASS(reg32) REG_FLD_GET(RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_SSUSB_LN0_RX_PD_RST_PASS, (reg32))
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_GET_RG_SSUSB_LN0_RX_PD_RST(reg32) REG_FLD_GET(RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_SSUSB_LN0_RX_PD_RST, (reg32))
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_GET_RG_SSUSB_LN0_RX_P1_ENTRY_PASS(reg32) REG_FLD_GET(RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_SSUSB_LN0_RX_P1_ENTRY_PASS, (reg32))
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_GET_RG_SSUSB_LN0_RXAFE_DCMON_SEL(reg32) REG_FLD_GET(RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_SSUSB_LN0_RXAFE_DCMON_SEL, (reg32))

#define RGS_SSUSB_LN0_RX_DEBUG_RESERVE_GET_RGS_SSUSB_LN0_RX_DEBUG_RESERVE(reg32) REG_FLD_GET(RGS_SSUSB_LN0_RX_DEBUG_RESERVE_FLD_RGS_SSUSB_LN0_RX_DEBUG_RESERVE, (reg32))

#define RG_PON_TDC_RXCK_TEST_EN_SET_RG_PON_TDC_RESERVED(reg32, val) REG_FLD_SET(RG_PON_TDC_RXCK_TEST_EN_FLD_RG_PON_TDC_RESERVED, (reg32), (val))
#define RG_PON_TDC_RXCK_TEST_EN_SET_RG_PON_TXPLL_REFIN_LPBK_CKEN(reg32, val) REG_FLD_SET(RG_PON_TDC_RXCK_TEST_EN_FLD_RG_PON_TXPLL_REFIN_LPBK_CKEN, (reg32), (val))
#define RG_PON_TDC_RXCK_TEST_EN_SET_RG_PON_TDC_AUTOEN(reg32, val) REG_FLD_SET(RG_PON_TDC_RXCK_TEST_EN_FLD_RG_PON_TDC_AUTOEN, (reg32), (val))
#define RG_PON_TDC_RXCK_TEST_EN_SET_RG_PON_TDC_RXCKDIV_SEL(reg32, val) REG_FLD_SET(RG_PON_TDC_RXCK_TEST_EN_FLD_RG_PON_TDC_RXCKDIV_SEL, (reg32), (val))
#define RG_PON_TDC_RXCK_TEST_EN_SET_RG_PON_TDC_TXCKDIV_SEL(reg32, val) REG_FLD_SET(RG_PON_TDC_RXCK_TEST_EN_FLD_RG_PON_TDC_TXCKDIV_SEL, (reg32), (val))
#define RG_PON_TDC_RXCK_TEST_EN_SET_RG_PON_TDC_RXCK_TEST_EN(reg32, val) REG_FLD_SET(RG_PON_TDC_RXCK_TEST_EN_FLD_RG_PON_TDC_RXCK_TEST_EN, (reg32), (val))

#define RG_SSUSB_BGR_EN_SET_RG_SSUSB_EXT_BIAS_SEL(reg32, val)  REG_FLD_SET(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_EXT_BIAS_SEL, (reg32), (val))
#define RG_SSUSB_BGR_EN_SET_RG_SSUSB_INT_BIAS_SEL(reg32, val)  REG_FLD_SET(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_INT_BIAS_SEL, (reg32), (val))
#define RG_SSUSB_BGR_EN_SET_RG_SSUSB_BG_MONEN(reg32, val)      REG_FLD_SET(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_BG_MONEN, (reg32), (val))
#define RG_SSUSB_BGR_EN_SET_RG_SSUSB_REF_EN(reg32, val)        REG_FLD_SET(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_REF_EN, (reg32), (val))
#define RG_SSUSB_BGR_EN_SET_RG_SSUSB_VRT_VREF_SEL(reg32, val)  REG_FLD_SET(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_VRT_VREF_SEL, (reg32), (val))
#define RG_SSUSB_BGR_EN_SET_RG_SSUSB_IEXT_INTR_CTRL(reg32, val) REG_FLD_SET(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_IEXT_INTR_CTRL, (reg32), (val))
#define RG_SSUSB_BGR_EN_SET_RG_SSUSB_MPX_SEL(reg32, val)       REG_FLD_SET(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_MPX_SEL, (reg32), (val))
#define RG_SSUSB_BGR_EN_SET_RG_SSUSB_MPX_EN(reg32, val)        REG_FLD_SET(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_MPX_EN, (reg32), (val))
#define RG_SSUSB_BGR_EN_SET_RG_SSUSB_INTR_EN(reg32, val)       REG_FLD_SET(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_INTR_EN, (reg32), (val))
#define RG_SSUSB_BGR_EN_SET_RG_SSUSB_VRT_25M_EN(reg32, val)    REG_FLD_SET(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_VRT_25M_EN, (reg32), (val))
#define RG_SSUSB_BGR_EN_SET_RG_SSUSB_BG_DIV(reg32, val)        REG_FLD_SET(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_BG_DIV, (reg32), (val))
#define RG_SSUSB_BGR_EN_SET_RG_SSUSB_CHPEN(reg32, val)         REG_FLD_SET(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_CHPEN, (reg32), (val))
#define RG_SSUSB_BGR_EN_SET_RG_SSUSB_BGR_EN(reg32, val)        REG_FLD_SET(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_BGR_EN, (reg32), (val))

#define RG_PCIE_CLKDRV_OFFSET_SET_RG_SSUSB_XTAL_TOP_RESERVE(reg32, val) REG_FLD_SET(RG_PCIE_CLKDRV_OFFSET_FLD_RG_SSUSB_XTAL_TOP_RESERVE, (reg32), (val))
#define RG_PCIE_CLKDRV_OFFSET_SET_RG_SSUSB_XTAL_HYS(reg32, val) REG_FLD_SET(RG_PCIE_CLKDRV_OFFSET_FLD_RG_SSUSB_XTAL_HYS, (reg32), (val))
#define RG_PCIE_CLKDRV_OFFSET_SET_RG_SSUSB_XTAL_MON_EN(reg32, val) REG_FLD_SET(RG_PCIE_CLKDRV_OFFSET_FLD_RG_SSUSB_XTAL_MON_EN, (reg32), (val))
#define RG_PCIE_CLKDRV_OFFSET_SET_RG_SSUSB_XTAL_TST_A2DCK_EN(reg32, val) REG_FLD_SET(RG_PCIE_CLKDRV_OFFSET_FLD_RG_SSUSB_XTAL_TST_A2DCK_EN, (reg32), (val))
#define RG_PCIE_CLKDRV_OFFSET_SET_RG_VUSB10_ON(reg32, val)     REG_FLD_SET(RG_PCIE_CLKDRV_OFFSET_FLD_RG_VUSB10_ON, (reg32), (val))
#define RG_PCIE_CLKDRV_OFFSET_SET_RG_PCIE_CLKDET_VTH(reg32, val) REG_FLD_SET(RG_PCIE_CLKDRV_OFFSET_FLD_RG_PCIE_CLKDET_VTH, (reg32), (val))
#define RG_PCIE_CLKDRV_OFFSET_SET_RG_PCIE_CLKDRV_AMP(reg32, val) REG_FLD_SET(RG_PCIE_CLKDRV_OFFSET_FLD_RG_PCIE_CLKDRV_AMP, (reg32), (val))
#define RG_PCIE_CLKDRV_OFFSET_SET_RG_PCIE_CLKDRV_SLEW(reg32, val) REG_FLD_SET(RG_PCIE_CLKDRV_OFFSET_FLD_RG_PCIE_CLKDRV_SLEW, (reg32), (val))
#define RG_PCIE_CLKDRV_OFFSET_SET_RG_PCIE_CLKDRV_OFFSET(reg32, val) REG_FLD_SET(RG_PCIE_CLKDRV_OFFSET_FLD_RG_PCIE_CLKDRV_OFFSET, (reg32), (val))

#define RG_PON_PLL_RXREF_SEL_SET_RG_SSUSB_PLL_RICO_SEL(reg32, val) REG_FLD_SET(RG_PON_PLL_RXREF_SEL_FLD_RG_SSUSB_PLL_RICO_SEL, (reg32), (val))
#define RG_PON_PLL_RXREF_SEL_SET_RG_SSUSB_PLL_RST_DLY(reg32, val) REG_FLD_SET(RG_PON_PLL_RXREF_SEL_FLD_RG_SSUSB_PLL_RST_DLY, (reg32), (val))
#define RG_PON_PLL_RXREF_SEL_SET_RG_PCIE_CLKDRV_FORCE(reg32, val) REG_FLD_SET(RG_PON_PLL_RXREF_SEL_FLD_RG_PCIE_CLKDRV_FORCE, (reg32), (val))
#define RG_PON_PLL_RXREF_SEL_SET_RG_PCIE_CLKDRV_HZ(reg32, val) REG_FLD_SET(RG_PON_PLL_RXREF_SEL_FLD_RG_PCIE_CLKDRV_HZ, (reg32), (val))
#define RG_PON_PLL_RXREF_SEL_SET_RG_PCIE_CLKDRV_IMPSEL(reg32, val) REG_FLD_SET(RG_PON_PLL_RXREF_SEL_FLD_RG_PCIE_CLKDRV_IMPSEL, (reg32), (val))
#define RG_PON_PLL_RXREF_SEL_SET_RG_PON_PLL_RXREF_SEL(reg32, val) REG_FLD_SET(RG_PON_PLL_RXREF_SEL_FLD_RG_PON_PLL_RXREF_SEL, (reg32), (val))

#define RG_SSUSB_PLL_KBAND_KFC_SET_RG_SSUSB_PLL_SDM_MODE(reg32, val) REG_FLD_SET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_SDM_MODE, (reg32), (val))
#define RG_SSUSB_PLL_KBAND_KFC_SET_RG_SSUSB_PLL_SDM_ORD(reg32, val) REG_FLD_SET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_SDM_ORD, (reg32), (val))
#define RG_SSUSB_PLL_KBAND_KFC_SET_RG_SSUSB_PLL_SDM_DI_LS(reg32, val) REG_FLD_SET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_SDM_DI_LS, (reg32), (val))
#define RG_SSUSB_PLL_KBAND_KFC_SET_RG_SSUSB_PLL_SDM_DI_EN(reg32, val) REG_FLD_SET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_SDM_DI_EN, (reg32), (val))
#define RG_SSUSB_PLL_KBAND_KFC_SET_RG_SSUSB_PLL_IPLL_DIG_PWR_SEL(reg32, val) REG_FLD_SET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_IPLL_DIG_PWR_SEL, (reg32), (val))
#define RG_SSUSB_PLL_KBAND_KFC_SET_RG_SSUSB_PLL_DEBUG_SEL(reg32, val) REG_FLD_SET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_DEBUG_SEL, (reg32), (val))
#define RG_SSUSB_PLL_KBAND_KFC_SET_RG_SSUSB_PLL_RLP_SEL(reg32, val) REG_FLD_SET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_RLP_SEL, (reg32), (val))
#define RG_SSUSB_PLL_KBAND_KFC_SET_RG_SSUSB_PLL_TCL_EN(reg32, val) REG_FLD_SET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_TCL_EN, (reg32), (val))
#define RG_SSUSB_PLL_KBAND_KFC_SET_RG_SSUSB_PLL_LDOVCO_VSEL(reg32, val) REG_FLD_SET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_LDOVCO_VSEL, (reg32), (val))
#define RG_SSUSB_PLL_KBAND_KFC_SET_RG_SSUSB_PLL_LDOLPF_VSEL(reg32, val) REG_FLD_SET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_LDOLPF_VSEL, (reg32), (val))
#define RG_SSUSB_PLL_KBAND_KFC_SET_RG_SSUSB_PLL_LDOCHP_VSEL(reg32, val) REG_FLD_SET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_LDOCHP_VSEL, (reg32), (val))
#define RG_SSUSB_PLL_KBAND_KFC_SET_RG_SSUSB_PLL_LDOPFD_VSEL(reg32, val) REG_FLD_SET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_LDOPFD_VSEL, (reg32), (val))
#define RG_SSUSB_PLL_KBAND_KFC_SET_RG_SSUSB_PLL_MON_LDO_SEL(reg32, val) REG_FLD_SET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_MON_LDO_SEL, (reg32), (val))
#define RG_SSUSB_PLL_KBAND_KFC_SET_RG_SSUSB_PLL_MONREF_EN(reg32, val) REG_FLD_SET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_MONREF_EN, (reg32), (val))
#define RG_SSUSB_PLL_KBAND_KFC_SET_RG_SSUSB_PLL_MONVC_EN(reg32, val) REG_FLD_SET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_MONVC_EN, (reg32), (val))
#define RG_SSUSB_PLL_KBAND_KFC_SET_RG_SSUSB_PLL_MONCK_EN(reg32, val) REG_FLD_SET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_MONCK_EN, (reg32), (val))
#define RG_SSUSB_PLL_KBAND_KFC_SET_RG_SSUSB_PLL_KBAND_PREDIV(reg32, val) REG_FLD_SET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_KBAND_PREDIV, (reg32), (val))
#define RG_SSUSB_PLL_KBAND_KFC_SET_RG_SSUSB_PLL_POSDIV(reg32, val) REG_FLD_SET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_POSDIV, (reg32), (val))
#define RG_SSUSB_PLL_KBAND_KFC_SET_RG_SSUSB_PLL_KBAND_KFC(reg32, val) REG_FLD_SET(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_KBAND_KFC, (reg32), (val))

#define RG_SSUSB_PLL_SDM_HREN_SET_RG_SSUSB_PLL_RESERVE(reg32, val) REG_FLD_SET(RG_SSUSB_PLL_SDM_HREN_FLD_RG_SSUSB_PLL_RESERVE, (reg32), (val))
#define RG_SSUSB_PLL_SDM_HREN_SET_RG_SSUSB_PLL_SSC_DIR_DLY(reg32, val) REG_FLD_SET(RG_SSUSB_PLL_SDM_HREN_FLD_RG_SSUSB_PLL_SSC_DIR_DLY, (reg32), (val))
#define RG_SSUSB_PLL_SDM_HREN_SET_RG_SSUSB_PLL_SSC_TRI_EN(reg32, val) REG_FLD_SET(RG_SSUSB_PLL_SDM_HREN_FLD_RG_SSUSB_PLL_SSC_TRI_EN, (reg32), (val))
#define RG_SSUSB_PLL_SDM_HREN_SET_RG_SSUSB_PLL_SSC_PH_INIT(reg32, val) REG_FLD_SET(RG_SSUSB_PLL_SDM_HREN_FLD_RG_SSUSB_PLL_SSC_PH_INIT, (reg32), (val))
#define RG_SSUSB_PLL_SDM_HREN_SET_RG_SSUSB_PLL_SSC_PRD(reg32, val) REG_FLD_SET(RG_SSUSB_PLL_SDM_HREN_FLD_RG_SSUSB_PLL_SSC_PRD, (reg32), (val))
#define RG_SSUSB_PLL_SDM_HREN_SET_RG_SSUSB_PLL_SDM_IFM(reg32, val) REG_FLD_SET(RG_SSUSB_PLL_SDM_HREN_FLD_RG_SSUSB_PLL_SDM_IFM, (reg32), (val))
#define RG_SSUSB_PLL_SDM_HREN_SET_RG_SSUSB_PLL_SDM_HREN(reg32, val) REG_FLD_SET(RG_SSUSB_PLL_SDM_HREN_FLD_RG_SSUSB_PLL_SDM_HREN, (reg32), (val))

#define RG_SSUSB_LN0_CDR_RESERVE_SET_RG_SSUSB_LN0_LNMPX_SEL(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_CDR_RESERVE_FLD_RG_SSUSB_LN0_LNMPX_SEL, (reg32), (val))
#define RG_SSUSB_LN0_CDR_RESERVE_SET_RG_PCIE_LN0_RX_RESERVE(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_CDR_RESERVE_FLD_RG_PCIE_LN0_RX_RESERVE, (reg32), (val))
#define RG_SSUSB_LN0_CDR_RESERVE_SET_RG_SSUSB_LN0_RXAFE_RESERVE(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_CDR_RESERVE_FLD_RG_SSUSB_LN0_RXAFE_RESERVE, (reg32), (val))
#define RG_SSUSB_LN0_CDR_RESERVE_SET_RG_SSUSB_LN0_CDR_RESERVE(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_CDR_RESERVE_FLD_RG_SSUSB_LN0_CDR_RESERVE, (reg32), (val))

#define RG_SSUSB_LN0_TX250MCK_INVB_SET_RG_SSUSB_LN0_CKMON_SEL(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_CKMON_SEL, (reg32), (val))
#define RG_SSUSB_LN0_TX250MCK_INVB_SET_RG_SSUSB_LN0_TX_VLMON_SEL(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_TX_VLMON_SEL, (reg32), (val))
#define RG_SSUSB_LN0_TX250MCK_INVB_SET_RG_SSUSB_LN0_TX_VLMON_EN(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_TX_VLMON_EN, (reg32), (val))
#define RG_SSUSB_LN0_TX250MCK_INVB_SET_RG_SSUSB_LN0_CKMON_EN(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_CKMON_EN, (reg32), (val))
#define RG_SSUSB_LN0_TX250MCK_INVB_SET_RG_SSUSB_LN0_RXDET_VTHSEL_H(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_RXDET_VTHSEL_H, (reg32), (val))
#define RG_SSUSB_LN0_TX250MCK_INVB_SET_RG_SSUSB_LN0_RXDET_VTHSEL_L(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_RXDET_VTHSEL_L, (reg32), (val))
#define RG_SSUSB_LN0_TX250MCK_INVB_SET_RG_SSUSB_LN0_RXDET_UPDN_SEL(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_RXDET_UPDN_SEL, (reg32), (val))
#define RG_SSUSB_LN0_TX250MCK_INVB_SET_RG_SSUSB_LN0_RXDET_UPDN_FORCE(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_RXDET_UPDN_FORCE, (reg32), (val))
#define RG_SSUSB_LN0_TX250MCK_INVB_SET_RG_SSUSB_LN0_RXDET_RSEL(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_RXDET_RSEL, (reg32), (val))
#define RG_SSUSB_LN0_TX250MCK_INVB_SET_RG_SSUSB_LN0_TX_SR(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_TX_SR, (reg32), (val))
#define RG_SSUSB_LN0_TX250MCK_INVB_SET_RG_SSUSB_LN0_TX_R50_FON(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_TX_R50_FON, (reg32), (val))
#define RG_SSUSB_LN0_TX250MCK_INVB_SET_RG_SSUSB_LN0_IDEM_BIAS(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_IDEM_BIAS, (reg32), (val))
#define RG_SSUSB_LN0_TX250MCK_INVB_SET_RG_SSUSB_LN0_IDRV_CALIB(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_IDRV_CALIB, (reg32), (val))
#define RG_SSUSB_LN0_TX250MCK_INVB_SET_RG_SSUSB_LN0_IDRV_ITAILOP_EN(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_IDRV_ITAILOP_EN, (reg32), (val))
#define RG_SSUSB_LN0_TX250MCK_INVB_SET_RG_SSUSB_LN0_TX250MCK_INVB(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_TX250MCK_INVB, (reg32), (val))

#define RG_SSUSB_LN0_TX_EIDLE_CM_SET_RG_SSUSB_LN0_RESERVE(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_TX_EIDLE_CM_FLD_RG_SSUSB_LN0_RESERVE, (reg32), (val))
#define RG_SSUSB_LN0_TX_EIDLE_CM_SET_RG_SSUSB_LN0_TXLBRX_EN(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_TX_EIDLE_CM_FLD_RG_SSUSB_LN0_TXLBRX_EN, (reg32), (val))
#define RG_SSUSB_LN0_TX_EIDLE_CM_SET_RG_SSUSB_LN0_RXLBTX_EN(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_TX_EIDLE_CM_FLD_RG_SSUSB_LN0_RXLBTX_EN, (reg32), (val))
#define RG_SSUSB_LN0_TX_EIDLE_CM_SET_RG_SSUSB_LN0_TX_EIDLE_CM(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_TX_EIDLE_CM_FLD_RG_SSUSB_LN0_TX_EIDLE_CM, (reg32), (val))

#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_SET_RG_SSUSB_LN0_EQ_CURSEL(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_EQ_CURSEL, (reg32), (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_SET_RG_SSUSB_LN0_RX_DAC_PWD(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_RX_DAC_PWD, (reg32), (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_SET_RG_SSUSB_LN0_RX_DAC_EN(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_RX_DAC_EN, (reg32), (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_SET_RG_SSUSB_LN0_CDR_AUTOK_KF(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_AUTOK_KF, (reg32), (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_SET_RG_SSUSB_LN0_CDR_AUTOK_KS(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_AUTOK_KS, (reg32), (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_SET_RG_SSUSB_LN0_CDR_REGOD(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_REGOD, (reg32), (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_SET_RG_SSUSB_LN0_CDR_MONEN_DIG(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_MONEN_DIG, (reg32), (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_SET_RG_SSUSB_LN0_CDR_MONEN(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_MONEN, (reg32), (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_SET_RG_SSUSB_LN0_CDR_AUTOK_LOAD(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_AUTOK_LOAD, (reg32), (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_SET_RG_SSUSB_LN0_CDR_EPEN(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_EPEN, (reg32), (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_SET_RG_SSUSB_LN0_CDR_PI_SLEW(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_PI_SLEW, (reg32), (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_SET_RG_SSUSB_LN0_CDR_BYPASS(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_BYPASS, (reg32), (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_SET_RG_SSUSB_LN0_CDR_RSTB_MANUAL(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_RSTB_MANUAL, (reg32), (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_SET_RG_SSUSB_LN0_CDR_RST_DLY(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_RST_DLY, (reg32), (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_SET_RG_SSUSB_LN0_CDR_MONMUX(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_MONMUX, (reg32), (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_SET_RG_SSUSB_LN0_CDR_OSCDET_EN(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_OSCDET_EN, (reg32), (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_SET_RG_SSUSB_LN0_CDR_CPBIAS_SEL(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_CPBIAS_SEL, (reg32), (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_SET_RG_SSUSB_LN0_CDR_PD_DIV_SEL(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_PD_DIV_SEL, (reg32), (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_SET_RG_SSUSB_LN0_CDR_PD_DIV_BYPASS(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_PD_DIV_BYPASS, (reg32), (val))

#define RG_SSUSB_LN0_RX_DAC_MUX_SET_RG_SSUSB_LN0_LFPS_MON_EN(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_LFPS_MON_EN, (reg32), (val))
#define RG_SSUSB_LN0_RX_DAC_MUX_SET_RG_SSUSB_LN0_LFPS_LPF(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_LFPS_LPF, (reg32), (val))
#define RG_SSUSB_LN0_RX_DAC_MUX_SET_RG_SSUSB_LN0_LFPS_SLCOUT_SEL(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_LFPS_SLCOUT_SEL, (reg32), (val))
#define RG_SSUSB_LN0_RX_DAC_MUX_SET_RG_SSUSB_LN0_LFPS_CMPOUT_SEL(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_LFPS_CMPOUT_SEL, (reg32), (val))
#define RG_SSUSB_LN0_RX_DAC_MUX_SET_RG_PCIE_LN0_SIGDET_HF(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_PCIE_LN0_SIGDET_HF, (reg32), (val))
#define RG_SSUSB_LN0_RX_DAC_MUX_SET_RG_PCIE_LN0_SIGDET_LPF(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_PCIE_LN0_SIGDET_LPF, (reg32), (val))
#define RG_SSUSB_LN0_RX_DAC_MUX_SET_RG_PCIE_LN0_SIGDET_VTH(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_PCIE_LN0_SIGDET_VTH, (reg32), (val))
#define RG_SSUSB_LN0_RX_DAC_MUX_SET_RG_SSUSB_LN0_RX_SW_CTRL(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_RX_SW_CTRL, (reg32), (val))
#define RG_SSUSB_LN0_RX_DAC_MUX_SET_RG_SSUSB_LN0_RX_50_TAR(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_RX_50_TAR, (reg32), (val))
#define RG_SSUSB_LN0_RX_DAC_MUX_SET_RG_SSUSB_LN0_RX_50_LOWER(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_RX_50_LOWER, (reg32), (val))
#define RG_SSUSB_LN0_RX_DAC_MUX_SET_RG_SSUSB_LN0_RX_T2R_EN(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_RX_T2R_EN, (reg32), (val))
#define RG_SSUSB_LN0_RX_DAC_MUX_SET_RG_SSUSB_LN0_RX_R2T_EN(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_RX_R2T_EN, (reg32), (val))
#define RG_SSUSB_LN0_RX_DAC_MUX_SET_RG_SSUSB_LN0_RX_DAC_MUX(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_RX_DAC_MUX, (reg32), (val))

#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_SET_RG_PON_TX_DIVTDC(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_PON_TX_DIVTDC, (reg32), (val))
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_SET_RG_PON_RX_CDR_DIVTDC(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_PON_RX_CDR_DIVTDC, (reg32), (val))
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_SET_RG_PCIE_LN0_CRSDET_VTH(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_PCIE_LN0_CRSDET_VTH, (reg32), (val))
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_SET_RG_SSUSB_LN0_RX_DAC_MEAS_EN(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_SSUSB_LN0_RX_DAC_MEAS_EN, (reg32), (val))
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_SET_RG_SSUSB_LN0_RX_PD_PICAL_SWAP(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_SSUSB_LN0_RX_PD_PICAL_SWAP, (reg32), (val))
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_SET_RG_SSUSB_LN0_RX_PD_RST_PASS(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_SSUSB_LN0_RX_PD_RST_PASS, (reg32), (val))
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_SET_RG_SSUSB_LN0_RX_PD_RST(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_SSUSB_LN0_RX_PD_RST, (reg32), (val))
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_SET_RG_SSUSB_LN0_RX_P1_ENTRY_PASS(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_SSUSB_LN0_RX_P1_ENTRY_PASS, (reg32), (val))
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_SET_RG_SSUSB_LN0_RXAFE_DCMON_SEL(reg32, val) REG_FLD_SET(RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_SSUSB_LN0_RXAFE_DCMON_SEL, (reg32), (val))

#define RGS_SSUSB_LN0_RX_DEBUG_RESERVE_SET_RGS_SSUSB_LN0_RX_DEBUG_RESERVE(reg32, val) REG_FLD_SET(RGS_SSUSB_LN0_RX_DEBUG_RESERVE_FLD_RGS_SSUSB_LN0_RX_DEBUG_RESERVE, (reg32), (val))

#define RG_PON_TDC_RXCK_TEST_EN_VAL_RG_PON_TDC_RESERVED(val)   REG_FLD_VAL(RG_PON_TDC_RXCK_TEST_EN_FLD_RG_PON_TDC_RESERVED, (val))
#define RG_PON_TDC_RXCK_TEST_EN_VAL_RG_PON_TXPLL_REFIN_LPBK_CKEN(val) REG_FLD_VAL(RG_PON_TDC_RXCK_TEST_EN_FLD_RG_PON_TXPLL_REFIN_LPBK_CKEN, (val))
#define RG_PON_TDC_RXCK_TEST_EN_VAL_RG_PON_TDC_AUTOEN(val)     REG_FLD_VAL(RG_PON_TDC_RXCK_TEST_EN_FLD_RG_PON_TDC_AUTOEN, (val))
#define RG_PON_TDC_RXCK_TEST_EN_VAL_RG_PON_TDC_RXCKDIV_SEL(val) REG_FLD_VAL(RG_PON_TDC_RXCK_TEST_EN_FLD_RG_PON_TDC_RXCKDIV_SEL, (val))
#define RG_PON_TDC_RXCK_TEST_EN_VAL_RG_PON_TDC_TXCKDIV_SEL(val) REG_FLD_VAL(RG_PON_TDC_RXCK_TEST_EN_FLD_RG_PON_TDC_TXCKDIV_SEL, (val))
#define RG_PON_TDC_RXCK_TEST_EN_VAL_RG_PON_TDC_RXCK_TEST_EN(val) REG_FLD_VAL(RG_PON_TDC_RXCK_TEST_EN_FLD_RG_PON_TDC_RXCK_TEST_EN, (val))

#define RG_SSUSB_BGR_EN_VAL_RG_SSUSB_EXT_BIAS_SEL(val)         REG_FLD_VAL(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_EXT_BIAS_SEL, (val))
#define RG_SSUSB_BGR_EN_VAL_RG_SSUSB_INT_BIAS_SEL(val)         REG_FLD_VAL(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_INT_BIAS_SEL, (val))
#define RG_SSUSB_BGR_EN_VAL_RG_SSUSB_BG_MONEN(val)             REG_FLD_VAL(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_BG_MONEN, (val))
#define RG_SSUSB_BGR_EN_VAL_RG_SSUSB_REF_EN(val)               REG_FLD_VAL(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_REF_EN, (val))
#define RG_SSUSB_BGR_EN_VAL_RG_SSUSB_VRT_VREF_SEL(val)         REG_FLD_VAL(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_VRT_VREF_SEL, (val))
#define RG_SSUSB_BGR_EN_VAL_RG_SSUSB_IEXT_INTR_CTRL(val)       REG_FLD_VAL(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_IEXT_INTR_CTRL, (val))
#define RG_SSUSB_BGR_EN_VAL_RG_SSUSB_MPX_SEL(val)              REG_FLD_VAL(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_MPX_SEL, (val))
#define RG_SSUSB_BGR_EN_VAL_RG_SSUSB_MPX_EN(val)               REG_FLD_VAL(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_MPX_EN, (val))
#define RG_SSUSB_BGR_EN_VAL_RG_SSUSB_INTR_EN(val)              REG_FLD_VAL(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_INTR_EN, (val))
#define RG_SSUSB_BGR_EN_VAL_RG_SSUSB_VRT_25M_EN(val)           REG_FLD_VAL(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_VRT_25M_EN, (val))
#define RG_SSUSB_BGR_EN_VAL_RG_SSUSB_BG_DIV(val)               REG_FLD_VAL(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_BG_DIV, (val))
#define RG_SSUSB_BGR_EN_VAL_RG_SSUSB_CHPEN(val)                REG_FLD_VAL(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_CHPEN, (val))
#define RG_SSUSB_BGR_EN_VAL_RG_SSUSB_BGR_EN(val)               REG_FLD_VAL(RG_SSUSB_BGR_EN_FLD_RG_SSUSB_BGR_EN, (val))

#define RG_PCIE_CLKDRV_OFFSET_VAL_RG_SSUSB_XTAL_TOP_RESERVE(val) REG_FLD_VAL(RG_PCIE_CLKDRV_OFFSET_FLD_RG_SSUSB_XTAL_TOP_RESERVE, (val))
#define RG_PCIE_CLKDRV_OFFSET_VAL_RG_SSUSB_XTAL_HYS(val)       REG_FLD_VAL(RG_PCIE_CLKDRV_OFFSET_FLD_RG_SSUSB_XTAL_HYS, (val))
#define RG_PCIE_CLKDRV_OFFSET_VAL_RG_SSUSB_XTAL_MON_EN(val)    REG_FLD_VAL(RG_PCIE_CLKDRV_OFFSET_FLD_RG_SSUSB_XTAL_MON_EN, (val))
#define RG_PCIE_CLKDRV_OFFSET_VAL_RG_SSUSB_XTAL_TST_A2DCK_EN(val) REG_FLD_VAL(RG_PCIE_CLKDRV_OFFSET_FLD_RG_SSUSB_XTAL_TST_A2DCK_EN, (val))
#define RG_PCIE_CLKDRV_OFFSET_VAL_RG_VUSB10_ON(val)            REG_FLD_VAL(RG_PCIE_CLKDRV_OFFSET_FLD_RG_VUSB10_ON, (val))
#define RG_PCIE_CLKDRV_OFFSET_VAL_RG_PCIE_CLKDET_VTH(val)      REG_FLD_VAL(RG_PCIE_CLKDRV_OFFSET_FLD_RG_PCIE_CLKDET_VTH, (val))
#define RG_PCIE_CLKDRV_OFFSET_VAL_RG_PCIE_CLKDRV_AMP(val)      REG_FLD_VAL(RG_PCIE_CLKDRV_OFFSET_FLD_RG_PCIE_CLKDRV_AMP, (val))
#define RG_PCIE_CLKDRV_OFFSET_VAL_RG_PCIE_CLKDRV_SLEW(val)     REG_FLD_VAL(RG_PCIE_CLKDRV_OFFSET_FLD_RG_PCIE_CLKDRV_SLEW, (val))
#define RG_PCIE_CLKDRV_OFFSET_VAL_RG_PCIE_CLKDRV_OFFSET(val)   REG_FLD_VAL(RG_PCIE_CLKDRV_OFFSET_FLD_RG_PCIE_CLKDRV_OFFSET, (val))

#define RG_PON_PLL_RXREF_SEL_VAL_RG_SSUSB_PLL_RICO_SEL(val)    REG_FLD_VAL(RG_PON_PLL_RXREF_SEL_FLD_RG_SSUSB_PLL_RICO_SEL, (val))
#define RG_PON_PLL_RXREF_SEL_VAL_RG_SSUSB_PLL_RST_DLY(val)     REG_FLD_VAL(RG_PON_PLL_RXREF_SEL_FLD_RG_SSUSB_PLL_RST_DLY, (val))
#define RG_PON_PLL_RXREF_SEL_VAL_RG_PCIE_CLKDRV_FORCE(val)     REG_FLD_VAL(RG_PON_PLL_RXREF_SEL_FLD_RG_PCIE_CLKDRV_FORCE, (val))
#define RG_PON_PLL_RXREF_SEL_VAL_RG_PCIE_CLKDRV_HZ(val)        REG_FLD_VAL(RG_PON_PLL_RXREF_SEL_FLD_RG_PCIE_CLKDRV_HZ, (val))
#define RG_PON_PLL_RXREF_SEL_VAL_RG_PCIE_CLKDRV_IMPSEL(val)    REG_FLD_VAL(RG_PON_PLL_RXREF_SEL_FLD_RG_PCIE_CLKDRV_IMPSEL, (val))
#define RG_PON_PLL_RXREF_SEL_VAL_RG_PON_PLL_RXREF_SEL(val)     REG_FLD_VAL(RG_PON_PLL_RXREF_SEL_FLD_RG_PON_PLL_RXREF_SEL, (val))

#define RG_SSUSB_PLL_KBAND_KFC_VAL_RG_SSUSB_PLL_SDM_MODE(val)  REG_FLD_VAL(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_SDM_MODE, (val))
#define RG_SSUSB_PLL_KBAND_KFC_VAL_RG_SSUSB_PLL_SDM_ORD(val)   REG_FLD_VAL(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_SDM_ORD, (val))
#define RG_SSUSB_PLL_KBAND_KFC_VAL_RG_SSUSB_PLL_SDM_DI_LS(val) REG_FLD_VAL(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_SDM_DI_LS, (val))
#define RG_SSUSB_PLL_KBAND_KFC_VAL_RG_SSUSB_PLL_SDM_DI_EN(val) REG_FLD_VAL(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_SDM_DI_EN, (val))
#define RG_SSUSB_PLL_KBAND_KFC_VAL_RG_SSUSB_PLL_IPLL_DIG_PWR_SEL(val) REG_FLD_VAL(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_IPLL_DIG_PWR_SEL, (val))
#define RG_SSUSB_PLL_KBAND_KFC_VAL_RG_SSUSB_PLL_DEBUG_SEL(val) REG_FLD_VAL(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_DEBUG_SEL, (val))
#define RG_SSUSB_PLL_KBAND_KFC_VAL_RG_SSUSB_PLL_RLP_SEL(val)   REG_FLD_VAL(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_RLP_SEL, (val))
#define RG_SSUSB_PLL_KBAND_KFC_VAL_RG_SSUSB_PLL_TCL_EN(val)    REG_FLD_VAL(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_TCL_EN, (val))
#define RG_SSUSB_PLL_KBAND_KFC_VAL_RG_SSUSB_PLL_LDOVCO_VSEL(val) REG_FLD_VAL(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_LDOVCO_VSEL, (val))
#define RG_SSUSB_PLL_KBAND_KFC_VAL_RG_SSUSB_PLL_LDOLPF_VSEL(val) REG_FLD_VAL(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_LDOLPF_VSEL, (val))
#define RG_SSUSB_PLL_KBAND_KFC_VAL_RG_SSUSB_PLL_LDOCHP_VSEL(val) REG_FLD_VAL(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_LDOCHP_VSEL, (val))
#define RG_SSUSB_PLL_KBAND_KFC_VAL_RG_SSUSB_PLL_LDOPFD_VSEL(val) REG_FLD_VAL(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_LDOPFD_VSEL, (val))
#define RG_SSUSB_PLL_KBAND_KFC_VAL_RG_SSUSB_PLL_MON_LDO_SEL(val) REG_FLD_VAL(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_MON_LDO_SEL, (val))
#define RG_SSUSB_PLL_KBAND_KFC_VAL_RG_SSUSB_PLL_MONREF_EN(val) REG_FLD_VAL(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_MONREF_EN, (val))
#define RG_SSUSB_PLL_KBAND_KFC_VAL_RG_SSUSB_PLL_MONVC_EN(val)  REG_FLD_VAL(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_MONVC_EN, (val))
#define RG_SSUSB_PLL_KBAND_KFC_VAL_RG_SSUSB_PLL_MONCK_EN(val)  REG_FLD_VAL(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_MONCK_EN, (val))
#define RG_SSUSB_PLL_KBAND_KFC_VAL_RG_SSUSB_PLL_KBAND_PREDIV(val) REG_FLD_VAL(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_KBAND_PREDIV, (val))
#define RG_SSUSB_PLL_KBAND_KFC_VAL_RG_SSUSB_PLL_POSDIV(val)    REG_FLD_VAL(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_POSDIV, (val))
#define RG_SSUSB_PLL_KBAND_KFC_VAL_RG_SSUSB_PLL_KBAND_KFC(val) REG_FLD_VAL(RG_SSUSB_PLL_KBAND_KFC_FLD_RG_SSUSB_PLL_KBAND_KFC, (val))

#define RG_SSUSB_PLL_SDM_HREN_VAL_RG_SSUSB_PLL_RESERVE(val)    REG_FLD_VAL(RG_SSUSB_PLL_SDM_HREN_FLD_RG_SSUSB_PLL_RESERVE, (val))
#define RG_SSUSB_PLL_SDM_HREN_VAL_RG_SSUSB_PLL_SSC_DIR_DLY(val) REG_FLD_VAL(RG_SSUSB_PLL_SDM_HREN_FLD_RG_SSUSB_PLL_SSC_DIR_DLY, (val))
#define RG_SSUSB_PLL_SDM_HREN_VAL_RG_SSUSB_PLL_SSC_TRI_EN(val) REG_FLD_VAL(RG_SSUSB_PLL_SDM_HREN_FLD_RG_SSUSB_PLL_SSC_TRI_EN, (val))
#define RG_SSUSB_PLL_SDM_HREN_VAL_RG_SSUSB_PLL_SSC_PH_INIT(val) REG_FLD_VAL(RG_SSUSB_PLL_SDM_HREN_FLD_RG_SSUSB_PLL_SSC_PH_INIT, (val))
#define RG_SSUSB_PLL_SDM_HREN_VAL_RG_SSUSB_PLL_SSC_PRD(val)    REG_FLD_VAL(RG_SSUSB_PLL_SDM_HREN_FLD_RG_SSUSB_PLL_SSC_PRD, (val))
#define RG_SSUSB_PLL_SDM_HREN_VAL_RG_SSUSB_PLL_SDM_IFM(val)    REG_FLD_VAL(RG_SSUSB_PLL_SDM_HREN_FLD_RG_SSUSB_PLL_SDM_IFM, (val))
#define RG_SSUSB_PLL_SDM_HREN_VAL_RG_SSUSB_PLL_SDM_HREN(val)   REG_FLD_VAL(RG_SSUSB_PLL_SDM_HREN_FLD_RG_SSUSB_PLL_SDM_HREN, (val))

#define RG_SSUSB_LN0_CDR_RESERVE_VAL_RG_SSUSB_LN0_LNMPX_SEL(val) REG_FLD_VAL(RG_SSUSB_LN0_CDR_RESERVE_FLD_RG_SSUSB_LN0_LNMPX_SEL, (val))
#define RG_SSUSB_LN0_CDR_RESERVE_VAL_RG_PCIE_LN0_RX_RESERVE(val) REG_FLD_VAL(RG_SSUSB_LN0_CDR_RESERVE_FLD_RG_PCIE_LN0_RX_RESERVE, (val))
#define RG_SSUSB_LN0_CDR_RESERVE_VAL_RG_SSUSB_LN0_RXAFE_RESERVE(val) REG_FLD_VAL(RG_SSUSB_LN0_CDR_RESERVE_FLD_RG_SSUSB_LN0_RXAFE_RESERVE, (val))
#define RG_SSUSB_LN0_CDR_RESERVE_VAL_RG_SSUSB_LN0_CDR_RESERVE(val) REG_FLD_VAL(RG_SSUSB_LN0_CDR_RESERVE_FLD_RG_SSUSB_LN0_CDR_RESERVE, (val))

#define RG_SSUSB_LN0_TX250MCK_INVB_VAL_RG_SSUSB_LN0_CKMON_SEL(val) REG_FLD_VAL(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_CKMON_SEL, (val))
#define RG_SSUSB_LN0_TX250MCK_INVB_VAL_RG_SSUSB_LN0_TX_VLMON_SEL(val) REG_FLD_VAL(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_TX_VLMON_SEL, (val))
#define RG_SSUSB_LN0_TX250MCK_INVB_VAL_RG_SSUSB_LN0_TX_VLMON_EN(val) REG_FLD_VAL(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_TX_VLMON_EN, (val))
#define RG_SSUSB_LN0_TX250MCK_INVB_VAL_RG_SSUSB_LN0_CKMON_EN(val) REG_FLD_VAL(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_CKMON_EN, (val))
#define RG_SSUSB_LN0_TX250MCK_INVB_VAL_RG_SSUSB_LN0_RXDET_VTHSEL_H(val) REG_FLD_VAL(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_RXDET_VTHSEL_H, (val))
#define RG_SSUSB_LN0_TX250MCK_INVB_VAL_RG_SSUSB_LN0_RXDET_VTHSEL_L(val) REG_FLD_VAL(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_RXDET_VTHSEL_L, (val))
#define RG_SSUSB_LN0_TX250MCK_INVB_VAL_RG_SSUSB_LN0_RXDET_UPDN_SEL(val) REG_FLD_VAL(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_RXDET_UPDN_SEL, (val))
#define RG_SSUSB_LN0_TX250MCK_INVB_VAL_RG_SSUSB_LN0_RXDET_UPDN_FORCE(val) REG_FLD_VAL(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_RXDET_UPDN_FORCE, (val))
#define RG_SSUSB_LN0_TX250MCK_INVB_VAL_RG_SSUSB_LN0_RXDET_RSEL(val) REG_FLD_VAL(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_RXDET_RSEL, (val))
#define RG_SSUSB_LN0_TX250MCK_INVB_VAL_RG_SSUSB_LN0_TX_SR(val) REG_FLD_VAL(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_TX_SR, (val))
#define RG_SSUSB_LN0_TX250MCK_INVB_VAL_RG_SSUSB_LN0_TX_R50_FON(val) REG_FLD_VAL(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_TX_R50_FON, (val))
#define RG_SSUSB_LN0_TX250MCK_INVB_VAL_RG_SSUSB_LN0_IDEM_BIAS(val) REG_FLD_VAL(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_IDEM_BIAS, (val))
#define RG_SSUSB_LN0_TX250MCK_INVB_VAL_RG_SSUSB_LN0_IDRV_CALIB(val) REG_FLD_VAL(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_IDRV_CALIB, (val))
#define RG_SSUSB_LN0_TX250MCK_INVB_VAL_RG_SSUSB_LN0_IDRV_ITAILOP_EN(val) REG_FLD_VAL(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_IDRV_ITAILOP_EN, (val))
#define RG_SSUSB_LN0_TX250MCK_INVB_VAL_RG_SSUSB_LN0_TX250MCK_INVB(val) REG_FLD_VAL(RG_SSUSB_LN0_TX250MCK_INVB_FLD_RG_SSUSB_LN0_TX250MCK_INVB, (val))

#define RG_SSUSB_LN0_TX_EIDLE_CM_VAL_RG_SSUSB_LN0_RESERVE(val) REG_FLD_VAL(RG_SSUSB_LN0_TX_EIDLE_CM_FLD_RG_SSUSB_LN0_RESERVE, (val))
#define RG_SSUSB_LN0_TX_EIDLE_CM_VAL_RG_SSUSB_LN0_TXLBRX_EN(val) REG_FLD_VAL(RG_SSUSB_LN0_TX_EIDLE_CM_FLD_RG_SSUSB_LN0_TXLBRX_EN, (val))
#define RG_SSUSB_LN0_TX_EIDLE_CM_VAL_RG_SSUSB_LN0_RXLBTX_EN(val) REG_FLD_VAL(RG_SSUSB_LN0_TX_EIDLE_CM_FLD_RG_SSUSB_LN0_RXLBTX_EN, (val))
#define RG_SSUSB_LN0_TX_EIDLE_CM_VAL_RG_SSUSB_LN0_TX_EIDLE_CM(val) REG_FLD_VAL(RG_SSUSB_LN0_TX_EIDLE_CM_FLD_RG_SSUSB_LN0_TX_EIDLE_CM, (val))

#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_VAL_RG_SSUSB_LN0_EQ_CURSEL(val) REG_FLD_VAL(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_EQ_CURSEL, (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_VAL_RG_SSUSB_LN0_RX_DAC_PWD(val) REG_FLD_VAL(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_RX_DAC_PWD, (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_VAL_RG_SSUSB_LN0_RX_DAC_EN(val) REG_FLD_VAL(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_RX_DAC_EN, (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_VAL_RG_SSUSB_LN0_CDR_AUTOK_KF(val) REG_FLD_VAL(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_AUTOK_KF, (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_VAL_RG_SSUSB_LN0_CDR_AUTOK_KS(val) REG_FLD_VAL(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_AUTOK_KS, (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_VAL_RG_SSUSB_LN0_CDR_REGOD(val) REG_FLD_VAL(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_REGOD, (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_VAL_RG_SSUSB_LN0_CDR_MONEN_DIG(val) REG_FLD_VAL(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_MONEN_DIG, (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_VAL_RG_SSUSB_LN0_CDR_MONEN(val) REG_FLD_VAL(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_MONEN, (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_VAL_RG_SSUSB_LN0_CDR_AUTOK_LOAD(val) REG_FLD_VAL(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_AUTOK_LOAD, (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_VAL_RG_SSUSB_LN0_CDR_EPEN(val) REG_FLD_VAL(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_EPEN, (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_VAL_RG_SSUSB_LN0_CDR_PI_SLEW(val) REG_FLD_VAL(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_PI_SLEW, (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_VAL_RG_SSUSB_LN0_CDR_BYPASS(val) REG_FLD_VAL(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_BYPASS, (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_VAL_RG_SSUSB_LN0_CDR_RSTB_MANUAL(val) REG_FLD_VAL(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_RSTB_MANUAL, (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_VAL_RG_SSUSB_LN0_CDR_RST_DLY(val) REG_FLD_VAL(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_RST_DLY, (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_VAL_RG_SSUSB_LN0_CDR_MONMUX(val) REG_FLD_VAL(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_MONMUX, (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_VAL_RG_SSUSB_LN0_CDR_OSCDET_EN(val) REG_FLD_VAL(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_OSCDET_EN, (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_VAL_RG_SSUSB_LN0_CDR_CPBIAS_SEL(val) REG_FLD_VAL(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_CPBIAS_SEL, (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_VAL_RG_SSUSB_LN0_CDR_PD_DIV_SEL(val) REG_FLD_VAL(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_PD_DIV_SEL, (val))
#define RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_VAL_RG_SSUSB_LN0_CDR_PD_DIV_BYPASS(val) REG_FLD_VAL(RG_SSUSB_LN0_CDR_PD_DIV_BYPASS_FLD_RG_SSUSB_LN0_CDR_PD_DIV_BYPASS, (val))

#define RG_SSUSB_LN0_RX_DAC_MUX_VAL_RG_SSUSB_LN0_LFPS_MON_EN(val) REG_FLD_VAL(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_LFPS_MON_EN, (val))
#define RG_SSUSB_LN0_RX_DAC_MUX_VAL_RG_SSUSB_LN0_LFPS_LPF(val) REG_FLD_VAL(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_LFPS_LPF, (val))
#define RG_SSUSB_LN0_RX_DAC_MUX_VAL_RG_SSUSB_LN0_LFPS_SLCOUT_SEL(val) REG_FLD_VAL(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_LFPS_SLCOUT_SEL, (val))
#define RG_SSUSB_LN0_RX_DAC_MUX_VAL_RG_SSUSB_LN0_LFPS_CMPOUT_SEL(val) REG_FLD_VAL(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_LFPS_CMPOUT_SEL, (val))
#define RG_SSUSB_LN0_RX_DAC_MUX_VAL_RG_PCIE_LN0_SIGDET_HF(val) REG_FLD_VAL(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_PCIE_LN0_SIGDET_HF, (val))
#define RG_SSUSB_LN0_RX_DAC_MUX_VAL_RG_PCIE_LN0_SIGDET_LPF(val) REG_FLD_VAL(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_PCIE_LN0_SIGDET_LPF, (val))
#define RG_SSUSB_LN0_RX_DAC_MUX_VAL_RG_PCIE_LN0_SIGDET_VTH(val) REG_FLD_VAL(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_PCIE_LN0_SIGDET_VTH, (val))
#define RG_SSUSB_LN0_RX_DAC_MUX_VAL_RG_SSUSB_LN0_RX_SW_CTRL(val) REG_FLD_VAL(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_RX_SW_CTRL, (val))
#define RG_SSUSB_LN0_RX_DAC_MUX_VAL_RG_SSUSB_LN0_RX_50_TAR(val) REG_FLD_VAL(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_RX_50_TAR, (val))
#define RG_SSUSB_LN0_RX_DAC_MUX_VAL_RG_SSUSB_LN0_RX_50_LOWER(val) REG_FLD_VAL(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_RX_50_LOWER, (val))
#define RG_SSUSB_LN0_RX_DAC_MUX_VAL_RG_SSUSB_LN0_RX_T2R_EN(val) REG_FLD_VAL(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_RX_T2R_EN, (val))
#define RG_SSUSB_LN0_RX_DAC_MUX_VAL_RG_SSUSB_LN0_RX_R2T_EN(val) REG_FLD_VAL(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_RX_R2T_EN, (val))
#define RG_SSUSB_LN0_RX_DAC_MUX_VAL_RG_SSUSB_LN0_RX_DAC_MUX(val) REG_FLD_VAL(RG_SSUSB_LN0_RX_DAC_MUX_FLD_RG_SSUSB_LN0_RX_DAC_MUX, (val))

#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_VAL_RG_PON_TX_DIVTDC(val) REG_FLD_VAL(RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_PON_TX_DIVTDC, (val))
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_VAL_RG_PON_RX_CDR_DIVTDC(val) REG_FLD_VAL(RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_PON_RX_CDR_DIVTDC, (val))
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_VAL_RG_PCIE_LN0_CRSDET_VTH(val) REG_FLD_VAL(RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_PCIE_LN0_CRSDET_VTH, (val))
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_VAL_RG_SSUSB_LN0_RX_DAC_MEAS_EN(val) REG_FLD_VAL(RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_SSUSB_LN0_RX_DAC_MEAS_EN, (val))
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_VAL_RG_SSUSB_LN0_RX_PD_PICAL_SWAP(val) REG_FLD_VAL(RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_SSUSB_LN0_RX_PD_PICAL_SWAP, (val))
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_VAL_RG_SSUSB_LN0_RX_PD_RST_PASS(val) REG_FLD_VAL(RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_SSUSB_LN0_RX_PD_RST_PASS, (val))
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_VAL_RG_SSUSB_LN0_RX_PD_RST(val) REG_FLD_VAL(RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_SSUSB_LN0_RX_PD_RST, (val))
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_VAL_RG_SSUSB_LN0_RX_P1_ENTRY_PASS(val) REG_FLD_VAL(RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_SSUSB_LN0_RX_P1_ENTRY_PASS, (val))
#define RG_SSUSB_LN0_RXAFE_DCMON_SEL_VAL_RG_SSUSB_LN0_RXAFE_DCMON_SEL(val) REG_FLD_VAL(RG_SSUSB_LN0_RXAFE_DCMON_SEL_FLD_RG_SSUSB_LN0_RXAFE_DCMON_SEL, (val))

#define RGS_SSUSB_LN0_RX_DEBUG_RESERVE_VAL_RGS_SSUSB_LN0_RX_DEBUG_RESERVE(val) REG_FLD_VAL(RGS_SSUSB_LN0_RX_DEBUG_RESERVE_FLD_RGS_SSUSB_LN0_RX_DEBUG_RESERVE, (val))

#ifdef __cplusplus
}
#endif

#endif // __pon_hsgmii_ana_csr_REGS_H__
