/******************************************************************************/
/*
 * Copyright (C) 1994-2014 Econet Technologies, Corp.
 * All Rights Reserved.
 *
 * TrendChip Confidential; Need to Know only.
 * Protected as an unpublished work.
 *
 * The computer program listings, specifications and documentation
 * herein are the property of TrendChip Technologies, Corp. and
 * shall not be reproduced, copied, disclosed, or used in whole or
 * in part for any reason without the prior express written permission of
 * TrendChip Technologies, Corp.
 */
/******************************************************************************/
#ifndef _COMPILEOPTION_LIB_H
#define _COMPILEOPTION_LIB_H

#define FUNC_MVAL_NUM			5

#define CUSTOM_MVAL_NUM			4

#define CT_MVAL_NUM				5

#define CMCC_MVAL_NUM			3

#define	CUC_MVAL_NUM			3

#define JOYME_MVAL_NUM			3

#define NP_MVAL_NUM				6
#define NP_COMMON_IDX			0
#define NP_CTC_IDX				2
#define NP_CMCC_IDX 			4

#define	PON_MVAL_NUM	3
#define	SOC_MVAL_NUM	3
#define	WIFI_COMMON_MVAL_NUM	3
#define	WIFI_CHIP_MVAL_NUM	3
#define	NPU_MVAL_NUM	3
#define	DP_MVAL_NUM	4
#define VOIP_MVAL_NUM 3
#define FUNC_UVAL_NUM 2


#define	FH_MVAL_NUM	4
#define OPENWRT_MVAL_NUM 3

typedef struct _CompileOption_MVal_
{
	unsigned int _BIT_0:1;
	unsigned int _BIT_1:1;
	unsigned int _BIT_2:1;
	unsigned int _BIT_3:1;
	unsigned int _BIT_4:1;
	unsigned int _BIT_5:1;
	unsigned int _BIT_6:1;
	unsigned int _BIT_7:1;
	unsigned int _BIT_8:1;
	unsigned int _BIT_9:1;
	unsigned int _BIT_10:1;
	unsigned int _BIT_11:1;
	unsigned int _BIT_12:1;
	unsigned int _BIT_13:1;
	unsigned int _BIT_14:1;
	unsigned int _BIT_15:1;
	unsigned int _BIT_16:1;
	unsigned int _BIT_17:1;
	unsigned int _BIT_18:1;
	unsigned int _BIT_19:1;
	unsigned int _BIT_20:1;
	unsigned int _BIT_21:1;
	unsigned int _BIT_22:1;
	unsigned int _BIT_23:1;
	unsigned int _BIT_24:1;
	unsigned int _BIT_25:1;
	unsigned int _BIT_26:1;
	unsigned int _BIT_27:1;
	unsigned int _BIT_28:1;
	unsigned int _BIT_29:1;
	unsigned int _BIT_30:1;
	unsigned int _BIT_31:1;	
}CompileOption_MVal;

typedef struct _CompileOption_UVal_
{
	unsigned int _BYTE_0:8;
	unsigned int _BYTE_1:8;
	unsigned int _BYTE_2:8;
	unsigned int _BYTE_3:8;
}CompileOption_UVal;

extern CompileOption_MVal TCSUPPORT_FUNC_MVAL[];
#define TCSUPPORT_SAMBA_4_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_0
#define TCSUPPORT_LANMGR_NG_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_1
#define TCSUPPORT_CT_L2TP_VPN_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_2
#define TCSUPPORT_CT_MULTI_LAN_PD_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_3
#define TCSUPPORT_XSI_ENABLE_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_4
#define TCSUPPORT_VXLAN_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_5
#define TCSUPPORT_VLAN_TAG_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_6
#define TCSUPPORT_BACKUPROMFILE_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_7
#define TCSUPPORT_PRODUCTIONLINE_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_8
#define TCSUPPORT_NOTDEFAULTROMFILEAREA_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_9
#define TCSUPPORT_AUTOBENCH_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_10
#define TCSUPPORT_ITMS_CONFIG_AS_DEFAULT_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_11
#define TCSUPPORT_DMS_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_12
#define TCSUPPORT_TR69_IP_HOST_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_13
#define TCSUPPORT_WAN_ATM_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_14
#define TCSUPPORT_LAN_VLAN_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_15
#define TCSUPPORT_LAN_VLAN_RANGE_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_16
#define TCSUPPORT_TCAPI_ENHANCE_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_17
#define TCSUPPORT_SYSLOG_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_18
#define TCSUPPORT_RESERVEAREA_EXTEND_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_19
#define TCSUPPORT_ROUTEPOLICY_PRIOR_PORTBIND_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_20
#define TCSUPPORT_TRUE_LANDING_PAGE_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_21
#define TCSUPPORT_CWMP_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_22
#define TCSUPPORT_CWMP_TR181_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_23
#define TCSUPPORT_CWMP_NO_HOST_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_24
#define TCSUPPORT_TEST_WLAN_SHORTCUT_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_25
#define TCSUPPORT_INIC_CLIENT_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_26
#define TCSUPPORT_KEYPARA_STORE_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_27
#define TCSUPPORT_START_TRAP_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_28
#define TCSUPPORT_SYSLOG_ENHANCE_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_29
#define TCSUPPORT_CWMP_FAST_GET_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_30
#define TCSUPPORT_CD_DDNS_VAL TCSUPPORT_FUNC_MVAL[0]._BIT_31
#define TCSUPPORT_CMDPROMPT_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_0
#define TCSUPPORT_RANDOM_INFORM_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_1
#define CWMP_REDIRECT_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_2
#define TCSUPPORT_TR69_BIND_PVC_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_3
#define TCSUPPORT_NO_BOOT_VALUECHANGE_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_4
#define TCSUPPORT_CROSS_REBOOT_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_5
#define TCSUPPORT_BHARTI_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_6
#define TCSUPPORT_CWMP_PRECISE_TIME_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_7
#define TCSUPPORT_PROLINE_CMD_ACTION_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_8
#define TCSUPPORT_MULTISERVICE_ON_WAN_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_9
#define TCSUPPORT_UPNP_ENHANCE_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_10
#define TCSUPPORT_WAN_PTM_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_11
#define TCSUPPORT_CD_NEW_GUI_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_12
#define TCSUPPORT_CCT_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_13
#define TCSUPPORT_CLMP_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_14
#define TCSUPPORT_SAGECOM_CWMP_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_15
#define TCSUPPORT_FW_UPGRADE_DELAY_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_16
#define AZTECH_CWMP_REORDER_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_17
#define TCSUPPORT_CWMP_IOT_STRINGTYPE_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_18
#define TCSUPPORT_CWMP_FAULT_RESPONSE_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_19
#define TCSUPPORT_CWMP_CRPORTCHANGE_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_20
#define TCSUPPORT_WEB_INTERCEPTION_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_21
#define TCSUPPORT_MNT_CONF_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_22
#define TCSUPPORT_FTP_USB_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_23
#define TCSUPPORT_IPV6_FIREWALL_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_24
#define TCSUPPORT_IPV6_FIREWALL_RFC2827_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_25
#define TCSUPPORT_PRODUCTIONLINE_CONTENT_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_26
#define TCSUPPORT_IPV6_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_27
#define TCSUPPORT_UPSTREAM_VLAN_POLICER_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_28
#define TCSUPPORT_GPON_DOWNSTREAM_MAPPING_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_29
#define TCSUPPORT_ARC_CWMP_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_30
#define TCSUPPORT_TR143_CURL_UPLOAD_VAL TCSUPPORT_FUNC_MVAL[1]._BIT_31
#define TCSUPPORT_CSC_EEUROPE_VAL TCSUPPORT_FUNC_MVAL[2]._BIT_0
#define TCSUPPORT_UPGRADE_NO_REBOOT_VAL TCSUPPORT_FUNC_MVAL[2]._BIT_1
#define TCSUPPORT_TR64_DIGEST_AUTH_VAL TCSUPPORT_FUNC_MVAL[2]._BIT_2
#define TCSUPPORT_PORT_ISOLATION_VAL TCSUPPORT_FUNC_MVAL[2]._BIT_3
#define TCSUPPORT_TLS_VAL TCSUPPORT_FUNC_MVAL[2]._BIT_4
#define TCSUPPORT_IPV6_CWMP_VAL TCSUPPORT_FUNC_MVAL[2]._BIT_5
#define TCSUPPORT_CWMP_SSL_VAL TCSUPPORT_FUNC_MVAL[2]._BIT_6
#define TCSUPPORT_CWMP_OPENSSL_VAL TCSUPPORT_FUNC_MVAL[2]._BIT_7
#define TCSUPPORT_CWMP_NG_VAL TCSUPPORT_FUNC_MVAL[2]._BIT_8
#define TCSUPPORT_CFG_NG_VAL TCSUPPORT_FUNC_MVAL[2]._BIT_9
#define TCSUPPORT_IPV6_CEROUTER_VAL TCSUPPORT_FUNC_MVAL[2]._BIT_10
#define TCSUPPORT_CG_DS_ADD_TAG_VAL TCSUPPORT_FUNC_MVAL[2]._BIT_11
#define TCSUPPORT_PORTBIND_VAL TCSUPPORT_FUNC_MVAL[2]._BIT_12
#define TCSUPPORT_ASYM_VOD_VAL TCSUPPORT_FUNC_MVAL[2]._BIT_13
#define TCSUPPORT_CHARSET_CHANGE_VAL TCSUPPORT_FUNC_MVAL[2]._BIT_14
#define TCSUPPORT_DSL_PHYMODE_VAL TCSUPPORT_FUNC_MVAL[2]._BIT_15
#define TCSUPPORT_DSL_PHYMODE_HOST_VAL TCSUPPORT_FUNC_MVAL[2]._BIT_16
#define TCSUPPORT_APPS_NOROOT_PERM_VAL TCSUPPORT_FUNC_MVAL[2]._BIT_17
#define TCSUPPORT_TEST_STRESS_NG_VAL TCSUPPORT_FUNC_MVAL[2]._BIT_18
#define TCSUPPORT_TEST_STRESS_NG_V01310_VAL TCSUPPORT_FUNC_MVAL[2]._BIT_19
#define TCSUPPORT_L2TP_VPN_HWNAT_VAL TCSUPPORT_FUNC_MVAL[2]._BIT_20
#define TCSUPPORT_SISM_HOST_VAL TCSUPPORT_FUNC_MVAL[2]._BIT_21



extern CompileOption_MVal TCSUPPORT_CUSTOM_MVAL[];
#define TCSUPPORT_CT_CONGW_CH_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_0
#define TCSUPPORT_CT_PON_GD_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_1
#define TCSUPPORT_CT_PON_GDV20_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_2
#define TCSUPPORT_CT_PON_CZ_GDCS_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_3
#define TCSUPPORT_CT_PON_CY_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_4
#define TCSUPPORT_CT_PON_CY_JX_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_5
#define TCSUPPORT_CT_PON_JS_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_6
#define TCSUPPORT_CT_FJ_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_7
#define TCSUPPORT_CT_PON_GX_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_8
#define TCSUPPORT_CT_PON_CQ_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_9
#define TCSUPPORT_CY_PON_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_10
#define TCSUPPORT_CT_PON_C9_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_11
#define TCSUPPORT_CT_PON_JS_IP_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_12
#define TCSUPPORT_CT_PON_YN_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_13
#define TCSUPPORT_CT_PON_NMG_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_14
#define TCSUPPORT_C1_MS_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_15
#define TCSUPPORT_C1_ZY_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_16
#define TCSUPPORT_C7_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_17
#define TCSUPPORT_CY_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_18
#define TCSUPPORT_CT_PON_C7_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_19
#define TCSUPPORT_CY_E8_SFU_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_20
#define TCSUPPORT_CT_PON_JX_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_21
#define TCSUPPORT_CT_PON_SK_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_22
#define TCSUPPORT_CT_PON_CN_JS_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_23
#define TCSUPPORT_CT_PON_CZ_GD_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_24
#define TCSUPPORT_CT_PON_CZ_NX_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_25
#define TCSUPPORT_CDS_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_26
#define TCSUPPORT_CZ_GENERAL_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_27
#define TCSUPPORT_CZ_TM_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_28
#define TCSUPPORT_TTNET_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_29
#define TCSUPPORT_C1_NEW_GUI_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_30
#define TCSUPPORT_C1_OBM_VAL TCSUPPORT_CUSTOM_MVAL[0]._BIT_31
#define TCSUPPORT_CHT_RAMENU_VAL TCSUPPORT_CUSTOM_MVAL[1]._BIT_0
#define TCSUPPORT_CHS_VAL TCSUPPORT_CUSTOM_MVAL[1]._BIT_1
#define TCSUPPORT_C9_ROST_LED_VAL TCSUPPORT_CUSTOM_MVAL[1]._BIT_2
#define TCSUPPORT_VNPTT_VAL TCSUPPORT_CUSTOM_MVAL[1]._BIT_3
#define TCSUPPORT_CCA_VAL TCSUPPORT_CUSTOM_MVAL[1]._BIT_4
#define TCSUPPORT_CD_WIND_VAL TCSUPPORT_CUSTOM_MVAL[1]._BIT_5
#define TCSUPPORT_CRJO_VAL TCSUPPORT_CUSTOM_MVAL[1]._BIT_6
#define TCSUPPORT_GOOGLE_FIBER_VAL TCSUPPORT_CUSTOM_MVAL[1]._BIT_7
#define TCSUPPORT_ALPHION_PON_VAL TCSUPPORT_CUSTOM_MVAL[1]._BIT_8
#define TCSUPPORT_CDS_CT_VAL TCSUPPORT_CUSTOM_MVAL[1]._BIT_9
#define TCSUPPORT_CATV_GD_VAL TCSUPPORT_CUSTOM_MVAL[1]._BIT_10
#define TCSUPPORT_DZS_VAL TCSUPPORT_CUSTOM_MVAL[1]._BIT_11

extern CompileOption_MVal TCSUPPORT_CT_MVAL[];
#define TCSUPPORT_CT_VAL TCSUPPORT_CT_MVAL[0]._BIT_0
#define TCSUPPORT_CT_APPROUTE_VAL TCSUPPORT_CT_MVAL[0]._BIT_1
#define TCSUPPORT_CT_APPFILTER_VAL TCSUPPORT_CT_MVAL[0]._BIT_2
#define TCSUPPORT_CT_DSL_EX_VAL TCSUPPORT_CT_MVAL[0]._BIT_3
#define TCSUPPORT_CT_PON_BIND2_VAL TCSUPPORT_CT_MVAL[0]._BIT_4
#define TCSUPPORT_CT_PON_VAL TCSUPPORT_CT_MVAL[0]._BIT_5
#define TCSUPPORT_CT_UPG_PINGPONG_VAL TCSUPPORT_CT_MVAL[0]._BIT_6
#define TCSUPPORT_CT_MIDWARE_VAL TCSUPPORT_CT_MVAL[0]._BIT_7
#define TCSUPPORT_CT_BACKUPROMFILEENCHANCEMENT_VAL TCSUPPORT_CT_MVAL[0]._BIT_8
#define TCSUPPORT_CT_PHONEAPP_VAL TCSUPPORT_CT_MVAL[0]._BIT_9
#define TCSUPPORT_CT_DEV_ACCESS_TYPE_VAL TCSUPPORT_CT_MVAL[0]._BIT_10
#define TCSUPPORT_CT_ECN_GZ_VAL TCSUPPORT_CT_MVAL[0]._BIT_11
#define TCSUPPORT_CT_MONITORCOLLECTOR_VAL TCSUPPORT_CT_MVAL[0]._BIT_12
#define TCSUPPORT_CT_PPPOE_EMULATOR_VAL TCSUPPORT_CT_MVAL[0]._BIT_13
#define CT_COM_DEVICEREG_VAL TCSUPPORT_CT_MVAL[0]._BIT_14
#define TCSUPPORT_CT_UPNP_DM_VAL TCSUPPORT_CT_MVAL[0]._BIT_15
#define TCSUPPORT_CT_PPPINFORM_VAL TCSUPPORT_CT_MVAL[0]._BIT_16
#define TCSUPPORT_CT_SWQOS_VAL TCSUPPORT_CT_MVAL[0]._BIT_17
#define TCSUPPORT_CT_PORT_BIND_VAL TCSUPPORT_CT_MVAL[0]._BIT_18
#define TCSUPPORT_CT_GUIACCESSLIMIT_VAL TCSUPPORT_CT_MVAL[0]._BIT_19
#define TCSUPPORT_CT_PPPOEPROXY_VAL TCSUPPORT_CT_MVAL[0]._BIT_20
#define TCSUPPORT_CT_ZIPROMFILE_VAL TCSUPPORT_CT_MVAL[0]._BIT_21
#define TCSUPPORT_CT_E8B_ADSL_VAL TCSUPPORT_CT_MVAL[0]._BIT_22
#define TCSUPPORT_CT_WANNODE_MAPPING_VAL TCSUPPORT_CT_MVAL[0]._BIT_23
#define TCSUPPORT_CT_BLOCK_PROCESS_VAL TCSUPPORT_CT_MVAL[0]._BIT_24
#define TCSUPPORT_CT_SERVICELIST_E8C_VAL TCSUPPORT_CT_MVAL[0]._BIT_25
#define TCSUPPORT_CT_ALARMMONITOR_VAL TCSUPPORT_CT_MVAL[0]._BIT_26
#define TCSUPPORT_CT_INFORM_NODE_VAL TCSUPPORT_CT_MVAL[0]._BIT_27
#define TCSUPPORT_CT_LONG_RESETBTN_VAL TCSUPPORT_CT_MVAL[0]._BIT_28
#define TCSUPPORT_CT_PPP_ONDEMAND_VAL TCSUPPORT_CT_MVAL[0]._BIT_29
#define TCSUPPORT_CT_PPP_MANUALLY_VAL TCSUPPORT_CT_MVAL[0]._BIT_30
#define TCSUPPORT_CT_CWMP_ZIPROMFILE_VAL TCSUPPORT_CT_MVAL[0]._BIT_31
#define TCSUPPORT_CT_FTP_DOWNLOADCLIENT_VAL TCSUPPORT_CT_MVAL[1]._BIT_0
#define TCSUPPORT_CT_NEWGUI_VAL TCSUPPORT_CT_MVAL[1]._BIT_1
#define TCSUPPORT_CT_HWQOS_VAL TCSUPPORT_CT_MVAL[1]._BIT_2
#define TCSUPPORT_CT_VLAN_BIND_VAL TCSUPPORT_CT_MVAL[1]._BIT_3
#define TCSUPPORT_CT_DSLITE_VAL TCSUPPORT_CT_MVAL[1]._BIT_4
#define TCSUPPORT_CT_STBMAC_REPORT_VAL TCSUPPORT_CT_MVAL[1]._BIT_5
#define TCSUPPORT_CT_PMINFORM_VAL TCSUPPORT_CT_MVAL[1]._BIT_6
#define TCSUPPORT_CT_PON_HUB_VAL TCSUPPORT_CT_MVAL[1]._BIT_7
#define TCSUPPORT_CT_ADSL_HN_VAL TCSUPPORT_CT_MVAL[1]._BIT_8
#define TCSUPPORT_CT_PON_SC_VAL TCSUPPORT_CT_MVAL[1]._BIT_9
#define TCSUPPORT_CT_PON_C9_HUN_VAL TCSUPPORT_CT_MVAL[1]._BIT_10
#define TCSUPPORT_CT_TR143_WGET_DOWNLOAD_VAL TCSUPPORT_CT_MVAL[1]._BIT_11
#define TCSUPPORT_CT_ADSL_TJ_VAL TCSUPPORT_CT_MVAL[1]._BIT_12
#define TCSUPPORT_CT_ADSL_BIND1_VAL TCSUPPORT_CT_MVAL[1]._BIT_13
#define TCSUPPORT_CT_NAMECHGNOTIFY_VAL TCSUPPORT_CT_MVAL[1]._BIT_14
#define TCSUPPORT_CT_C5_HEN_SFU_VAL TCSUPPORT_CT_MVAL[1]._BIT_15
#define TCSUPPORT_CT_SFU_SX_VAL TCSUPPORT_CT_MVAL[1]._BIT_16
#define TCSUPPORT_CT_ITMS_TMOUT_VAL TCSUPPORT_CT_MVAL[1]._BIT_17
#define TCSUPPORT_CT_CWMP_WORK_COMPATIBLE_VAL TCSUPPORT_CT_MVAL[1]._BIT_18
#define TCSUPPORT_CT_VPN_ONDEMAND_VAL TCSUPPORT_CT_MVAL[1]._BIT_19
#define TCSUPPORT_CT_VPN_PPTP_VAL TCSUPPORT_CT_MVAL[1]._BIT_20
#define TCSUPPORT_CT_VLAN_TAG_VAL TCSUPPORT_CT_MVAL[1]._BIT_21
#define TCSUPPORT_CT_WANNINDEX_INCREASE_VAL TCSUPPORT_CT_MVAL[1]._BIT_22
#define TCSUPPORT_CT_SIMCARD_SEPARATION_VAL TCSUPPORT_CT_MVAL[1]._BIT_23
#define TCSUPPORT_CT_2PORTS_VAL TCSUPPORT_CT_MVAL[1]._BIT_24
#define TCSUPPORT_CT_PON_SN_VAL TCSUPPORT_CT_MVAL[1]._BIT_25
#define TCSUPPORT_CT_WAN_PTM_VAL TCSUPPORT_CT_MVAL[1]._BIT_26
#define TCSUPPORT_E8B_VAL TCSUPPORT_CT_MVAL[1]._BIT_27
#define TCSUPPORT_CT_STANDARD_E8C_VAL TCSUPPORT_CT_MVAL[1]._BIT_28
#define TCSUPPORT_CT_BUTTONDETECT_VAL TCSUPPORT_CT_MVAL[1]._BIT_29
#define TCSUPPORT_CT_HWNAT_OFFLOAD_VAL TCSUPPORT_CT_MVAL[1]._BIT_30
#define TCSUPPORT_CT_MAP_INSIDE_AGENT_VAL TCSUPPORT_CT_MVAL[1]._BIT_31
#define TCSUPPORT_CT_DS_LIMIT_VAL TCSUPPORT_CT_MVAL[2]._BIT_0
#define TCSUPPORT_CT_IGMP_PPPOE_TO_IPOE_VAL TCSUPPORT_CT_MVAL[2]._BIT_1

extern CompileOption_MVal TCSUPPORT_CMCC_MVAL[];
#define TCSUPPORT_CMCC_VAL TCSUPPORT_CMCC_MVAL[0]._BIT_0
#define TCSUPPORT_CMCCV2_VAL TCSUPPORT_CMCC_MVAL[0]._BIT_1
#define TCSUPPORT_CMCC_GANSU_VAL TCSUPPORT_CMCC_MVAL[0]._BIT_2
#define TCSUPPORT_CMCC_ENTERPRISE_VAL TCSUPPORT_CMCC_MVAL[0]._BIT_3

extern CompileOption_MVal TCSUPPORT_CUC_MVAL[];
#define TCSUPPORT_CUC_VAL TCSUPPORT_CUC_MVAL[0]._BIT_0
#define TCSUPPORT_CUC_FJ_SFU_VAL TCSUPPORT_CUC_MVAL[0]._BIT_1
#define TCSUPPORT_CUC_C5_2P_VAL TCSUPPORT_CUC_MVAL[0]._BIT_2
#define TCSUPPORT_CUC_CWMP_PARAMETER_VAL TCSUPPORT_CUC_MVAL[0]._BIT_3
#define TCSUPPORT_C1_CUC_VAL TCSUPPORT_CUC_MVAL[0]._BIT_4
#define TCSUPPORT_CUC_QOS_VAL TCSUPPORT_CUC_MVAL[0]._BIT_5
#define TCSUPPORT_CUC_PON_SD_VAL TCSUPPORT_CUC_MVAL[0]._BIT_6

extern CompileOption_MVal TCSUPPORT_CT_JOYME_MVAL[];
#define TCSUPPORT_CT_JOYME4_VAL TCSUPPORT_CT_JOYME_MVAL[0]._BIT_0
#define TCSUPPORT_CT_JOYME4_JC_VAL TCSUPPORT_CT_JOYME_MVAL[0]._BIT_1
#define TCSUPPORT_CT_IPOE_DETECT_VAL TCSUPPORT_CT_JOYME_MVAL[0]._BIT_2
#define TCSUPPORT_CT_JOYME_VAL TCSUPPORT_CT_JOYME_MVAL[0]._BIT_3
#define TCSUPPORT_CT_JOYME2_VAL TCSUPPORT_CT_JOYME_MVAL[0]._BIT_4
#define TCSUPPORT_CT_JOYME_BANDWIDTH_VAL TCSUPPORT_CT_JOYME_MVAL[0]._BIT_5
#define TCSUPPORT_CT_DBUS_VAL TCSUPPORT_CT_JOYME_MVAL[0]._BIT_6
#define TCSUPPORT_SDN_OVS_VAL TCSUPPORT_CT_JOYME_MVAL[0]._BIT_7

extern CompileOption_MVal TCSUPPORT_NP_MVAL[];
#define TCSUPPORT_NP_VAL TCSUPPORT_NP_MVAL[NP_COMMON_IDX]._BIT_0
#define TCSUPPORT_NP_RAM_SHRINK_VAL TCSUPPORT_NP_MVAL[NP_COMMON_IDX]._BIT_1
#define TCSUPPORT_NP_CODE_SHRINK_VAL TCSUPPORT_NP_MVAL[NP_COMMON_IDX]._BIT_2
#define TCSUPPORT_NP_FTTR_VAL TCSUPPORT_NP_MVAL[NP_COMMON_IDX]._BIT_3

#define TCSUPPORT_NP_CTC_VAL TCSUPPORT_NP_MVAL[NP_CTC_IDX]._BIT_0
#define TCSUPPORT_CT_UBUS_VAL TCSUPPORT_NP_MVAL[NP_CTC_IDX]._BIT_1

#define TCSUPPORT_NP_CMCC_VAL TCSUPPORT_NP_MVAL[NP_CMCC_IDX]._BIT_0
#define TCSUPPORT_ANDLINK_VAL TCSUPPORT_NP_MVAL[NP_CMCC_IDX]._BIT_1

extern CompileOption_MVal TCSUPPORT_PON_MVAL[];
#define TCSUPPORT_PON_VLAN_FILTER_VAL TCSUPPORT_PON_MVAL[0]._BIT_0
#define TCSUPPORT_PON_MAC_FILTER_VAL  TCSUPPORT_PON_MVAL[0]._BIT_1
#define TCSUPPORT_PON_IP_HOST_VAL  TCSUPPORT_PON_MVAL[0]._BIT_2
#define TCSUPPORT_PONMGR_VAL  TCSUPPORT_PON_MVAL[0]._BIT_3
#define TCSUPPORT_PMMGR_VAL  TCSUPPORT_PON_MVAL[0]._BIT_4
#define TCSUPPORT_WAN_GPON_VAL  TCSUPPORT_PON_MVAL[0]._BIT_5
#define TCSUPPORT_WAN_EPON_VAL  TCSUPPORT_PON_MVAL[0]._BIT_6
#define TCSUPPORT_OMCI_VAL  TCSUPPORT_PON_MVAL[0]._BIT_7
#define TCSUPPORT_EPON_OAM_CTC_VAL  TCSUPPORT_PON_MVAL[0]._BIT_8
#define TCSUPPORT_OMCI_ALCATEL_VAL  TCSUPPORT_PON_MVAL[0]._BIT_9
#define TCSUPPORT_GPON_MAPPING_VAL  TCSUPPORT_PON_MVAL[0]._BIT_10
#define TCSUPPORT_EPON_MAPPING_VAL  TCSUPPORT_PON_MVAL[0]._BIT_11
#define TCSUPPORT_PON_USER_ISOLATION_VAL  TCSUPPORT_PON_MVAL[0]._BIT_12
#define TCSUPPORT_XPON_IGMP_VAL  TCSUPPORT_PON_MVAL[0]._BIT_13
#define TCSUPPORT_PON_SFU_HGU_HYBRID_VAL  TCSUPPORT_PON_MVAL[0]._BIT_14
#define TCSUPPORT_PON_VLAN_VAL  TCSUPPORT_PON_MVAL[0]._BIT_15
#define TCSUPPORT_OMCI_LAN_DEBUG_VAL  TCSUPPORT_PON_MVAL[0]._BIT_16
#define TCSUPPORT_XPON_LED_VAL  TCSUPPORT_PON_MVAL[0]._BIT_17
#define TCSUPPORT_EPON_DUMMY_VAL  TCSUPPORT_PON_MVAL[0]._BIT_18
#define TCSUPPORT_XPON_IGMP_CHT_VAL  TCSUPPORT_PON_MVAL[0]._BIT_19
#define TCSUPPORT_PON_ROSTELECOM_VAL  TCSUPPORT_PON_MVAL[0]._BIT_20
#define TCSUPPORT_XPON_LED_UPGRADE_VAL  TCSUPPORT_PON_MVAL[0]._BIT_21
#define TCSUPPORT_BBF_247_VAL  TCSUPPORT_PON_MVAL[0]._BIT_22

extern CompileOption_MVal TCSUPPORT_SOC_MVAL[];
#define TCSUPPORT_SECURE_BOOT_V1_VAL TCSUPPORT_SOC_MVAL[0]._BIT_0
#define TCSUPPORT_CPU_MT7505_VAL TCSUPPORT_SOC_MVAL[0]._BIT_1
#define TCSUPPORT_CPU_MT7510_VAL TCSUPPORT_SOC_MVAL[0]._BIT_2
#define TCSUPPORT_CPU_MT7520_VAL TCSUPPORT_SOC_MVAL[0]._BIT_3
#define TCSUPPORT_VPN_VAL TCSUPPORT_SOC_MVAL[0]._BIT_4
#define TCSUPPORT_MULTI_BOOT_VAL TCSUPPORT_SOC_MVAL[0]._BIT_5
#define TCSUPPORT_USBHOST_VAL TCSUPPORT_SOC_MVAL[0]._BIT_6
#define TCSUPPORT_CPU_PERFORMANCE_TEST_VAL TCSUPPORT_SOC_MVAL[0]._BIT_7
#define TCSUPPORT_CPU_EN75XX_VAL TCSUPPORT_SOC_MVAL[0]._BIT_8
#define TCSUPPORT_CPU_EN758X_VAL TCSUPPORT_SOC_MVAL[0]._BIT_9
#define TCSUPPORT_CPU_EN7528_VAL TCSUPPORT_SOC_MVAL[0]._BIT_10
#define TCSUPPORT_CPU_EN7512_VAL TCSUPPORT_SOC_MVAL[0]._BIT_11
#define TCSUPPORT_IPSEC_PASSTHROUGH_VAL TCSUPPORT_SOC_MVAL[0]._BIT_12
#define TCSUPPORT_MIPS_1004K_VAL TCSUPPORT_SOC_MVAL[0]._BIT_13
#define TCSUPPORT_HIGHMEM_VAL TCSUPPORT_SOC_MVAL[0]._BIT_14
#define TCSUPPORT_NEW_WDOG_VAL TCSUPPORT_SOC_MVAL[0]._BIT_15
#define TCSUPPORT_BB_256KB_VAL TCSUPPORT_SOC_MVAL[0]._BIT_16
#define TCSUPPORT_CPU_ARMV8_VAL TCSUPPORT_SOC_MVAL[0]._BIT_17

extern CompileOption_MVal TCSUPPORT_DP_MVAL[];
#define TCSUPPORT_RA_HWNAT_VAL TCSUPPORT_DP_MVAL[0]._BIT_0
#define TCSUPPORT_MANUAL_ETHERNET_PORTMAP_VAL TCSUPPORT_DP_MVAL[0]._BIT_1
#define TCSUPPORT_VLAN_DOT1P_VAL TCSUPPORT_DP_MVAL[0]._BIT_2
#define TCSUPPORT_VLAN_PASSTHROUGH_VAL TCSUPPORT_DP_MVAL[0]._BIT_3
#define TCSUPPORT_HWNAT_L2VID_VAL TCSUPPORT_DP_MVAL[0]._BIT_4
#define TCSUPPORT_IFC_EN_VAL TCSUPPORT_DP_MVAL[0]._BIT_5
#define TCSUPPORT_WAN_ETHER_VAL TCSUPPORT_DP_MVAL[0]._BIT_6
#define TCSUPPORT_WAN_XSI_VAL TCSUPPORT_DP_MVAL[0]._BIT_7
#define TCSUPPORT_HSGMII_LAN_VAL TCSUPPORT_DP_MVAL[0]._BIT_8
#define TCSUPPORT_ACTIVE_ETHERNET_WAN_VAL TCSUPPORT_DP_MVAL[0]._BIT_9
#define TCSUPPORT_HWNAT_VAL TCSUPPORT_DP_MVAL[0]._BIT_10
#define TCSUPPORT_HWNAT_WAN_ACCOUNT_VAL TCSUPPORT_DP_MVAL[0]._BIT_11
#define TCSUPPORT_2PORTS_VAL TCSUPPORT_DP_MVAL[0]._BIT_12
#define TCSUPPORT_MULTICAST_SPEED_VAL TCSUPPORT_DP_MVAL[0]._BIT_13
#define TCSUPPORT_IGMP_SET_GROUP_VAL TCSUPPORT_DP_MVAL[0]._BIT_14
#define RA_NAT_EXE_VAL TCSUPPORT_DP_MVAL[0]._BIT_15
#define TCSUPPORT_SWNAT_VAL TCSUPPORT_DP_MVAL[0]._BIT_16
#define TCSUPPORT_TC2031_VAL TCSUPPORT_DP_MVAL[0]._BIT_17
#define TCSUPPORT_DS_HWNAT_OFFLOAD_VAL TCSUPPORT_DP_MVAL[0]._BIT_18
#define TCSUPPORT_WAN_UPSTREAM_REMARK_VAL TCSUPPORT_DP_MVAL[0]._BIT_19
#define TCSUPPORT_SMUX_HW_STAT_VAL TCSUPPORT_DP_MVAL[0]._BIT_20
#define TCSUPPORT_RA_HWNAT_ENHANCE_HOOK_VAL TCSUPPORT_DP_MVAL[0]._BIT_21
#define TCSUPPORT_LRO_ENABLE_VAL TCSUPPORT_DP_MVAL[0]._BIT_22
#define TCSUPPORT_HWNAT_ADD_DEL_API_VAL TCSUPPORT_DP_MVAL[0]._BIT_23
#define TCSUPPORT_MULIF_WAN_SAME_MAC_VAL TCSUPPORT_DP_MVAL[0]._BIT_24
#define TCSUPPORT_MULTI_USER_ITF_VAL TCSUPPORT_DP_MVAL[0]._BIT_25
#define TCSUPPORT_GRE_TUNNEL_HWNAT_VAL TCSUPPORT_DP_MVAL[0]._BIT_26
#define TCSUPPORT_MULTI_SWITCH_EXT_VAL TCSUPPORT_DP_MVAL[0]._BIT_27
#define TCSUPPORT_QDMA_WAN_FOR_ETHER_VAL TCSUPPORT_DP_MVAL[0]._BIT_28
#define TCSUPPORT_VLAN_ACCESS_TRUNK_VAL TCSUPPORT_DP_MVAL[0]._BIT_29
#define TCSUPPORT_QOS_EIGHT_QUEUE_VAL TCSUPPORT_DP_MVAL[0]._BIT_30
#define TCSUPPORT_EXTENDED_VLAN_VAL TCSUPPORT_DP_MVAL[0]._BIT_31
#define TCSUPPORT_UNKNOW_MULTICAST_COUNT_VAL TCSUPPORT_DP_MVAL[1]._BIT_0
#define TCSUPPORT_VXLAN_HW_OFFLOAD_VAL TCSUPPORT_DP_MVAL[1]._BIT_1
#define TCSUPPORT_ACCOUNT_METER_V2_VAL TCSUPPORT_DP_MVAL[1]._BIT_2

extern CompileOption_MVal TCSUPPORT_VOIP_MVAL[];
#define TCSUPPORT_VOIP_VAL TCSUPPORT_VOIP_MVAL[0]._BIT_0
#define TCSUPPORT_ZARLINK_LE89156B_VAL TCSUPPORT_VOIP_MVAL[0]._BIT_1
#define TCSUPPORT_VOIP_LED_APPCTRL_VAL TCSUPPORT_VOIP_MVAL[0]._BIT_2
#define TCSUPPORT_CT_VOIP_CRYPT_VAL TCSUPPORT_VOIP_MVAL[0]._BIT_3
#define TCSUPPORT_VOIP_SIP_DNS_VAL TCSUPPORT_VOIP_MVAL[0]._BIT_4
#define TCSUPPORT_ZARLINK_LE89156A_VAL TCSUPPORT_VOIP_MVAL[0]._BIT_5
#define TCSUPPORT_CT_1FXS_VAL TCSUPPORT_VOIP_MVAL[0]._BIT_6
#define TCSUPPORT_CT_VOIP_SIP_VAL TCSUPPORT_VOIP_MVAL[0]._BIT_7
#define TCSUPPORT_ECN_SIP_VAL TCSUPPORT_VOIP_MVAL[0]._BIT_8
#define TCSUPPORT_ECN_MEGACO_VAL TCSUPPORT_VOIP_MVAL[0]._BIT_9
#define TCSUPPORT_SLIC_ZL88801_VAL TCSUPPORT_VOIP_MVAL[0]._BIT_10

extern CompileOption_MVal TCSUPPORT_WIFI_COMMON_MVAL[];
#define TCSUPPORT_WLAN_VAL TCSUPPORT_WIFI_COMMON_MVAL[0]._BIT_0
#define TCSUPPORT_WLAN_AC_VAL TCSUPPORT_WIFI_COMMON_MVAL[0]._BIT_1
#define TCSUPPORT_WLAN_MULTIDRIVER_VAL TCSUPPORT_WIFI_COMMON_MVAL[0]._BIT_2
#define TCSUPPORT_DLF_CTRL_VAL TCSUPPORT_WIFI_COMMON_MVAL[0]._BIT_3
#define TCSUPPORT_WLAN_SW_RPS_VAL TCSUPPORT_WIFI_COMMON_MVAL[0]._BIT_4
#define TCSUPPORT_WLAN_WDS_VAL TCSUPPORT_WIFI_COMMON_MVAL[0]._BIT_5
#define TCSUPPORT_MESH_ROLE_AUTO_DETECT_VAL TCSUPPORT_WIFI_COMMON_MVAL[0]._BIT_6
#define TCSUPPORT_MESH_ETHETWAN_PORT_ONBOARDING_VAL TCSUPPORT_WIFI_COMMON_MVAL[0]._BIT_7
#define TCSUPPORT_WLAN_MT76_MAC80211_VAL TCSUPPORT_WIFI_COMMON_MVAL[0]._BIT_8
#define TCSUPPORT_WLAN_INODE_VAL TCSUPPORT_WIFI_COMMON_MVAL[0]._BIT_9


extern CompileOption_MVal TCSUPPORT_WIFI_CHIP_MVAL[];
#define TCSUPPORT_WLAN_MT7592_VAL TCSUPPORT_WIFI_CHIP_MVAL[0]._BIT_0
#define TCSUPPORT_WLAN_RT3390_VAL TCSUPPORT_WIFI_CHIP_MVAL[0]._BIT_1
#define TCSUPPORT_WLAN_RT3090_VAL TCSUPPORT_WIFI_CHIP_MVAL[0]._BIT_2
#define TCSUPPORT_WLAN_RT5392_VAL TCSUPPORT_WIFI_CHIP_MVAL[0]._BIT_3
#define TCSUPPORT_WLAN_MT7615_TXOFFLOAD_VAL TCSUPPORT_WIFI_CHIP_MVAL[0]._BIT_4
#define TCSUPPORT_DUAL_WLAN_MT7613E_VAL TCSUPPORT_WIFI_CHIP_MVAL[0]._BIT_5

extern CompileOption_MVal TCSUPPORT_NPU_MVAL[];
#define TCSUPPORT_NPU_VAL TCSUPPORT_NPU_MVAL[0]._BIT_0
#define TCSUPPORT_NPU_TUNNEL_OFFLOAD_VAL  TCSUPPORT_NPU_MVAL[0]._BIT_1
#define TCSUPPORT_NPU_WIFI_OFFLOAD_VAL  TCSUPPORT_NPU_MVAL[0]._BIT_2
#define TCSUPPORT_NPU_WIFI_TX_VAL  TCSUPPORT_NPU_MVAL[0]._BIT_3

#if 0
extern CompileOption_Val TCSUPPORT_CDS_VTAG_TRANSPARENT_VAL;
#endif

extern CompileOption_MVal TCSUPPORT_CF_MVAL[];
#define TCSUPPORT_FH_BOOTUP_VAL TCSUPPORT_CF_MVAL[0]._BIT_0
#define TCSUPPORT_FH_PON_VAL TCSUPPORT_CF_MVAL[0]._BIT_1
#define TCSUPPORT_FH_UNION_VAL TCSUPPORT_CF_MVAL[0]._BIT_2
#define TCSUPPORT_FH_DP_VAL TCSUPPORT_CF_MVAL[0]._BIT_3

/* not used */
#define TCSUPPORT_PON_CF_VAL TCSUPPORT_CF_MVAL[1]._BIT_0
#define TCSUPPORT_EPON_OAM_LAN_DBG_VAL TCSUPPORT_CF_MVAL[1]._BIT_1
#define TCSUPPORT_XPON_HAL_API_QOS_VAL TCSUPPORT_CF_MVAL[1]._BIT_2
#define TCSUPPORT_XPON_HAL_API_VAL TCSUPPORT_CF_MVAL[1]._BIT_3
#define TCSUPPORT_XPON_HAL_API_EXT_VAL TCSUPPORT_CF_MVAL[1]._BIT_4
#define TCSUPPORT_XPON_PON_QOS_VAL TCSUPPORT_CF_MVAL[1]._BIT_5
#define TCSUPPORT_XPON_HAL_API_MCST_VAL TCSUPPORT_CF_MVAL[1]._BIT_6
#define TCSUPPORT_CF_JOYMEV2_PON_VAL TCSUPPORT_CF_MVAL[1]._BIT_7
#define TCSUPPORT_FWC_ENV_VAL TCSUPPORT_CF_MVAL[1]._BIT_8
#define TCSUPPORT_FH_SDN_PON_VAL TCSUPPORT_CF_MVAL[1]._BIT_9
#define TCSUPPORT_FWC_QOS_VAL TCSUPPORT_CF_MVAL[1]._BIT_10
#define TCSUPPORT_CF_FDB_VLAN_VAL TCSUPPORT_CF_MVAL[1]._BIT_11
#define TCSUPPORT_FWC_VLAN_TAG_VAL TCSUPPORT_CF_MVAL[1]._BIT_12
#define TCSUPPORT_FWC_MCST_VAL TCSUPPORT_CF_MVAL[1]._BIT_13
#define TCSUPPORT_XPON_HAL_API_NG_VAL TCSUPPORT_CF_MVAL[1]._BIT_14
#define TCSUPPORT_CF_UNIFIED_PLATFORM_VAL TCSUPPORT_CF_MVAL[1]._BIT_15

extern CompileOption_MVal TCSUPPORT_OPENWRT_MVAL[];
#define TCSUPPORT_OPENWRT_MULTI_WAN_VAL TCSUPPORT_OPENWRT_MVAL[0]._BIT_0

extern CompileOption_UVal TCSUPPORT_FUNC_UVAL[];
#define TCSUPPORT_USER_DEFINE_FIRST_MAC_VAL TCSUPPORT_FUNC_UVAL[1]._BYTE_0

void init_compileoption_val(void);

#endif
