#ifndef RATE_ADAPTION_CSR_XGMII_REG
#define RATE_ADAPTION_CSR_XGMII_REG

#define _rg_rate_adapt_ctrl_0 0x0
#define _rg_rate_adapt_ctrl_1 0x4
#define _rg_rate_adapt_ctrl_2 0x8
#define _rg_rate_adapt_ctrl_3 0xc
#define _rg_rate_adapt_ctrl_4 0x10
#define _rg_rate_adapt_ctrl_5 0x14
#define _rg_rate_adapt_ctrl_6 0x18
#define _rg_rate_adapt_ctrl_7 0x1c
#define _rg_rate_adapt_ctrl_8 0x20
#define _rg_rate_adapt_ctrl_9 0x24
#define _rg_rate_adapt_ctrl_10 0x28
#define _rg_rate_adapt_ctrl_11 0x2c
#define _ro_rate_adapt_sts_0 0x30
#define _ro_rate_adapt_sts_1 0x34
#define _ro_rate_adapt_sts_2 0x38
#define _ro_rate_adapt_sts_3 0x3c
#define _ro_rate_adapt_sts_4 0x40
#define _ro_rate_adapt_sts_5 0x44
#define _ro_rate_adapt_sts_6 0x48
#define _ro_rate_adapt_sts_7 0x4c
#define _ro_rate_adapt_sts_8 0x50
#define _ro_rate_adapt_sts_9 0x54
#define _ro_rate_adapt_sts_10 0x58
#define _ro_rate_adapt_sts_11 0x5c
#define _ro_rate_adapt_sts_12 0x60
#define _XGMII_IPG_CNT 0x64
#define _ro_rate_adapt_sts_13 0x70
#define _ro_rate_adapt_sts_14 0x74
#define _ro_rate_adapt_sts_15 0x78
#define _ro_rate_adapt_sts_16 0x80
#define _ro_rate_adapt_sts_17 0x84
#define _ro_rate_adapt_sts_18 0x88
#define _rg_rate_adapt_out_cnt_reset 0xa0
#define _ro_rate_adapt_out_cnt_pre6 0xa4
#define _ro_rate_adapt_out_cnt_pre5 0xa8
#define _rg_fpga_mode_set 0xac
#define _ro_rate_adapt_ctrl_0_sts 0xb0
#define _ro_rate_adapt_ctrl_1_sts 0xb4
#define _ro_rate_adapt_ctrl_2_sts 0xb8
#define _ro_rate_adapt_ctrl_3_sts 0xbc
#define _ro_rate_adapt_ctrl_4_sts 0xc0
#define _ro_rate_adapt_ctrl_5_sts 0xc4
#define _ro_rate_adapt_ctrl_6_sts 0xc8
#define _ro_rate_adapt_ctrl_7_sts 0xcc
#define _ro_rate_adapt_ctrl_8_sts 0xd0
#define _ro_rate_adapt_ctrl_9_sts 0xd4
#define _ro_rate_adapt_ctrl_10_sts 0xd8
#define _rg_rate_adapt_modified 0xdc
#define _rg_xgmii_dbg_0 0xe0
#define _rg_xgmii_dbg_1 0xe4
#define _rg_xgmii_dbg_2 0xe8
#define _rg_xgmii_dbg_3 0xec
#define _rg_xgmii_dbg_4 0xf0
#define _rg_xgmii_dbg_5 0xf4
#define _xgmii_ipg_dbg_0 0xf8
#define _xgmii_ipg_dbg_1 0xfc
#endif