/******************************************************************************/
/*
 * Copyright (C) 1994-2014 EcoNet Technologies, Corp.
 * All Rights Reserved.
 *
 * TrendChip Confidential; Need to Know only.
 * Protected as an unpublished work.
 *
 * The computer program listings, specifications and documentation
 * herein are the property of TrendChip Technologies, Corp. and
 * shall not be reproduced, copied, disclosed, or used in whole or
 * in part for any reason without the prior express written permission of
 * TrendChip Technologies, Corp.
 */
/******************************************************************************/
//#include <stdlib.h>
#ifdef __KERNEL__
#include <linux/init.h>
#include <linux/mm.h>
#include <linux/sched.h>
#include <linux/version.h>
#if LINUX_VERSION_CODE < KERNEL_VERSION(5,4,0)
#include <linux/bootmem.h>
#endif
#include <linux/blkdev.h>

#if !defined(TCSUPPORT_CPU_ARMV8) && !defined(TCSUPPORT_CPU_ARMV8_64)
#include <asm/mipsmtregs.h>
#include <asm/addrspace.h>
#include <asm/bootinfo.h>
#include <asm/time.h>
#include <asm/traps.h>
#endif

#include <asm/cpu.h>

#include <linux/libcompileoption.h>
#else
#include "libcompileoption.h"
#endif

CompileOption_MVal TCSUPPORT_FUNC_MVAL[FUNC_MVAL_NUM] = {0};
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_FUNC_MVAL);
#endif

CompileOption_MVal TCSUPPORT_CUSTOM_MVAL[CUSTOM_MVAL_NUM] = {0};
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CUSTOM_MVAL);
#endif

CompileOption_MVal TCSUPPORT_CT_MVAL[CT_MVAL_NUM] = {0};
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_MVAL);
#endif

CompileOption_MVal TCSUPPORT_CMCC_MVAL[CMCC_MVAL_NUM] = {0};
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CMCC_MVAL);
#endif

CompileOption_MVal TCSUPPORT_CUC_MVAL[CUC_MVAL_NUM] = {0};
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CUC_MVAL);
#endif

CompileOption_MVal TCSUPPORT_CT_JOYME_MVAL[JOYME_MVAL_NUM] = {0};
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_JOYME_MVAL);
#endif

CompileOption_MVal TCSUPPORT_NP_MVAL[NP_MVAL_NUM] = {0};
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_NP_MVAL);
#endif

CompileOption_MVal TCSUPPORT_PON_MVAL[PON_MVAL_NUM] = {0};
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_PON_MVAL);
#endif

CompileOption_MVal TCSUPPORT_SOC_MVAL[SOC_MVAL_NUM] = {0};
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_SOC_MVAL);
#endif

CompileOption_MVal TCSUPPORT_DP_MVAL[DP_MVAL_NUM] = {0};
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_DP_MVAL);
#endif

CompileOption_MVal TCSUPPORT_VOIP_MVAL[VOIP_MVAL_NUM] = {0};
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_VOIP_MVAL);
#endif

CompileOption_MVal TCSUPPORT_WIFI_COMMON_MVAL[WIFI_COMMON_MVAL_NUM] = {0};
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_WIFI_COMMON_MVAL);
#endif

CompileOption_MVal TCSUPPORT_WIFI_CHIP_MVAL[WIFI_CHIP_MVAL_NUM] = {0};
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_WIFI_CHIP_MVAL);
#endif

CompileOption_MVal TCSUPPORT_NPU_MVAL[NPU_MVAL_NUM] = {0};
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_NPU_MVAL);
#endif

#if 0
CompileOption_Val TCSUPPORT_CDS_VTAG_TRANSPARENT_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CDS_VTAG_TRANSPARENT_VAL);
#endif
#endif

CompileOption_MVal TCSUPPORT_OPENWRT_MVAL[OPENWRT_MVAL_NUM] = {0};
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_OPENWRT_MVAL);
#endif

CompileOption_MVal TCSUPPORT_CF_MVAL[FH_MVAL_NUM] = {0};
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CF_MVAL);
#endif

CompileOption_UVal TCSUPPORT_FUNC_UVAL[FUNC_UVAL_NUM] = {0};
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_FUNC_UVAL);
#endif

void init_compileoption_val(void){
	
	memset(TCSUPPORT_PON_MVAL, 0, sizeof(TCSUPPORT_PON_MVAL));
#ifdef TCSUPPORT_PON_VLAN_FILTER
	TCSUPPORT_PON_VLAN_FILTER_VAL = 1;
#endif

#ifdef TCSUPPORT_PON_MAC_FILTER
	TCSUPPORT_PON_MAC_FILTER_VAL = 1;
#endif

#ifdef TCSUPPORT_PON_IP_HOST
	TCSUPPORT_PON_IP_HOST_VAL = 1;
#endif

#ifdef TCSUPPORT_PONMGR
	TCSUPPORT_PONMGR_VAL = 1;
#endif

#ifdef TCSUPPORT_PMMGR
	TCSUPPORT_PMMGR_VAL = 1;
#endif

#ifdef TCSUPPORT_WAN_GPON
	TCSUPPORT_WAN_GPON_VAL = 1;
#endif

#ifdef TCSUPPORT_WAN_EPON
	TCSUPPORT_WAN_EPON_VAL = 1;
#endif

#ifdef TCSUPPORT_OMCI
	TCSUPPORT_OMCI_VAL = 1;
#endif

#ifdef TCSUPPORT_EPON_OAM_CTC
	TCSUPPORT_EPON_OAM_CTC_VAL = 1;
#endif

#ifdef TCSUPPORT_OMCI_ALCATEL
	TCSUPPORT_OMCI_ALCATEL_VAL = 1;
#endif

#ifdef TCSUPPORT_GPON_MAPPING
	TCSUPPORT_GPON_MAPPING_VAL = 1;
#endif

#ifdef TCSUPPORT_GPON_MAPPING
	TCSUPPORT_EPON_MAPPING_VAL = 1;
#endif

#ifdef TCSUPPORT_PON_USER_ISOLATION
	TCSUPPORT_PON_USER_ISOLATION_VAL = 1;
#endif

#ifdef TCSUPPORT_XPON_IGMP
	TCSUPPORT_XPON_IGMP_VAL = 1;
#endif

#ifdef TCSUPPORT_PON_SFU_HGU_HYBRID
	TCSUPPORT_PON_SFU_HGU_HYBRID_VAL = 1;
#endif

#ifdef TCSUPPORT_PON_VLAN
	TCSUPPORT_PON_VLAN_VAL = 1;
#endif

#ifdef TCSUPPORT_OMCI_LAN_DEBUG
	TCSUPPORT_OMCI_LAN_DEBUG_VAL = 1;
#endif

#ifdef TCSUPPORT_XPON_LED
	TCSUPPORT_XPON_LED_VAL = 1;
#endif

#ifdef TCSUPPORT_EPON_DUMMY
	TCSUPPORT_EPON_DUMMY_VAL = 1;
#endif

#ifdef TCSUPPORT_XPON_IGMP_CHT
	TCSUPPORT_XPON_IGMP_CHT_VAL = 1;
#endif

#ifdef TCSUPPORT_PON_ROSTELECOM
	TCSUPPORT_PON_ROSTELECOM_VAL = 1;
#endif

#ifdef TCSUPPORT_XPON_LED_UPGRADE
	TCSUPPORT_XPON_LED_UPGRADE_VAL = 1;
#endif

#ifdef TCSUPPORT_BBF_247
	TCSUPPORT_BBF_247_VAL = 1;
#endif

	memset(TCSUPPORT_SOC_MVAL, 0, sizeof(TCSUPPORT_SOC_MVAL));
#ifdef TCSUPPORT_SECURE_BOOT_V1
	TCSUPPORT_SECURE_BOOT_V1_VAL = 1;
#endif

#ifdef TCSUPPORT_CPU_MT7505
	TCSUPPORT_CPU_MT7505_VAL = 1;
#endif

#ifdef TCSUPPORT_CPU_MT7510
	TCSUPPORT_CPU_MT7510_VAL = 1;
#endif
	
#ifdef TCSUPPORT_CPU_MT7520
	TCSUPPORT_CPU_MT7520_VAL = 1;
#endif

#ifdef TCSUPPORT_VPN
	TCSUPPORT_VPN_VAL = 1;
#endif

#ifdef TCSUPPORT_USBHOST
	TCSUPPORT_USBHOST_VAL = 1;
#endif

#ifdef TCSUPPORT_CPU_PERFORMANCE_TEST
	TCSUPPORT_CPU_PERFORMANCE_TEST_VAL = 1;
#endif

#if defined(TCSUPPORT_CPU_EN7512) || defined(TCSUPPORT_CPU_EN7521)
	TCSUPPORT_CPU_EN75XX_VAL = 1;
#endif

#if defined(TCSUPPORT_CPU_EN7580)
	TCSUPPORT_CPU_EN758X_VAL = 1;
#endif

#if defined(TCSUPPORT_CPU_EN7528)
	TCSUPPORT_CPU_EN7528_VAL = 1;
#endif

#if defined(TCSUPPORT_CPU_EN7512)
	TCSUPPORT_CPU_EN7512_VAL = 1;
#endif

#ifdef TCSUPPORT_IPSEC_PASSTHROUGH
	TCSUPPORT_IPSEC_PASSTHROUGH_VAL = 1;
#endif

#ifdef TCSUPPORT_MIPS_1004K
	TCSUPPORT_MIPS_1004K_VAL = 1;
#endif

#ifdef TCSUPPORT_HIGHMEM
	TCSUPPORT_HIGHMEM_VAL = 1;
#endif

#ifdef TCSUPPORT_NEW_WDOG
	TCSUPPORT_NEW_WDOG_VAL = 1;
#endif

#ifdef TCSUPPORT_BB_256KB
	TCSUPPORT_BB_256KB_VAL = 1;
#endif

#ifdef TCSUPPORT_CPU_ARMV8
	TCSUPPORT_CPU_ARMV8_VAL = 1;
#endif

	memset(TCSUPPORT_DP_MVAL, 0, sizeof(TCSUPPORT_DP_MVAL));
#ifdef TCSUPPORT_RA_HWNAT
	TCSUPPORT_RA_HWNAT_VAL = 1;
#endif

#ifdef TCSUPPORT_MANUAL_ETHERNET_PORTMAP
	TCSUPPORT_MANUAL_ETHERNET_PORTMAP_VAL = 1;
#endif

#ifdef TCSUPPORT_VLAN_DOT1P
	TCSUPPORT_VLAN_DOT1P_VAL = 1;
#endif

#ifdef TCSUPPORT_VLAN_PASSTHROUGH
	TCSUPPORT_VLAN_PASSTHROUGH_VAL = 1;
#endif

#ifdef TCSUPPORT_HWNAT_L2VID
	TCSUPPORT_HWNAT_L2VID_VAL = 1;
#endif

#ifdef TCSUPPORT_IFC_EN
	TCSUPPORT_IFC_EN_VAL = 1;
#endif

#ifdef TCSUPPORT_WAN_ETHER
	TCSUPPORT_WAN_ETHER_VAL = 1;
#endif

#ifdef TCSUPPORT_WAN_XSI
	TCSUPPORT_WAN_XSI_VAL = 1;
#endif

#ifdef TCSUPPORT_HSGMII_LAN
	TCSUPPORT_HSGMII_LAN_VAL = 1;
#endif

#ifdef TCSUPPORT_ACTIVE_ETHERNET_WAN
	TCSUPPORT_ACTIVE_ETHERNET_WAN_VAL = 1;
#endif

#ifdef TCSUPPORT_HWNAT
	TCSUPPORT_HWNAT_VAL = 1;
#endif

#ifdef TCSUPPORT_HWNAT_WAN_ACCOUNT
	TCSUPPORT_HWNAT_WAN_ACCOUNT_VAL = 1;
#endif

#ifdef TCSUPPORT_2PORTS
	TCSUPPORT_2PORTS_VAL = 1;
#endif

#ifdef TCSUPPORT_MULTICAST_SPEED
	TCSUPPORT_MULTICAST_SPEED_VAL = 1;
#endif

#ifdef TCSUPPORT_IGMP_SET_GROUP
	TCSUPPORT_IGMP_SET_GROUP_VAL = 1;
#endif

#if defined(TCSUPPORT_PON_VLAN) || defined(TCSUPPORT_PON_MAC_FILTER) || (defined(TCSUPPORT_GPON_MAPPING) && defined(TCSUPPORT_GPON_DOWNSTREAM_MAPPING))
	RA_NAT_EXE_VAL = 1;
#endif

#ifdef TCSUPPORT_SWNAT
	TCSUPPORT_SWNAT_VAL = 1;
#endif

#ifdef TCSUPPORT_TC2031
	TCSUPPORT_TC2031_VAL = 1;
#endif

#ifdef TCSUPPORT_DS_HWNAT_OFFLOAD
	TCSUPPORT_DS_HWNAT_OFFLOAD_VAL = 1;
#endif

#ifdef TCSUPPORT_WAN_UPSTREAM_REMARK
	TCSUPPORT_WAN_UPSTREAM_REMARK_VAL = 1;
#endif

#ifdef TCSUPPORT_SMUX_HW_STAT
	TCSUPPORT_SMUX_HW_STAT_VAL = 1;
#endif

#ifdef TCSUPPORT_RA_HWNAT_ENHANCE_HOOK
	TCSUPPORT_RA_HWNAT_ENHANCE_HOOK_VAL = 1;
#endif

#ifdef TCSUPPORT_LRO_ENABLE
	TCSUPPORT_LRO_ENABLE_VAL = 1;
#endif

#ifdef TCSUPPORT_HWNAT_ADD_DEL_API
	TCSUPPORT_HWNAT_ADD_DEL_API_VAL = 1;
#endif

#ifdef TCSUPPORT_MULIF_WAN_SAME_MAC
	TCSUPPORT_MULIF_WAN_SAME_MAC_VAL = 1;
#endif

#ifdef TCSUPPORT_MULTI_USER_ITF
	TCSUPPORT_MULTI_USER_ITF_VAL = 1;
#endif

#ifdef TCSUPPORT_GRE_TUNNEL_HWNAT
	TCSUPPORT_GRE_TUNNEL_HWNAT_VAL = 1;
#endif

#ifdef TCSUPPORT_MULTI_SWITCH_EXT
	TCSUPPORT_MULTI_SWITCH_EXT_VAL = 1;
#endif

#ifdef TCSUPPORT_QDMA_WAN_FOR_ETHER
	TCSUPPORT_QDMA_WAN_FOR_ETHER_VAL = 1;
#endif

#ifdef TCSUPPORT_VLAN_ACCESS_TRUNK
	TCSUPPORT_VLAN_ACCESS_TRUNK_VAL = 1;
#endif

#ifdef TCSUPPORT_QOS_EIGHT_QUEUE
	TCSUPPORT_QOS_EIGHT_QUEUE_VAL = 1;
#endif

#ifdef TCSUPPORT_EXTENDED_VLAN
	TCSUPPORT_EXTENDED_VLAN_VAL = 1;
#endif

#ifdef TCSUPPORT_UNKNOW_MULTICAST_COUNT
	TCSUPPORT_UNKNOW_MULTICAST_COUNT_VAL = 1;
#endif

#ifdef TCSUPPORT_VXLAN_HW_OFFLOAD
	TCSUPPORT_VXLAN_HW_OFFLOAD_VAL = 1;
#endif

#ifdef TCSUPPORT_ACCOUNT_METER_V2
	TCSUPPORT_ACCOUNT_METER_V2_VAL = 1;
#endif

	memset(TCSUPPORT_VOIP_MVAL, 0, sizeof(TCSUPPORT_VOIP_MVAL));
#ifdef TCSUPPORT_VOIP
	TCSUPPORT_VOIP_VAL = 1;
#endif

#ifdef TCSUPPORT_ZARLINK_LE89156B
	TCSUPPORT_ZARLINK_LE89156B_VAL = 1;
#endif

#ifdef TCSUPPORT_VOIP_LED_APPCTRL
	TCSUPPORT_VOIP_LED_APPCTRL_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_VOIP_CRYPT
	TCSUPPORT_CT_VOIP_CRYPT_VAL = 1;
#endif

#ifdef TCSUPPORT_VOIP_SIP_DNS
	TCSUPPORT_VOIP_SIP_DNS_VAL = 1;
#endif

#ifdef TCSUPPORT_ZARLINK_LE89156A
	TCSUPPORT_ZARLINK_LE89156A_VAL = 1;
#endif

#ifdef TCSUPPORT_MULTI_BOOT
	TCSUPPORT_MULTI_BOOT_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_1FXS
	TCSUPPORT_CT_1FXS_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_VOIP_SIP
	TCSUPPORT_CT_VOIP_SIP_VAL = 1;
#endif

#ifdef TCSUPPORT_ECN_SIP
	TCSUPPORT_ECN_SIP_VAL = 1;
#endif

#ifdef TCSUPPORT_ECN_MEGACO
	TCSUPPORT_ECN_MEGACO_VAL = 1;
#endif

#ifdef TCSUPPORT_SLIC_ZL88801
	TCSUPPORT_SLIC_ZL88801_VAL = 1;
#endif

	memset(TCSUPPORT_WIFI_COMMON_MVAL, 0, sizeof(TCSUPPORT_WIFI_COMMON_MVAL));
#ifdef TCSUPPORT_WLAN
	TCSUPPORT_WLAN_VAL = 1;
#endif

#ifdef TCSUPPORT_WLAN_AC
	TCSUPPORT_WLAN_AC_VAL = 1;
#endif

#ifdef TCSUPPORT_WLAN_MULTIDRIVER
	TCSUPPORT_WLAN_MULTIDRIVER_VAL = 1;
#endif

#ifdef TCSUPPORT_DLF_CTRL
	TCSUPPORT_DLF_CTRL_VAL = 1;
#endif

#ifdef TCSUPPORT_WLAN_SW_RPS
	TCSUPPORT_WLAN_SW_RPS_VAL = 1;
#endif

#ifdef TCSUPPORT_WLAN_WDS
	TCSUPPORT_WLAN_WDS_VAL = 1;
#endif

#ifdef TCSUPPORT_MESH_ROLE_AUTO_DETECT
	TCSUPPORT_MESH_ROLE_AUTO_DETECT_VAL = 1;
#endif

#ifdef TCSUPPORT_MESH_ETHETWAN_PORT_ONBOARDING
	TCSUPPORT_MESH_ETHETWAN_PORT_ONBOARDING_VAL = 1;
#endif

#ifdef TCSUPPORT_WLAN_MT76_MAC80211
	TCSUPPORT_WLAN_MT76_MAC80211_VAL = 1;
#endif

#ifdef TCSUPPORT_WLAN_INODE
	TCSUPPORT_WLAN_INODE_VAL = 1;
#endif

	memset(TCSUPPORT_WIFI_CHIP_MVAL, 0, sizeof(TCSUPPORT_WIFI_CHIP_MVAL));
#ifdef TCSUPPORT_WLAN_MT7592
	TCSUPPORT_WLAN_MT7592_VAL = 1;
#endif

#ifdef TCSUPPORT_WLAN_RT3390
	TCSUPPORT_WLAN_RT3390_VAL = 1;
#endif

#ifdef TCSUPPORT_WLAN_RT3090
	TCSUPPORT_WLAN_RT3090_VAL = 1;
#endif

#ifdef TCSUPPORT_WLAN_RT5392
	TCSUPPORT_WLAN_RT5392_VAL = 1;
#endif

#ifdef TCSUPPORT_WLAN_MT7615_TXOFFLOAD
	TCSUPPORT_WLAN_MT7615_TXOFFLOAD_VAL = 1;
#endif

#ifdef MT7613E
	TCSUPPORT_DUAL_WLAN_MT7613E_VAL = 1;
#endif

	memset(TCSUPPORT_NPU_MVAL, 0, sizeof(TCSUPPORT_NPU_MVAL));
#ifdef TCSUPPORT_NPU
    TCSUPPORT_NPU_VAL = 1;
#endif

#ifdef TCSUPPORT_NPU_TUNNEL_OFFLOAD
    TCSUPPORT_NPU_TUNNEL_OFFLOAD_VAL = 1;
#endif

#ifdef TCSUPPORT_NPU_WIFI_OFFLOAD
	TCSUPPORT_NPU_WIFI_OFFLOAD_VAL = 1;
#endif

#ifdef TCSUPPORT_NPU_WIFI_TX
	TCSUPPORT_NPU_WIFI_TX_VAL = 1;
#endif
	 	   
	memset(TCSUPPORT_FUNC_MVAL, 0, sizeof(TCSUPPORT_FUNC_MVAL));
#ifdef TCSUPPORT_SAMBA_4
	TCSUPPORT_SAMBA_4_VAL = 1;
#endif

#ifdef TCSUPPORT_LANMGR_NG
	TCSUPPORT_LANMGR_NG_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_L2TP_VPN
	TCSUPPORT_CT_L2TP_VPN_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_MULTI_LAN_PD
	TCSUPPORT_CT_MULTI_LAN_PD_VAL = 1;
#endif

#ifdef TCSUPPORT_XSI_ENABLE
	TCSUPPORT_XSI_ENABLE_VAL = 1;
#endif

#ifdef TCSUPPORT_VXLAN
	TCSUPPORT_VXLAN_VAL = 1;
#endif

#ifdef TCSUPPORT_VLAN_TAG
	TCSUPPORT_VLAN_TAG_VAL = 1;
#endif

#ifdef TCSUPPORT_BACKUPROMFILE
	TCSUPPORT_BACKUPROMFILE_VAL = 1;
#endif

#ifdef TCSUPPORT_PRODUCTIONLINE
	TCSUPPORT_PRODUCTIONLINE_VAL = 1;
#endif

#ifdef TCSUPPORT_NOTDEFAULTROMFILEAREA
	TCSUPPORT_NOTDEFAULTROMFILEAREA_VAL = 1;
#endif

#ifdef TCSUPPORT_AUTOBENCH
	TCSUPPORT_AUTOBENCH_VAL = 1;
#endif

#ifdef TCSUPPORT_ITMS_CONFIG_AS_DEFAULT
	TCSUPPORT_ITMS_CONFIG_AS_DEFAULT_VAL = 1;
#endif

#ifdef TCSUPPORT_DMS
	TCSUPPORT_DMS_VAL = 1;
#endif

#ifdef TCSUPPORT_TR69_IP_HOST
	TCSUPPORT_TR69_IP_HOST_VAL = 1;
#endif

#ifdef TCSUPPORT_WAN_ATM
	TCSUPPORT_WAN_ATM_VAL = 1;
#endif

#ifdef TCSUPPORT_LAN_VLAN
	TCSUPPORT_LAN_VLAN_VAL = 1;
#endif

#ifdef TCSUPPORT_LAN_VLAN_RANGE
	TCSUPPORT_LAN_VLAN_RANGE_VAL = 1;
#endif

#ifdef TCSUPPORT_TCAPI_ENHANCE
	TCSUPPORT_TCAPI_ENHANCE_VAL = 1;
#endif

#ifdef TCSUPPORT_SYSLOG
	TCSUPPORT_SYSLOG_VAL = 1;
#endif

#ifdef TCSUPPORT_RESERVEAREA_EXTEND
	TCSUPPORT_RESERVEAREA_EXTEND_VAL = 1;
#endif

#ifdef TCSUPPORT_ROUTEPOLICY_PRIOR_PORTBIND
	TCSUPPORT_ROUTEPOLICY_PRIOR_PORTBIND_VAL = 1;
#endif

#ifdef TCSUPPORT_TRUE_LANDING_PAGE
	TCSUPPORT_TRUE_LANDING_PAGE_VAL = 1;
#endif

#ifdef TCSUPPORT_CWMP
	TCSUPPORT_CWMP_VAL = 1;
#endif

#ifdef TCSUPPORT_CWMP_TR181
	TCSUPPORT_CWMP_TR181_VAL = 1;
#endif

#ifdef TCSUPPORT_CWMP_NO_HOST
	TCSUPPORT_CWMP_NO_HOST_VAL = 1;
#endif

#ifdef TCSUPPORT_TEST_WLAN_SHORTCUT
	TCSUPPORT_TEST_WLAN_SHORTCUT_VAL = 1;
#endif
	
#ifdef TCSUPPORT_INIC_CLIENT
	TCSUPPORT_INIC_CLIENT_VAL = 1;
#endif

#ifdef TCSUPPORT_KEYPARA_STORE
	TCSUPPORT_KEYPARA_STORE_VAL = 1;
#endif

#ifdef TCSUPPORT_START_TRAP
	TCSUPPORT_START_TRAP_VAL = 1;
#endif

#ifdef TCSUPPORT_SYSLOG_ENHANCE
	TCSUPPORT_SYSLOG_ENHANCE_VAL = 1;
#endif

#ifdef TCSUPPORT_CWMP_FAST_GET
	TCSUPPORT_CWMP_FAST_GET_VAL = 1;
#endif

#ifdef TCSUPPORT_CD_DDNS
	TCSUPPORT_CD_DDNS_VAL = 1;
#endif

#ifdef TCSUPPORT_CMDPROMPT
	TCSUPPORT_CMDPROMPT_VAL = 1;
#endif

#ifdef TCSUPPORT_RANDOM_INFORM
	TCSUPPORT_RANDOM_INFORM_VAL = 1;
#endif

#ifdef CWMP_REDIRECT
	CWMP_REDIRECT_VAL = 1;
#endif

#ifdef TCSUPPORT_TR69_BIND_PVC
	TCSUPPORT_TR69_BIND_PVC_VAL = 1;
#endif

#ifdef TCSUPPORT_NO_BOOT_VALUECHANGE
	TCSUPPORT_NO_BOOT_VALUECHANGE_VAL = 1;
#endif

#ifdef TCSUPPORT_CROSS_REBOOT
	TCSUPPORT_CROSS_REBOOT_VAL = 1;
#endif

#ifdef TCSUPPORT_BHARTI
	TCSUPPORT_BHARTI_VAL = 1;
#endif

#ifdef TCSUPPORT_TTNET
	TCSUPPORT_TTNET_VAL = 1;
#endif

#ifdef TCSUPPORT_CWMP_PRECISE_TIME
	TCSUPPORT_CWMP_PRECISE_TIME_VAL = 1;
#endif

#ifdef TCSUPPORT_PROLINE_CMD_ACTION
	TCSUPPORT_PROLINE_CMD_ACTION_VAL = 1;
#endif

#ifdef TCSUPPORT_MULTISERVICE_ON_WAN
	TCSUPPORT_MULTISERVICE_ON_WAN_VAL = 1;
#endif

#ifdef TCSUPPORT_UPNP_ENHANCE
	TCSUPPORT_UPNP_ENHANCE_VAL = 1;
#endif

#ifdef TCSUPPORT_WAN_PTM
	TCSUPPORT_WAN_PTM_VAL = 1;
#endif

#ifdef TCSUPPORT_CD_NEW_GUI
	TCSUPPORT_CD_NEW_GUI_VAL = 1;
#endif

#ifdef TCSUPPORT_CCT
	TCSUPPORT_CCT_VAL = 1;
#endif

#ifdef TCSUPPORT_CLMP
	TCSUPPORT_CLMP_VAL = 1;
#endif

#ifdef TCSUPPORT_SAGECOM_CWMP
	TCSUPPORT_SAGECOM_CWMP_VAL = 1;
#endif

#ifdef TCSUPPORT_FW_UPGRADE_DELAY
	TCSUPPORT_FW_UPGRADE_DELAY_VAL = 1;
#endif

#ifdef AZTECH_CWMP_REORDER
	AZTECH_CWMP_REORDER_VAL = 1;
#endif

#ifdef TCSUPPORT_CWMP_IOT_STRINGTYPE
	TCSUPPORT_CWMP_IOT_STRINGTYPE_VAL = 1;
#endif

#ifdef TCSUPPORT_CWMP_FAULT_RESPONSE
	TCSUPPORT_CWMP_FAULT_RESPONSE_VAL = 1;
#endif

#ifdef TCSUPPORT_CWMP_CRPORTCHANGE
	TCSUPPORT_CWMP_CRPORTCHANGE_VAL = 1;
#endif

#ifdef TCSUPPORT_WEB_INTERCEPTION
	TCSUPPORT_WEB_INTERCEPTION_VAL = 1;
#endif

#ifdef TCSUPPORT_MNT_CONF
	TCSUPPORT_MNT_CONF_VAL = 1;
#endif

#ifdef TCSUPPORT_FTP_USB
	TCSUPPORT_FTP_USB_VAL = 1;
#endif

#ifdef TCSUPPORT_IPV6_FIREWALL
	TCSUPPORT_IPV6_FIREWALL_VAL = 1;
#endif

#ifdef TCSUPPORT_IPV6_FIREWALL_RFC2827
	TCSUPPORT_IPV6_FIREWALL_RFC2827_VAL = 1;
#endif

#ifdef TCSUPPORT_PRODUCTIONLINE_CONTENT
	TCSUPPORT_PRODUCTIONLINE_CONTENT_VAL = 1;
#endif

#ifdef TCSUPPORT_CHT_RAMENU
	TCSUPPORT_CHT_RAMENU_VAL = 1;
#endif

#ifdef TCSUPPORT_IPV6
	TCSUPPORT_IPV6_VAL = 1;
#endif

#ifdef TCSUPPORT_UPSTREAM_VLAN_POLICER
	TCSUPPORT_UPSTREAM_VLAN_POLICER_VAL = 1;
#endif

#ifdef TCSUPPORT_GPON_DOWNSTREAM_MAPPING
	TCSUPPORT_GPON_DOWNSTREAM_MAPPING_VAL = 1;
#endif

#ifdef TCSUPPORT_ARC_CWMP
	TCSUPPORT_ARC_CWMP_VAL = 1;
#endif

#ifdef TCSUPPORT_TR143_CURL_UPLOAD
	TCSUPPORT_TR143_CURL_UPLOAD_VAL = 1;
#endif

#ifdef TCSUPPORT_CSC_EEUROPE
	TCSUPPORT_CSC_EEUROPE_VAL = 1;
#endif

#ifdef TCSUPPORT_UPGRADE_NO_REBOOT
	TCSUPPORT_UPGRADE_NO_REBOOT_VAL = 1;
#endif

#ifdef TCSUPPORT_TR64_DIGEST_AUTH
	TCSUPPORT_TR64_DIGEST_AUTH_VAL = 1;
#endif

#ifdef TCSUPPORT_PORT_ISOLATION
	TCSUPPORT_PORT_ISOLATION_VAL = 1;
#endif

#ifdef TCSUPPORT_TLS
	TCSUPPORT_TLS_VAL = 1;
#endif

#ifdef TCSUPPORT_IPV6_CWMP
	TCSUPPORT_IPV6_CWMP_VAL = 1;
#endif

#ifdef TCSUPPORT_CWMP_SSL
	TCSUPPORT_CWMP_SSL_VAL = 1;
#endif

#ifdef TCSUPPORT_CWMP_OPENSSL
	TCSUPPORT_CWMP_OPENSSL_VAL = 1;
#endif

#ifdef TCSUPPORT_CWMP_NG
	TCSUPPORT_CWMP_NG_VAL = 1;
#endif

#ifdef TCSUPPORT_CFG_NG
	TCSUPPORT_CFG_NG_VAL = 1;
#endif

#ifdef TCSUPPORT_IPV6_CEROUTER
	TCSUPPORT_IPV6_CEROUTER_VAL = 1;
#endif

#ifdef TCSUPPORT_CG_DS_ADD_TAG
	TCSUPPORT_CG_DS_ADD_TAG_VAL = 1;
#endif

#ifdef TCSUPPORT_PORTBIND
	TCSUPPORT_PORTBIND_VAL = 1;
#endif

#ifdef TCSUPPORT_ASYM_VOD
	TCSUPPORT_ASYM_VOD_VAL = 1;
#endif

#ifdef TCSUPPORT_CHARSET_CHANGE
	TCSUPPORT_CHARSET_CHANGE_VAL = 1;
#endif

#ifdef TCSUPPORT_DSL_PHYMODE
	TCSUPPORT_DSL_PHYMODE_VAL = 1;
#endif

#ifdef TCSUPPORT_DSL_PHYMODE_HOST
	TCSUPPORT_DSL_PHYMODE_HOST_VAL = 1;
#endif

#ifdef TCSUPPORT_APPS_NOROOT_PERM
	TCSUPPORT_APPS_NOROOT_PERM_VAL = 1;
#endif

#ifdef TCSUPPORT_TEST_STRESS_NG
	TCSUPPORT_TEST_STRESS_NG_VAL = 1;
#endif

#ifdef TCSUPPORT_TEST_STRESS_NG_V01310
	TCSUPPORT_TEST_STRESS_NG_V01310_VAL = 1;
#endif
  
#ifdef TCSUPPORT_SISM_HOST
	TCSUPPORT_SISM_HOST_VAL = 1;
#else
	TCSUPPORT_SISM_HOST_VAL = 0;
#endif

	memset(TCSUPPORT_CUSTOM_MVAL, 0, sizeof(TCSUPPORT_CUSTOM_MVAL));
#ifdef TCSUPPORT_CT_CONGW_CH
	TCSUPPORT_CT_CONGW_CH_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PON_GD
	TCSUPPORT_CT_PON_GD_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PON_GDV20
	TCSUPPORT_CT_PON_GDV20_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PON_CZ_GDCS
	TCSUPPORT_CT_PON_CZ_GDCS_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PON_CY
	TCSUPPORT_CT_PON_CY_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PON_CY_JX
	TCSUPPORT_CT_PON_CY_JX_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PON_JS
	TCSUPPORT_CT_PON_JS_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_FJ
	TCSUPPORT_CT_FJ_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PON_GX
	TCSUPPORT_CT_PON_GX_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PON_CQ
	TCSUPPORT_CT_PON_CQ_VAL = 1;
#endif

#ifdef TCSUPPORT_CY_PON
	TCSUPPORT_CY_PON_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PON_C9
	TCSUPPORT_CT_PON_C9_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PON_JS_IP
	TCSUPPORT_CT_PON_JS_IP_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PON_YN
	TCSUPPORT_CT_PON_YN_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PON_NMG
	TCSUPPORT_CT_PON_NMG_VAL = 1;
#endif

#ifdef TCSUPPORT_C1_MS
	TCSUPPORT_C1_MS_VAL = 1;
#endif

#ifdef TCSUPPORT_C1_ZY
	TCSUPPORT_C1_ZY_VAL = 1;
#endif

#ifdef TCSUPPORT_C7
	TCSUPPORT_C7_VAL = 1;
#endif

#ifdef TCSUPPORT_CY
	TCSUPPORT_CY_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PON_C7
	TCSUPPORT_CT_PON_C7_VAL = 1;
#endif

#ifdef TCSUPPORT_CY_E8_SFU
	TCSUPPORT_CY_E8_SFU_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PON_JX
	TCSUPPORT_CT_PON_JX_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PON_SK
	TCSUPPORT_CT_PON_SK_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PON_CN_JS
	TCSUPPORT_CT_PON_CN_JS_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PON_CZ_GD
	TCSUPPORT_CT_PON_CZ_GD_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PON_CZ_NX
	TCSUPPORT_CT_PON_CZ_NX_VAL = 1;
#endif

#ifdef TCSUPPORT_CDS
	TCSUPPORT_CDS_VAL = 1;
#endif

#ifdef TCSUPPORT_CZ_GENERAL
	TCSUPPORT_CZ_GENERAL_VAL = 1;
#endif

#ifdef TCSUPPORT_CZ_TM
	TCSUPPORT_CZ_TM_VAL = 1;
#endif

#ifdef TCSUPPORT_C1_NEW_GUI
	TCSUPPORT_C1_NEW_GUI_VAL = 1;
#endif

#ifdef TCSUPPORT_C1_OBM
	TCSUPPORT_C1_OBM_VAL = 1;
#endif

#ifdef TCSUPPORT_CHS
	TCSUPPORT_CHS_VAL = 1;
#endif

#ifdef TCSUPPORT_C9_ROST_LED
	TCSUPPORT_C9_ROST_LED_VAL = 1;
#endif

#ifdef TCSUPPORT_VNPTT
	TCSUPPORT_VNPTT_VAL = 1;
#endif

#ifdef TCSUPPORT_CCA
	TCSUPPORT_CCA_VAL = 1;
#endif

#ifdef TCSUPPORT_CD_WIND
	TCSUPPORT_CD_WIND_VAL = 1;
#endif

#ifdef TCSUPPORT_CRJO
	TCSUPPORT_CRJO_VAL = 1;
#endif

#ifdef TCSUPPORT_GOOGLE_FIBER
	TCSUPPORT_GOOGLE_FIBER_VAL = 1;
#endif

#ifdef TCSUPPORT_ALPHION_PON
	TCSUPPORT_ALPHION_PON_VAL = 1;
#endif

#ifdef TCSUPPORT_CDS_CT
	TCSUPPORT_CDS_CT_VAL = 1;
#endif

#ifdef TCSUPPORT_CATV_GD
	TCSUPPORT_CATV_GD_VAL = 1;
#endif

#ifdef TCSUPPORT_DZS
	TCSUPPORT_DZS_VAL = 1;
#endif

	memset(TCSUPPORT_CT_MVAL, 0, sizeof(TCSUPPORT_CT_MVAL));
#ifdef TCSUPPORT_CT
	TCSUPPORT_CT_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_APPROUTE
	TCSUPPORT_CT_APPROUTE_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_APPFILTER
	TCSUPPORT_CT_APPFILTER_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_DSL_EX
	TCSUPPORT_CT_DSL_EX_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PON_BIND2
	TCSUPPORT_CT_PON_BIND2_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PON
	TCSUPPORT_CT_PON_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_UPG_PINGPONG
	TCSUPPORT_CT_UPG_PINGPONG_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_MIDWARE
	TCSUPPORT_CT_MIDWARE_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_BACKUPROMFILEENCHANCEMENT
	TCSUPPORT_CT_BACKUPROMFILEENCHANCEMENT_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PHONEAPP
	TCSUPPORT_CT_PHONEAPP_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_DEV_ACCESS_TYPE
	TCSUPPORT_CT_DEV_ACCESS_TYPE_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_ECN_GZ
	TCSUPPORT_CT_ECN_GZ_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_MONITORCOLLECTOR
	TCSUPPORT_CT_MONITORCOLLECTOR_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PPPOE_EMULATOR
	TCSUPPORT_CT_PPPOE_EMULATOR_VAL = 1;
#endif

#ifdef CT_COM_DEVICEREG
	CT_COM_DEVICEREG_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_UPNP_DM
	TCSUPPORT_CT_UPNP_DM_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PPPINFORM
	TCSUPPORT_CT_PPPINFORM_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_SWQOS
	TCSUPPORT_CT_SWQOS_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PORT_BIND
	TCSUPPORT_CT_PORT_BIND_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_GUIACCESSLIMIT
	TCSUPPORT_CT_GUIACCESSLIMIT_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PPPOEPROXY
	TCSUPPORT_CT_PPPOEPROXY_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_ZIPROMFILE
	TCSUPPORT_CT_ZIPROMFILE_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_E8B_ADSL
	TCSUPPORT_CT_E8B_ADSL_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_WANNODE_MAPPING
	TCSUPPORT_CT_WANNODE_MAPPING_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_BLOCK_PROCESS
	TCSUPPORT_CT_BLOCK_PROCESS_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_SERVICELIST_E8C
	TCSUPPORT_CT_SERVICELIST_E8C_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_ALARMMONITOR
	TCSUPPORT_CT_ALARMMONITOR_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_INFORM_NODE
	TCSUPPORT_CT_INFORM_NODE_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_LONG_RESETBTN
	TCSUPPORT_CT_LONG_RESETBTN_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PPP_ONDEMAND
	TCSUPPORT_CT_PPP_ONDEMAND_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PPP_MANUALLY
	TCSUPPORT_CT_PPP_MANUALLY_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_CWMP_ZIPROMFILE
	TCSUPPORT_CT_CWMP_ZIPROMFILE_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_FTP_DOWNLOADCLIENT
	TCSUPPORT_CT_FTP_DOWNLOADCLIENT_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_NEWGUI
	TCSUPPORT_CT_NEWGUI_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_HWQOS
	TCSUPPORT_CT_HWQOS_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_VLAN_BIND
	TCSUPPORT_CT_VLAN_BIND_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_DSLITE
	TCSUPPORT_CT_DSLITE_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_STBMAC_REPORT
	TCSUPPORT_CT_STBMAC_REPORT_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PMINFORM
	TCSUPPORT_CT_PMINFORM_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PON_HUB
	TCSUPPORT_CT_PON_HUB_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_ADSL_HN
	TCSUPPORT_CT_ADSL_HN_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PON_SC
	TCSUPPORT_CT_PON_SC_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PON_C9_HUN
	TCSUPPORT_CT_PON_C9_HUN_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_TR143_WGET_DOWNLOAD
	TCSUPPORT_CT_TR143_WGET_DOWNLOAD_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_ADSL_TJ
	TCSUPPORT_CT_ADSL_TJ_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_ADSL_BIND1
	TCSUPPORT_CT_ADSL_BIND1_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_NAMECHGNOTIFY
	TCSUPPORT_CT_NAMECHGNOTIFY_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_C5_HEN_SFU
	TCSUPPORT_CT_C5_HEN_SFU_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_SFU_SX
	TCSUPPORT_CT_SFU_SX_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_ITMS_TMOUT
	TCSUPPORT_CT_ITMS_TMOUT_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_CWMP_WORK_COMPATIBLE
	TCSUPPORT_CT_CWMP_WORK_COMPATIBLE_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_VPN_ONDEMAND
	TCSUPPORT_CT_VPN_ONDEMAND_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_VPN_PPTP
	TCSUPPORT_CT_VPN_PPTP_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_VLAN_TAG
	TCSUPPORT_CT_VLAN_TAG_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_WANNINDEX_INCREASE
	TCSUPPORT_CT_WANNINDEX_INCREASE_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_SIMCARD_SEPARATION
	TCSUPPORT_CT_SIMCARD_SEPARATION_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_2PORTS
	TCSUPPORT_CT_2PORTS_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_PON_SN
	TCSUPPORT_CT_PON_SN_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_WAN_PTM
	TCSUPPORT_CT_WAN_PTM_VAL = 1;
#endif

#ifdef TCSUPPORT_E8B
	TCSUPPORT_E8B_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_STANDARD_E8C
	TCSUPPORT_CT_STANDARD_E8C_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_BUTTONDETECT
	TCSUPPORT_CT_BUTTONDETECT_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_HWNAT_OFFLOAD
	TCSUPPORT_CT_HWNAT_OFFLOAD_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_MAP_INSIDE_AGENT
	TCSUPPORT_CT_MAP_INSIDE_AGENT_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_DS_LIMIT
	TCSUPPORT_CT_DS_LIMIT_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_IGMP_PPPOE_TO_IPOE
	TCSUPPORT_CT_IGMP_PPPOE_TO_IPOE_VAL = 1;
#endif

	memset(TCSUPPORT_CMCC_MVAL, 0, sizeof(TCSUPPORT_CMCC_MVAL));
#ifdef TCSUPPORT_CMCC
	TCSUPPORT_CMCC_VAL = 1;
#endif

#ifdef TCSUPPORT_CMCCV2
	TCSUPPORT_CMCCV2_VAL = 1;
#endif

#ifdef TCSUPPORT_CMCC_GANSU
	TCSUPPORT_CMCC_GANSU_VAL = 1;
#endif

#ifdef TCSUPPORT_CMCC_ENTERPRISE
	TCSUPPORT_CMCC_ENTERPRISE_VAL = 1;
#endif

	memset(TCSUPPORT_CUC_MVAL, 0, sizeof(TCSUPPORT_CUC_MVAL));
#ifdef TCSUPPORT_CUC_FJ_SFU
	TCSUPPORT_CUC_FJ_SFU_VAL = 1;
#endif

#ifdef TCSUPPORT_CUC_C5_2P
	TCSUPPORT_CUC_C5_2P_VAL = 1;
#endif

#ifdef TCSUPPORT_CUC_CWMP_PARAMETER
	TCSUPPORT_CUC_CWMP_PARAMETER_VAL = 1;
#endif

#ifdef TCSUPPORT_CUC
	TCSUPPORT_CUC_VAL = 1;
#endif

#ifdef TCSUPPORT_C1_CUC
	TCSUPPORT_C1_CUC_VAL = 1;
#endif

#ifdef TCSUPPORT_CUC_QOS
	TCSUPPORT_CUC_QOS_VAL = 1;
#endif

#ifdef TCSUPPORT_CUC_PON_SD
	TCSUPPORT_CUC_PON_SD_VAL = 1;
#endif

	memset(TCSUPPORT_CT_JOYME_MVAL, 0, sizeof(TCSUPPORT_CT_JOYME_MVAL));
#ifdef TCSUPPORT_CT_JOYME4
	TCSUPPORT_CT_JOYME4_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_JOYME4_JC
	TCSUPPORT_CT_JOYME4_JC_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_IPOE_DETECT
	TCSUPPORT_CT_IPOE_DETECT_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_JOYME
	TCSUPPORT_CT_JOYME_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_JOYME2
	TCSUPPORT_CT_JOYME2_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_JOYME_BANDWIDTH
	TCSUPPORT_CT_JOYME_BANDWIDTH_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_DBUS
	TCSUPPORT_CT_DBUS_VAL = 1;
#endif

#ifdef TCSUPPORT_SDN_OVS
	TCSUPPORT_SDN_OVS_VAL = 1;
#endif

	memset(TCSUPPORT_NP_MVAL, 0, sizeof(TCSUPPORT_NP_MVAL));
#ifdef TCSUPPORT_NP
	TCSUPPORT_NP_VAL = 1;
#endif

#ifdef TCSUPPORT_NP_RAM_SHRINK
	TCSUPPORT_NP_RAM_SHRINK_VAL = 1;
#endif

#ifdef TCSUPPORT_NP_FTTR
	TCSUPPORT_NP_FTTR_VAL = 1;
#endif

#ifdef TCSUPPORT_NP_CTC
	TCSUPPORT_NP_CTC_VAL = 1;
#endif

#ifdef TCSUPPORT_CT_UBUS
	TCSUPPORT_CT_UBUS_VAL = 1;
#endif

#ifdef TCSUPPORT_NP_CMCC
	TCSUPPORT_NP_CMCC_VAL = 1;
#endif

#ifdef TCSUPPORT_ANDLINK
	TCSUPPORT_ANDLINK_VAL = 1;
#endif

#if 0 
#ifdef TCSUPPORT_CDS_VTAG_TRANSPARENT
	TCSUPPORT_CDS_VTAG_TRANSPARENT_VAL = 1;
#else
	TCSUPPORT_CDS_VTAG_TRANSPARENT_VAL = 0;
#endif
#endif

/* fix bug OSBNB00044996 by johnson.sun on 20150410 */	    
/* 0/8 for normal usage, no need set; 1~7/ 9~15 for user define */
memset(TCSUPPORT_CF_MVAL, 0, sizeof(TCSUPPORT_CF_MVAL));
#ifdef TCSUPPORT_FH_BOOTUP
	TCSUPPORT_FH_BOOTUP_VAL = 1;
#endif

#ifdef TCSUPPORT_FH_PON
	TCSUPPORT_FH_PON_VAL = 1;
#endif

#ifdef TCSUPPORT_FH_UNION
	TCSUPPORT_FH_UNION_VAL = 1;
#endif

#ifdef TCSUPPORT_FH_DP
	TCSUPPORT_FH_DP_VAL = 1;
#endif

#ifdef TCSUPPORT_PON_CF
	TCSUPPORT_PON_CF_VAL = 1;
#endif

#ifdef TCSUPPORT_EPON_OAM_LAN_DBG
	TCSUPPORT_EPON_OAM_LAN_DBG_VAL = 1;
#endif

#if defined(TCSUPPORT_XPON_HAL_API_QOS) 
	TCSUPPORT_XPON_HAL_API_QOS_VAL=1;
#endif

#if defined(TCSUPPORT_XPON_HAL_API) 
	TCSUPPORT_XPON_HAL_API_VAL=1;
#endif

#if defined(TCSUPPORT_XPON_HAL_API_EXT)
	TCSUPPORT_XPON_HAL_API_EXT_VAL=1;
#endif

#if defined(TCSUPPORT_CT_PON) || defined(TCSUPPORT_XPON_HAL_API_QOS) || defined(TCSUPPORT_XPON_HAL_API_EXT)
	TCSUPPORT_XPON_PON_QOS_VAL=1;
#endif

#ifdef TCSUPPORT_XPON_HAL_API_MCST
	TCSUPPORT_XPON_HAL_API_MCST_VAL = 1;
#endif

#ifdef TCSUPPORT_CF_JOYMEV2_PON
	TCSUPPORT_CF_JOYMEV2_PON_VAL = 1;
#endif

#ifdef TCSUPPORT_FWC_ENV
	TCSUPPORT_FWC_ENV_VAL = 1;
#endif

#ifdef TCSUPPORT_FH_SDN_PON
	TCSUPPORT_FH_SDN_PON_VAL = 1;
#endif

#ifdef TCSUPPORT_FWC_QOS
	TCSUPPORT_FWC_QOS_VAL = 1;
#endif

#ifdef TCSUPPORT_CF_FDB_VLAN
	TCSUPPORT_CF_FDB_VLAN_VAL = 1;
#endif

#ifdef TCSUPPORT_FWC_VLAN_TAG
	TCSUPPORT_FWC_VLAN_TAG_VAL = 1;
#endif

#ifdef TCSUPPORT_FWC_MCST
	TCSUPPORT_FWC_MCST_VAL = 1;
#endif

#ifdef TCSUPPORT_XPON_HAL_API_NG
	TCSUPPORT_XPON_HAL_API_NG_VAL = 1;
#endif

#ifdef TCSUPPORT_CF_UNIFIED_PLATFORM
	TCSUPPORT_CF_UNIFIED_PLATFORM_VAL = 1;
#endif

memset(TCSUPPORT_FUNC_UVAL, 0, sizeof(TCSUPPORT_FUNC_UVAL));
#if (TCSUPPORT_USER_DEFINE_FIRST_MAC == 1)
	TCSUPPORT_USER_DEFINE_FIRST_MAC_VAL = 1;
#elif (TCSUPPORT_USER_DEFINE_FIRST_MAC == 2)
	TCSUPPORT_USER_DEFINE_FIRST_MAC_VAL = 2;
#elif (TCSUPPORT_USER_DEFINE_FIRST_MAC == 3)
	TCSUPPORT_USER_DEFINE_FIRST_MAC_VAL = 3;
#elif (TCSUPPORT_USER_DEFINE_FIRST_MAC == 4)
	TCSUPPORT_USER_DEFINE_FIRST_MAC_VAL = 4;
#elif (TCSUPPORT_USER_DEFINE_FIRST_MAC == 5)
	TCSUPPORT_USER_DEFINE_FIRST_MAC_VAL = 5;
#elif (TCSUPPORT_USER_DEFINE_FIRST_MAC == 6)
	TCSUPPORT_USER_DEFINE_FIRST_MAC_VAL = 6;
#elif (TCSUPPORT_USER_DEFINE_FIRST_MAC == 7)
	TCSUPPORT_USER_DEFINE_FIRST_MAC_VAL = 7;
#elif (TCSUPPORT_USER_DEFINE_FIRST_MAC == 9)
	TCSUPPORT_USER_DEFINE_FIRST_MAC_VAL = 9;
#elif (TCSUPPORT_USER_DEFINE_FIRST_MAC == 10)
	TCSUPPORT_USER_DEFINE_FIRST_MAC_VAL = 10;
#elif (TCSUPPORT_USER_DEFINE_FIRST_MAC == 11)
	TCSUPPORT_USER_DEFINE_FIRST_MAC_VAL = 11;
#elif (TCSUPPORT_USER_DEFINE_FIRST_MAC == 12)
	TCSUPPORT_USER_DEFINE_FIRST_MAC_VAL = 12;
#elif (TCSUPPORT_USER_DEFINE_FIRST_MAC == 13)
	TCSUPPORT_USER_DEFINE_FIRST_MAC_VAL = 13;
#elif (TCSUPPORT_USER_DEFINE_FIRST_MAC == 14)
	TCSUPPORT_USER_DEFINE_FIRST_MAC_VAL = 14;
#elif (TCSUPPORT_USER_DEFINE_FIRST_MAC == 15)
	TCSUPPORT_USER_DEFINE_FIRST_MAC_VAL = 15;
#endif

	memset(TCSUPPORT_OPENWRT_MVAL, 0, sizeof(TCSUPPORT_OPENWRT_MVAL));
#ifdef TCSUPPORT_OPENWRT_MULTI_WAN
	TCSUPPORT_OPENWRT_MULTI_WAN_VAL = 1;
#endif

#ifdef TCSUPPORT_L2TP_VPN_HWNAT
	TCSUPPORT_L2TP_VPN_HWNAT_VAL = 1;
#endif

	return;
}



